---
title: "Non-overlapping Window Analysis for Empirical Datasets"
author: "Jeremias Ivan"
date: "`r format(Sys.time(), '%d %B %Y, %H:%M%p')`"

output:
  html_document:
    code_folding: show
    toc: true
    toc_float: true

params:
  # general
  codedir: "~/SimNOW/empirical_analysis"
  prefix: "sim"
  outdir: "~/simulation"
  thread: 5
  redo: FALSE
  
  # IQ-Tree2
  iqtree2dir: "~/iqtree2"
  set_blmin: TRUE
  set_model: TRUE
  dna_model: "JC"

  bootstrap: 1000
  bootstrap_type: ""
  outgroup: ""
  
  # NOW analysis
  input_aln: "~/input.fa"
  
  window_len: 20
  window_size: !r c(50000)
  min_window_size: 1000

  ic_type: "aic"
---

```{r, include=FALSE}
# install.packages("ape")
# install.packages("forcats")
# install.packages("ggplot2")
# install.packages("log4r")
# install.packages("numbers)
# install.packages("seqinr")
# install.packages("stringr")

# store initial system time
sys_tic <- Sys.time()

# load libraries
source(paste0(params$codedir, "/non_overlapping_window/functions.R"), local=TRUE)

library(data.table)
library(dplyr)
library(doSNOW)

# create outdir
currentdir <- paste0(params$outdir, "/", params$prefix)
if (!dir.exists(currentdir)) {
  dir.create(currentdir, recursive = T)
}

# create log file
fn_log <- paste0(params$outdir, "/", params$prefix, "/", params$prefix, ".log")
log_appender <- log4r::file_appender(fn_log, append = TRUE, layout = log4r::default_log_layout())
fn_logger <- log4r::logger(threshold = "INFO", appenders = log_appender)
if (params$redo) {
  unlink(fn_log)
}

if (!file.exists(fn_log)) {
  write.table("SimNOW", file=fn_log, quote=F, row.names=F, col.names=F)
}

knitr::opts_knit$set(root.dir = currentdir)
```

```{r child = paste0(params$codedir,"/non_overlapping_window/2_run.Rmd"), include=FALSE}
```

```{r child = paste0(params$codedir,"/non_overlapping_window/3_summary.Rmd"), include=FALSE}
```

```{r child = paste0(params$codedir,"/non_overlapping_window/4_rerun.Rmd"), include=FALSE}
```

```{r, include=FALSE}
# store final system time
sys_toc <- Sys.time()

# write the system time in log file
write.table(c("", paste0("Total elapsed time: ", round(as.numeric(difftime(sys_toc, sys_tic, units = "mins")), 3), " mins")),
            file=fn_log, quote=F, row.names=F, col.names=F, append=T)
```