---
title: "NOW for Empirical Dataset"
---

```{r nowsetup-rerun, include=FALSE}
write.table(c("",
              "####################################",
              "####     Rerun NOW Analysis     ####",
              "####################################"),
            file=fn_log, quote=F, row.names=F, col.names=F, append=T)

# create windows dir
window_outdir <- paste0(getwd(), "/windows/")
fn_summary <- paste0(window_outdir, params$prefix, ".sum")
if (!file.exists(fn_summary)){
  log4r::info(fn_logger, paste0("File not found: ", params$prefix, ".sum. Exited."))
  knitr::knit_exit()
}

# check if bootstrap value is valid
if (!is.null(params$bootstrap_type) && params$bootstrap_type != "") {
  bs_type <- tolower(params$bootstrap_type)

  if (bs_type == "ufboot" && params$bootstrap < 1000) {
    log4r::error(fn_logger, "Error: invalid number of bootstrap for UFBoot. Exited.")
    knitr::knit_exit()
  } else if (bs_type == "nonparametric" && params$bootstrap < 100) {
    log4r::error(fn_logger, "Error: invalid number of bootstrap for non-parametric bootstrap. Exited.")
    knitr::knit_exit()
  }
}

# set up variables
min_branch_support <- 80
if (tolower(params$bootstrap_type) == "ufboot") {
  min_branch_support <- 95
}
```

```{r window-size-rerun, include=FALSE}
write.table(c("",
              "---------- Window Alignment --------"),
              file=fn_log, quote=F, row.names=F, col.names=F, append=T)

options(scipen=999)

# extract the best window size
sumfile <- data.table::fread(fn_summary)
min_ic <- sumfile %>%
  slice_min(!!sym(tolower(params$ic_type)))
best_wsize <- as.numeric(min_ic$window_size)*1000

write.table(paste0("Best window size according to ", toupper(params$ic_type), ": ", best_wsize, "bp"),
            file=fn_log, quote=F, row.names=F, col.names=F, append=T)
```

```{r window-aln-rerun, include=FALSE}
options(scipen=999)

# read fasta file
s <- seqinr::read.fasta(params$input_aln, whole.header = T)
empty_columns <- which(s[[1]] == " ")

if (length(empty_columns) != 0) {
  s <- lapply(s, function(x) {x[-empty_columns]})
}

s_ln <- seqinr::getLength(s)[1]
write.table(paste0("Number of sites: ", s_ln, "bp"),
            file=fn_log, quote=F, row.names=F, col.names=F, append=T)

# set working directory
best_wsize_outdir <- paste0(window_outdir, best_wsize, "/full/")
if (!dir.exists(best_wsize_outdir)) {
  dir.create(best_wsize_outdir, recursive = T)
}

# create outdir
temp_outdir <- paste0(best_wsize_outdir, "alignment/")
if (!dir.exists(temp_outdir)) {
  dir.create(temp_outdir, recursive = T)
}

# check if window alignments exist
numw <- floor(s_ln/best_wsize)
if (length(list.files(temp_outdir, pattern='*.fa$', recursive=TRUE)) == numw && !params$redo) {
  log4r::info(fn_logger, paste0("File found: ", best_wsize, "bp window alignment."))

} else {
  # remove all alignments in the folder
  unlink(paste0(temp_outdir,"*.fa"))

  # generate window alignments
  start <- 1
  wi <- ceiling(log(numw) / log(10)) + 1

  for (i in 1:numw) {
    last_idx <- i*best_wsize

    if (i == numw) {
      last_idx <- s_ln
    }

    subfasta <- lapply(s, function(x) x[seq(from = start, to = last_idx)])
    subfasta <- do.call(rbind,subfasta)
    subfasta <- setNames(split(subfasta, seq(nrow(subfasta))), rownames(subfasta))
    
    # window name
    window_name <- paste0("window_",formatC(i,width=wi,format="d",flag="0"))

    window_dir <- paste0(temp_outdir, window_name, "/")
    if (!dir.exists(window_dir)) {
      dir.create(window_dir, recursive=T)
    }

    # save FASTA file
    fn_out <- paste0(window_dir, window_name, ".fa")
    seqinr::write.fasta(sequences=subfasta, names=names(subfasta), file.out=fn_out, nbchar=100)
      
    start <- start + best_wsize
    rm(subfasta, fn_out)
  }

  log4r::info(fn_logger, paste0("File created: ", best_wsize, "bp window alignment."))
}

rm(s)
```

```{r window-tree-rerun, include=FALSE}
write.table(c("",
              "------------ Window Tree -----------"),
              file=fn_log, quote=F, row.names=F, col.names=F, append=T)

options(scipen=999)

# check input alignments
fastadir <- paste0(best_wsize_outdir, "alignment/")
numf <- length(list.files(fastadir, pattern='*.fa$', recursive=TRUE))
numw <- floor(s_ln/best_wsize)
if (numw != numf) {
  log4r::warn(fn_logger, paste0("Warning: ", best_wsize, "bp window has ", numf, "/", numw, " alignments. Exited."))
  knitr::knit_exit()
}

# check input alignments
dirs <- list.dirs(fastadir, full.names = F, recursive = F)
dirs <- dirs[grepl("^window", dirs)]

# create doSNOW cluster
nwcl <- makeCluster(params$thread)
doSNOW::registerDoSNOW(nwcl)

# iterate over windows
foreach (j = dirs) %dopar% {
  fastafile <- paste0(fastadir, j, "/", j, ".fa")

  # check if files exist
  iqtreefile <- paste0(fastafile, ".iqtree")
  treefile <- paste0(fastafile, ".treefile")
  if (all(file.exists(iqtreefile, treefile)) && !params$redo) {
    return(NULL)
  }
  
  # generate window treefile
  iqtree_cmd <- paste(params$iqtree2dir,
                      "-s", fastafile,
                      "-T 1 -cptime 1000000 --quiet -redo")
  
  if (!is.null(params$outgroup) && !params$outgroup == ""){
    iqtree_cmd <- paste(iqtree_cmd, "-o", params$outgroup)
  }
  
  if (params$set_blmin) {
    iqtree_cmd <- paste(iqtree_cmd, "-blmin", 1/i)
  }
  
  if (params$set_model) {
    iqtree_cmd <- paste(iqtree_cmd, "-m", params$dna_model)
  }

  if (!is.null(params$bootstrap_type) && params$bootstrap_type != "") {
    if (tolower(params$bootstrap_type) == "ufboot") {
      iqtree_cmd <- paste(iqtree_cmd, "-bb", params$bootstrap)
    } else if (tolower(params$bootstrap_type) == "nonparametric") {
      iqtree_cmd <- paste(iqtree_cmd, "-b", params$bootstrap)
    }
  }

  system(iqtree_cmd)
}

stopCluster(nwcl)
log4r::info(fn_logger, paste0("File created: ", best_wsize, "bp window treefile."))
```

```{r nowsummary-rerun, include=FALSE}
options(scipen=999)

temp_outdir <- paste0(best_wsize_outdir, "summary/")
if (!dir.exists(temp_outdir)) {
  dir.create(temp_outdir, recursive = T)
}

fn_atsum <- paste0(temp_outdir, params$prefix, ".atsum")
fn_cnsum <- paste0(temp_outdir, params$prefix, ".cnsum")
fn_tops <- paste0(temp_outdir, params$prefix, ".topsum")

# initiate variables
seq_len <- c()
start <- 0

# iterate over windows
for (window in dirs) {
  stop <- start+best_wsize
  length <- best_wsize

  if (start == best_wsize*(numw-1)) {
    stop <- s_ln
    length <- s_ln-start
  }

  # open treefile
  treefile <- paste0(fastadir, window, "/", window, ".fa.treefile")
  if (!file.exists(treefile)) {
    seq_len <- rbind(seq_len, c(window, start+1, stop, length, "", FALSE))

    start <- start+best_wsize
    next
  }

  # read Newick file
  tre <- readLines(treefile)

  tl <- ape::read.tree(text=tre)
  tl$edge.length <- NULL

  # check if there is bootstrap value
  if (!is.null(params$bootstrap_type) && params$bootstrap_type != "") {
    bl <- subset(tl$node.label, tl$node.label != "")

    if (!is.null(bl) && mean(as.numeric(bl)) >= min_branch_support) {
      tl$node.label <- NULL
      seq_len <- rbind(seq_len, c(window, start+1, stop, length, ape::write.tree(tl), TRUE))
    } else {
      seq_len <- rbind(seq_len, c(window, start+1, stop, length, ape::write.tree(tl), FALSE))
    }

    start <- start+best_wsize
    next
  }

  seq_len <- rbind(seq_len, c(window, start+1, stop, length, ape::write.tree(tl), FALSE))
  start <- start+best_wsize
}

seq_len <- data.table::as.data.table(seq_len)
data.table::setnames(seq_len, c("source", "start", "stop", "length", "topology", "high_bs"))
data.table::fwrite(seq_len, file=fn_atsum, quote=F, sep="\t")

# extract top topologies
top_tops <- seq_len %>%
  filter(high_bs) %>%
  group_by(topology) %>%
  filter(topology != "") %>%
  summarise(count = n()) %>%
  arrange(desc(count)) %>%
  mutate(cum.percentage = round(cumsum(count)/sum(count),3))
data.table::fwrite(top_tops, file=fn_tops, quote=F, sep="\t")

# count consecutive/contiguous windows per topology
count_contiguous <- seq_len %>%
  filter(high_bs) %>%
  group_by(topology,
           group_run = data.table::rleid(topology)) %>%
  summarise(count = n()) %>%
  arrange(group_run)
count_contiguous$group_run <- NULL
data.table::fwrite(count_contiguous, file=fn_cnsum, quote=F, sep="\t")  

log4r::info(fn_logger, paste0("File created: ", best_wsize, "bp summary files"))
```