---
title: "Summary of Multiple Non-overlapping Windows Analyses"
params:
  prefix: "sim"
  outdir: "~/simulation"

  initial_wsize: 64000
---
```{r setup, include=FALSE}
library(data.table)
library(dplyr)

dir_summary <- paste0(params$outdir,"/",params$prefix, "/summary/")
if (!dir.exists(dir_summary)) {
  dir.create(dir_summary, recursive=T)
}

fn_best_uqtops <- paste0(dir_summary, "best.uqtops")
```

```{r functions, include=FALSE}
f_count_topology_freq <- function(window_size, list_chr, step, outdir, fn_output) {
  df_output <- data.table::data.table(topology=character(), n=numeric(), cum.percentage=numeric())

  for (c in list_chr) {
    df_uqtops <- data.table::fread(paste0(outdir, "/", c, "/", step, "/", window_size, "/", window_size, ".uqtops"))
    df_output <- rbind(df_output, df_uqtops)
  }

  df_output <- df_output %>%
    select(topology, n) %>%
    group_by(topology) %>%
    summarise_all(sum) %>%
    arrange(desc(n)) %>%
    mutate(cum.percentage=cumsum(n)/sum(n)*100)

  data.table::fwrite(df_output, file=fn_output, quote=F, sep="\t")
}

f_compare_topology_weight <- function(df_input, df_uqtops, colname) {
  if (nrow(df_input) == 0) {
    # remove the last column
    df_uqtops$cum.percentage <- NULL

    # update colnames
    colnames(df_uqtops) <- c("topology", colname)
    return(df_uqtops)
  }

  # iterate over unique topology
  top_dist <- c()
  for (r in 1:nrow(df_input)) {
    idx <- match(df_input$topology[r], df_uqtops$topology)
    if (is.na(idx)) {
      top_dist <- c(top_dist, 0)
      next
    }

    top_dist <- c(top_dist, df_uqtops$n[idx])
  }

  # add new topologies
  new_tops <- subset(df_uqtops$topology, !df_uqtops$topology %in% df_input$topology)
  for (r in new_tops) {
    # new entry
    new_row <- as.data.frame(t(c(r, rep(0, ncol(df_input)-1))))
    df_input <- rbind(df_input, new_row, use.names=FALSE)

    idx <- match(r, df_uqtops$topology)
    top_dist <- c(top_dist, df_uqtops$n[idx])
  }

  # combine the two data.table
  df_input[, (colname) := top_dist]
  return(df_input)
}
```

```{r summary, include=FALSE}
allsims <- list.dirs(paste0(params$outdir,"/",params$prefix), full.names = F, recursive = F)
chrs <- allsims[grep("^chr", allsims)]
chrs <- stringr::str_sort(chrs, numeric=TRUE)

# extract window sizes
max_wsize <- params$initial_wsize
wsizes <- max_wsize
while (max_wsize %% 2 == 0) {
  wsizes <- c(wsizes, max_wsize / 2)
  max_wsize <- max_wsize / 2
}
wsizes <- sort(wsizes, decreasing=T)

for (i in 1:length(wsizes)) {
  fn_output <- paste0(dir_summary, wsizes[i], ".uqtops")

  if (i == 1) {
      f_count_topology_freq(wsizes[i], chrs, i, paste0(params$outdir,"/",params$prefix), fn_output)
  } else {
      f_count_topology_freq(wsizes[i], chrs, i-1, paste0(params$outdir,"/",params$prefix), fn_output)
  }
}

# summary for best window size
df_best_wsize <- data.table::data.table()

# iterate over chromosomes
for (c in chrs) {
  # open summary table
  fn_summary <- paste0(params$outdir, "/", params$prefix, "/", c, "/", c, ".sumtable")
  if (!file.exists(fn_summary)) {
    cat(paste("Error:", fn_summary, "is not found. Exited"))
    knitr::knit_exit()
  }

  # read summary table
  df_summary <- data.table::fread(fn_summary)

  # choose the best window size
  i <- 1
  for (j in nrow(df_summary):1) {
    if (df_summary$diff_aic[j] < 0) {
      i <- j
      break
    }
  }

  # read unique topology file
  best_wsize <- df_summary$s_wsize[i]
  fn_uqtops <- paste0(params$outdir, "/", params$prefix, "/", c, "/", df_summary$step[i], "/", best_wsize, "/", best_wsize, ".uqtops")
  if (!file.exists(fn_uqtops)) {
    cat(paste("Error:", fn_uqtops, "is not found. Exited"))
    knitr::knit_exit()
  }

  # read summary table
  df_uqtops <- data.table::fread(fn_uqtops)

  df_best_wsize <- f_compare_topology_weight(df_best_wsize, df_uqtops, paste0(c, ".", best_wsize))
}

# add the total topology count
df_colnames <- colnames(df_best_wsize)[2:ncol(df_best_wsize)]

# convert columns in numeric
df_best_wsize[, (df_colnames) := lapply(.SD, as.numeric), .SDcols = df_colnames]

df_best_wsize <- df_best_wsize %>%
  mutate(n = rowSums(select(., all_of(df_colnames)))) %>%
  arrange(desc(n)) %>%
  mutate(cum.percentage=round(cumsum(n)/sum(n)*100,3))

# write the output data.table
data.table::fwrite(df_best_wsize, file=fn_best_uqtops, quote=FALSE, sep="\t")
```