---
title: "MAST Analysis on Simulated Dataset"
params:
  # general
  rmddir: ""
  prefix: ""
  outdir: ""
  thread: 5
  redo: FALSE
  
  # software
  iqtree2dir: ""
  
  # masthmm
  ic_type: "AIC"
  
  mast_analysis: "HiMAST"
  mast_model: ""
  percent_tops: 0.95
  max_tops: 10
---

```{r, include=FALSE}
# install.packages("ape")
# install.packages("ggplot2")
# install.packages("log4r")
# install.packages("stringr")

# store initial system time
sys_tic <- Sys.time()

# load libraries
library(data.table)
library(dplyr)
library(doSNOW)

# set up working directory
currentdir <- paste0(params$outdir, "/", params$prefix)
if (!dir.exists(currentdir)) {
  dir.create(currentdir, recursive = T)
}

# update variables as folder name
fn_mast_model <- gsub('^\\_+|\\_+$', '', tolower(gsub("[[:punct:]]", "_", params$mast_model)))
mast_analysis <- tolower(params$mast_analysis)

# set up logger
logdir <- paste0(currentdir, "/", mast_analysis, "/", fn_mast_model, "/")
if (!dir.exists(logdir)) {
  dir.create(logdir, recursive = T)
}

fn_log <- paste0(logdir, params$prefix, ".mh.log")
log_appender <- log4r::file_appender(fn_log, append = TRUE, layout = log4r::default_log_layout())
fn_logger <- log4r::logger(threshold = "INFO", appenders = log_appender)
if (params$redo) {
  unlink(fn_log)
}

if (!file.exists(fn_log)) {
  write.table("SimNOW", file=fn_log, quote=F, row.names=F, col.names=F)
}

# select analysis type
MAST <- "mast"
HiMAST <- "himast"
if (!mast_analysis %in% c(MAST, HiMAST)) {
  log4r::error(fn_logger, "Error: invalid type of analysis. Exited.")
  knitr::knit_exit()
}

# switch to working directory
knitr::opts_knit$set(root.dir = currentdir)
```

```{r child = paste(params$rmddir,"/mh_run.Rmd",sep=""), include=FALSE}
```

```{r child = paste(params$rmddir,"/mh_summary.Rmd",sep=""), include=FALSE}
```

```{r, include=FALSE}
# store final system time
sys_toc <- Sys.time()

# write the system time in log file
write.table(c("", paste0("Total elapsed time: ", round(as.numeric(difftime(sys_toc, sys_tic, units = "mins")), 3), " mins")),
            file=fn_log, quote=F, row.names=F, col.names=F, append=T)
```
