---
title: "MASTHMM Analysis"
---

### setup
```{r vars, include=FALSE}
mast_outdir <- paste(getwd(), "/masthmm/", sep="")
if (!file.exists(mast_outdir)) {
  dir.create(mast_outdir, recursive = T)
}

window_outdir <- paste(getwd(), "/windows/", sep="")
window_sizes <- list.dirs(window_outdir, full.names = F, recursive = F)

fn_alisim <- paste(getwd(), "/simulation/", params$prefix, ".fa", sep="")
fn_mstops <- paste(getwd(), "/simulation/", params$prefix, ".mstops", sep="")

fn_topset <- paste(mast_outdir, params$prefix, ".topset", sep="")

mast_model <- paste("'", params$mast_model, "'", sep="")
```

### analysis
```{r prehmm}
uq_tops <- data.frame()
if (file.exists(fn_topset) && params$redo == FALSE){
  uq_tops <- read.table(fn_topset)
  colnames(uq_tops) <- uq_tops[1,]
  uq_tops <- uq_tops[-1,]
} else {
  list_tops <- c("wsize","topologies")

  for (i in window_sizes) {
    # extract top % topologies
    fn_tops <- paste(window_outdir, i, "/summary/", params$prefix, ".topsum", sep="")
    topsum <- read.table(fn_tops)
    colnames(topsum) <- topsum[1,]
    topsum <- topsum[-1,]
    
    tpercent <- 0
    tmast <- c()
    for (j in 1:nrow(topsum)) {
      tmast <- c(tmast, topsum$newick[j])
      tpercent <- topsum$cum.percentage[j]
      
      if (tpercent >= params$mast_tops) {
        break
      }
    }
    
    list_tops <- rbind(list_tops, c(i,paste(sort(tmast),collapse="&")))
  }
  
  list_tops <- as.data.frame(list_tops)
  colnames(list_tops) <- list_tops[1,]
  list_tops <- list_tops[-1,]
  
  uq_tops <- list_tops %>%
    group_by(topologies) %>% 
    summarise(wsizes = paste(wsize, collapse = "_"))
  
  write.table(uq_tops, file=fn_topset, quote=F, row.names=F, col.names=T)
}
```

```{r masthmm}
# create folder for each set topology
for (k in 1:nrow(uq_tops)) {
  setfn <- paste(mast_outdir,uq_tops$wsizes[k],"/",sep="")
  if (!file.exists(setfn)) {
    dir.create(setfn, recursive = T)
  }
  
  topls <- strsplit(uq_tops$topologies[k],split = "&")[[1]]
  fn_mast_tops <- paste(setfn, params$prefix, ".mast.tops", sep="")
  if (!file.exists(fn_mast_tops)) {
    write.table(topls, file = fn_mast_tops, quote = F, row.names = F, col.names = F)
  }
  
  if (length(topls) <= 1) {
    print(paste(uq_tops$wsizes[k], "bp window has only one or less tree. Moving on..."))
    next
  }
  
  # create folder based on the MAST model
  outdir <- paste(setfn, gsub('^\\_+|\\_+$','', tolower(gsub("[[:punct:]]","_",mast_model))), "/", sep="")
  if (!file.exists(outdir)) {
    dir.create(outdir, recursive = T)
  }
  
  prefix <- paste(outdir, params$prefix, sep="")
  if (file.exists(paste(prefix,".hmm",sep="")) && params$redo == FALSE) {
    print(paste(uq_tops$wsizes[k], "bp window MASTHMM file already exists. Moving on..."))
    next
  }
  
  # run MAST and HMM
  mast_cl <- paste(params$iqtree2dir,"-s",fn_alisim,"-m",mast_model,"-blmin 0.0001 -te",fn_mast_tops,"-pre",prefix,"-hmm -wslm -wspm -alninfo")
  system(mast_cl)
}
```

```{r posthmm}
msfile <- read.table(fn_mstops)
colnames(msfile) <- msfile[1,]
msfile <- msfile[-1,]

for (i in uq_tops$wsizes) {
  temp_outdir <- paste(mast_outdir,i,"/",sep="")
  fn_mast_tops <- paste(temp_outdir, params$prefix, ".mast.tops", sep="")
  outdir <- paste(temp_outdir, gsub('^\\_+|\\_+$','', tolower(gsub("[[:punct:]]","_",mast_model))), "/", sep="")
  
  fn_hmm <- paste(outdir, params$prefix, ".hmm", sep="")
  if (!file.exists(fn_hmm)) {
    print("HMM file is not found. Moving on...")
    next
  }
 
  fn_hmmsum <- paste(outdir, params$prefix, ".hmmsum", sep="")
  fn_hmmfig <- paste(outdir, params$prefix, ".hmmsum.tiff", sep="")
  if (all(file.exists(fn_hmmsum, fn_hmmfig)) && params$redo == FALSE) {
    print(paste(i, "bp window MASTHMM summary file already exists. Moving on...", sep=""))
    next
  }
  
  # read input files
  tmfile <- readLines(fn_mast_tops)
  hmmfile <- readLines(fn_hmm)
  hmmtrees <- subset(hmmfile, grepl("^\\[", hmmfile))
  
  trees <- data.frame(do.call('rbind', strsplit(as.character(hmmtrees),'\\[|,|\\]')))
  trees[,1] <- NULL
  colnames(trees) <- c("start","stop","tree")
  
  # extracting essential columns
  dat <- apply(trees, 1,
               function(x) data.table(bp = x["start"]:x["stop"], tree = x["tree"])) %>%
    rbindlist()
  
  # create empty dataframe
  empty_matrix <- as.data.frame(matrix(rep(0, length(tmfile)+1), nrow=length(tmfile), ncol=length(tmfile)+1))
  names(empty_matrix) <- c(tmfile,"NT")
  
  output <- data.frame(topology = tmfile)
  output <- cbind(output, empty_matrix)
  
  # annotating
  for (i in 1:nrow(msfile)){
    sites <- dat[msfile$start[i]:msfile$stop[i],]
    topology_idx <- which(output$topology==msfile$topology[i])
    
    sites_sum <- sites %>%
      group_by(tree) %>%
      summarise(n=n())
    
    for (j in 1:nrow(sites_sum)) {
      window_idx <- which(colnames(output)==tmfile[as.numeric(sites_sum$tree[j])])
      
      if (length(window_idx) == 0) {
        output$NT[topology_idx] = output$NT[topology_idx] + sites_sum$n[j]
      } else {
        output[topology_idx,window_idx] = output[topology_idx,window_idx] + sites_sum$n[j]
      }
    }
  }
  
  write.table(output, file=fn_hmmsum, quote = F, row.names = F)
  
  # visualization
  sub_output <- data.frame()
  
  for (i in 1:nrow(output)) {
    for (j in 2:ncol(output)) {
      sub_output <- rbind(sub_output, c(output$topology[i],colnames(output[j]),output[i,j]))
    }
  }
  colnames(sub_output) <- c("topology","sites","frequency")
  sub_output$sites <- factor(sub_output$sites,levels = unique(sub_output$sites),ordered = T)
  
  tiff(filename=fn_hmmfig, units="px", width=2880, height=1800)
  print(ggplot(sub_output, aes(fill=sites, y=as.numeric(frequency), x=topology)) + 
          geom_bar(position="dodge", stat="identity") +
          aes(x = fct_inorder(topology)) +
          ggtitle("Distribution of Sites from MAST+HMM in Simulated Dataset") + 
          xlab("True topology from simulated data") +
          ylab("Number of sites from MAST+HMM") +
          theme(
            plot.title = element_text(hjust = 0.5, size = 50),
            axis.title.x=element_text(size = 40, margin = margin(t=20, r=0, b=0, l=0)),
            axis.title.y=element_text(size = 40, margin = margin(t=0, r=20, b=0, l=0)),
            axis.text.y=element_text(size=30),
            axis.text.x=element_text(size=30),
            legend.title=element_blank(),
            legend.text=element_text(size=30),
            legend.key.size=unit(2,"cm")
          ))
  dev.off()
}
```