---
title: "Summary of MAST Analysis vs Truth"
---

```{r sumsetup, include=FALSE}
write.table(c("",
              "####################################",
              "####        MAST vs Truth       ####",
              "####################################"),
            file=fn_log, quote=F, row.names=F, col.names=F, append=T)

# extract MAST run directories
mast_outdir <- paste0(getwd(), "/", mast_analysis, "/", fn_mast_model, "/")
mast_model <- paste0("'", params$mast_model, "'")
  
mast_nw_outdir <- paste0(mast_outdir, "windows/")
mast_ms_outdir <- paste0(mast_outdir, "ms/")

# set up output directory
mast_sumdir <- paste0(mast_outdir, "summary/")
if (!dir.exists(mast_sumdir)) {
  dir.create(mast_sumdir, recursive = T)
}

# input / output files
fn_mstops <- paste0(getwd(), "/simulation/", params$prefix, ".mstops")
fn_mast_tops <- paste0(getwd(), "/", mast_analysis, "/", params$prefix, ".mast.tops")
fn_iqtree <- paste0(mast_outdir, params$prefix, ".iqtree")
fn_hmm <- paste0(mast_outdir, params$prefix, ".hmm")

fn_masttw <- paste0(mast_sumdir, params$prefix, ".masttw")
fn_hmmsum <- paste0(mast_sumdir, params$prefix, ".hmmsum")
fn_summary <- paste0(mast_sumdir, params$prefix, ".mh.sum")
fn_hmmsum_nw <- paste0(mast_sumdir, params$prefix, ".hmmnow")
fn_hmmsum_ms <- paste0(mast_sumdir, params$prefix, ".hmmms")
```

```{r summast, include=FALSE}
options(scipen=999)
if (!file.exists(fn_iqtree)) {
  errmsg <- "Error: IQ-Tree 2 file is not found. Exited."
  stop(errmsg)
}

# read ms topologies
msfile <- data.table::fread(fn_mstops)
uq_mstrees <- unique(msfile$topology)
uq_mstrees_ln <- length(uq_mstrees)

# read MAST input topologies
uq_tmtrees <- readLines(fn_mast_tops)

# match MAST topology with ms topology
for (j in uq_tmtrees) {
  for (k in uq_mstrees) {
    if (ape::all.equal.phylo(ape::unroot(ape::read.tree(text = k)), ape::read.tree(text = j))) {
      uq_tmtrees <- gsub(j, k, uq_tmtrees, fixed = TRUE)
      break
    }
  }
}

# ms topology weights
ms_len <- sum(as.numeric(msfile$length))
ms_tw <- msfile %>%
  select(topology, length) %>%
  group_by(topology) %>%
  summarise(ms=sum(length)/ms_len)

# MAST topology weights
mast_tw <- gsub("^.*: ", "", system(paste("grep '^Tree weights'", fn_iqtree), intern = T))
ls_mast_tw <- strsplit(mast_tw, ", ")[[1]]

# extract the weights for each topology
output <- NULL

if (mast_analysis == MAST) {
  output <- data.table::data.table(topology = character(), ms = numeric(), mast = numeric())
  
  for (j in 1:nrow(ms_tw)) {
    top_idx <- match(ms_tw$topology[j], uq_tmtrees)
    output <- rbindlist(list(output, list(ms_tw$topology[j], ms_tw$ms[j], round(as.numeric(ls_mast_tw[top_idx]), 4))))
  }
  
} else if (mast_analysis == HiMAST) {
  if (!file.exists(fn_hmm)) {
    errmsg <- "Error: HMM file is not found. Exited."
    stop(errmsg)
  }
  
  hmm_tw <- gsub("^.*: ", "", system(paste("grep '^Ratio of sites for each category'", fn_hmm), intern = T))
  ls_hmm_tw <- strsplit(hmm_tw, " ")[[1]]

  output <- data.table::data.table(topology = character(), ms = numeric(), mast = numeric(), hmm = numeric())
  
  for (j in 1:nrow(ms_tw)) {
    top_idx <- match(ms_tw$topology[j], uq_tmtrees)
    
    if (is.na(top_idx)) {
      output <- rbindlist(list(output, list(ms_tw$topology[j],
                                          ms_tw$ms[j],
                                          "NA",
                                          "NA")))
    } else {
      output <- rbindlist(list(output, list(ms_tw$topology[j],
                                          ms_tw$ms[j],
                                          round(as.numeric(ls_mast_tw[top_idx]), 4),
                                          round(as.numeric(ls_hmm_tw[top_idx]), 4))))
    }
  }
}

data.table::fwrite(output, fn_masttw, quote = F, sep = "\t")
log4r::info(fn_logger, paste("File created:", toupper(mast_analysis), "topology weights comparison."))

# extract per-site topology from HMM
if (mast_analysis == HiMAST) {
  # extract HMM per-site topology
  hmmtrees <- system(paste("grep '^\\['", fn_hmm), intern=TRUE)
  trees <- data.table::data.table(do.call('rbind', strsplit(as.character(hmmtrees),'\\[|,|\\]')))
  trees[,1] <- NULL
  
  colnames(trees) <- c("start","stop","tree")
  trees$start <- as.numeric(trees$start)
  trees$stop <- as.numeric(trees$stop)
  
  # create empty data.table
  output <- data.table::data.table(c(uq_mstrees, "NT"), matrix(0, nrow=uq_mstrees_ln+1, ncol=uq_mstrees_ln))
  data.table::setnames(output, c("topology", uq_mstrees))
  
  # iterate through ms topology file
  for (k in 1:nrow(msfile)){
    # extract the hmm topology based on ms topology switching
    start_idx <- tail(which(trees$start <= msfile$start[k]), 1)
    stop_idx <- head(which(trees$stop >= msfile$stop[k]), 1)
    
    # update lengths
    sites <- trees[start_idx:stop_idx,]
    sites$start[1] <- msfile$start[k]
    sites$length[1] <- sites$stop[1] - sites$start[1] + 1
    
    last_idx <- nrow(sites)
    sites$stop[last_idx] <- msfile$stop[k]
    sites$length[last_idx] <- sites$stop[last_idx] - sites$start[last_idx] + 1
    
    topology_idx <- match(msfile$topology[k], colnames(output))
    
    # add number of HMM sites for the respective ms topology
    for (j in 1:nrow(sites)) {
      window_idx <- match(uq_tmtrees[as.numeric(sites$tree[j])], output$topology)
      
      if (is.na(window_idx)) {
        tempval <- as.numeric(output[uq_mstrees_ln+1, ..topology_idx] + sites$length[j])
        output[uq_mstrees_ln+1, eval(msfile$topology[k]) := tempval]
      } else {
        tempval <- as.numeric(output[window_idx, ..topology_idx] + sites$length[j])
        output[window_idx, eval(msfile$topology[k]) := tempval]
      }
    }
    
    rm(sites)
  }
  
  # write the data.table into file
  data.table::fwrite(output, file=fn_hmmsum, quote=F, sep="\t")
  log4r::info(fn_logger, paste("File created:", toupper(mast_analysis), "per-site topology comparison."))
  
  rm(hmmtrees, trees, output)
}
```

```{r sumtable, include=FALSE}
if (mast_analysis == HiMAST) {
  # read HMM summary file
  hmmsum <- data.table::fread(fn_hmmsum)
  hmmsum <- as.matrix(hmmsum[,-1])
    
  # calculate the accuracy 
  acc <- sum(as.numeric(diag(hmmsum))) / sum(as.numeric(hmmsum)) * 100
  acc <- round(acc, 3)
  
  # extract information of interest
  aic <- gsub("^.* ", "", system(paste("grep '^Akaike information criterion'",fn_iqtree), intern = T))
  aicc <- gsub("^.* ", "", system(paste("grep '^Corrected Akaike information criterion'",fn_iqtree), intern = T))
  bic <- gsub("^.* ", "", system(paste("grep '^Bayesian information criterion'",fn_iqtree), intern = T))
  hmm <- gsub("^.* :", "", system(paste("grep '^BEST HMM SCORE'",fn_hmm), intern = T))
  
  output <- data.table::data.table()
  output[, c("accuracy","aic","aicc","bic","hmm") := list(acc,aic,aicc,bic,hmm)]
  data.table::fwrite(output, file=fn_summary, quote=F, sep="\t")
  
  log4r::info(fn_logger, paste0("File created/modified: summary table of ", toupper(mast_analysis), "."))
  rm(hmmsum, output)
}
```

```{r sumhmmnow, include=FALSE}
if (mast_analysis == HiMAST) {
  # list all windows
  fn_windows <- list.dirs(mast_nw_outdir, full.names = FALSE, recursive = FALSE)
  
  # create new empty data.table
  trees <- data.table::data.table(start = numeric(), stop = numeric(), length = numeric(), tree = character())
  last_pos <- 0
  
  # iterate through each window
  for (w in stringr::str_sort(fn_windows, numeric=TRUE)) {
    temp_hmm <- paste0(mast_nw_outdir, w, "/", w, ".hmm")
    
    hmmtrees <- system(paste("grep '^\\['", temp_hmm), intern=TRUE)
    temp_trees <- data.table::data.table(do.call('rbind', strsplit(as.character(hmmtrees),'\\[|,|\\]')))
    temp_trees[,1] <- NULL
    
    colnames(temp_trees) <- c("start","stop","tree")
    temp_trees$start <- as.numeric(temp_trees$start) + last_pos
    temp_trees$stop <- as.numeric(temp_trees$stop) + last_pos
    temp_trees$length <- temp_trees$stop - temp_trees$start + 1
    
    trees <- rbind(trees, temp_trees)
    last_pos <- temp_trees$stop[nrow(temp_trees)]
  }
  
  # create empty data.table
  output <- data.table::data.table(c(uq_mstrees, "NT"), matrix(0, nrow=uq_mstrees_ln+1, ncol=uq_mstrees_ln))
  data.table::setnames(output, c("topology", uq_mstrees))
  
  # iterate through ms topology file
  for (k in 1:nrow(msfile)){
    # extract the hmm topology based on ms topology switching
    start_idx <- tail(which(trees$start <= msfile$start[k]), 1)
    stop_idx <- head(which(trees$stop >= msfile$stop[k]), 1)
    
    # update lengths
    sites <- trees[start_idx:stop_idx,]
    sites$start[1] <- msfile$start[k]
    sites$length[1] <- sites$stop[1] - sites$start[1] + 1
    
    last_idx <- nrow(sites)
    sites$stop[last_idx] <- msfile$stop[k]
    sites$length[last_idx] <- sites$stop[last_idx] - sites$start[last_idx] + 1
    
    topology_idx <- match(msfile$topology[k], colnames(output))
    
    # add number of HMM sites for the respective ms topology
    for (j in 1:nrow(sites)) {
      window_idx <- match(uq_tmtrees[as.numeric(sites$tree[j])], output$topology)
      
      if (is.na(window_idx)) {
        tempval <- as.numeric(output[uq_mstrees_ln+1, ..topology_idx] + sites$length[j])
        output[uq_mstrees_ln+1, eval(msfile$topology[k]) := tempval]
      } else {
        tempval <- as.numeric(output[window_idx, ..topology_idx] + sites$length[j])
        output[window_idx, eval(msfile$topology[k]) := tempval]
      }
    }
    
    rm(sites)
  }
  
  # write the data.table into file
  data.table::fwrite(output, file=fn_hmmsum_nw, quote=F, sep="\t")
  log4r::info(fn_logger, paste("File created:", toupper(mast_analysis), "per-site, window-based topology comparison."))
}
```

```{r sumhmmms, include=FALSE}
if (mast_analysis == HiMAST) {
  fn_hmmms <- paste0(mast_ms_outdir, params$prefix, ".hmm")
  fn_uqtops <- paste0(params$outdir, "/", params$prefix, "/simulation/", params$prefix, ".uqtops")
  
  # extract HMM per-site topology
  hmmtrees <- system(paste("grep '^\\['", fn_hmmms), intern=TRUE)
  trees <- data.table::data.table(do.call('rbind', strsplit(as.character(hmmtrees),'\\[|,|\\]')))
  trees[,1] <- NULL
  
  colnames(trees) <- c("start","stop","tree")
  trees$start <- as.numeric(trees$start)
  trees$stop <- as.numeric(trees$stop)
  
  # read MAST input topologies
  uq_tmtrees <- readLines(fn_uqtops)
  
  # create empty data.table
  output <- data.table::data.table(c(uq_mstrees, "NT"), matrix(0, nrow=uq_mstrees_ln+1, ncol=uq_mstrees_ln))
  data.table::setnames(output, c("topology", uq_mstrees))
  
  # iterate through ms topology file
  for (k in 1:nrow(msfile)){
    # extract the hmm topology based on ms topology switching
    start_idx <- tail(which(trees$start <= msfile$start[k]), 1)
    stop_idx <- head(which(trees$stop >= msfile$stop[k]), 1)
    
    # update lengths
    sites <- trees[start_idx:stop_idx,]
    sites$start[1] <- msfile$start[k]
    sites$length[1] <- sites$stop[1] - sites$start[1] + 1
    
    last_idx <- nrow(sites)
    sites$stop[last_idx] <- msfile$stop[k]
    sites$length[last_idx] <- sites$stop[last_idx] - sites$start[last_idx] + 1
    
    topology_idx <- match(msfile$topology[k], colnames(output))
    
    # add number of HMM sites for the respective ms topology
    for (j in 1:nrow(sites)) {
      window_idx <- match(uq_tmtrees[as.numeric(sites$tree[j])], output$topology)
      
      if (is.na(window_idx)) {
        tempval <- as.numeric(output[uq_mstrees_ln+1, ..topology_idx] + sites$length[j])
        output[uq_mstrees_ln+1, eval(msfile$topology[k]) := tempval]
      } else {
        tempval <- as.numeric(output[window_idx, ..topology_idx] + sites$length[j])
        output[window_idx, eval(msfile$topology[k]) := tempval]
      }
    }
    
    rm(sites)
  }
  
  # write the data.table into file
  data.table::fwrite(output, file=fn_hmmsum_ms, quote=F, sep="\t")
  log4r::info(fn_logger, paste("File created:", toupper(mast_analysis), "per-site, ms-based topology comparison."))
}
```