---
title: "Non-overlapping Windows Analysis"
params:
  # general
  rmddir: "~/Documents/SimNOW/rmd"
  prefix: "db"
  outdir: "~/Documents/simulation/debug"
  thread: 1
  redo: TRUE
  
  # ms
  msdir: "~/Documents/msdir/ms"
  ms_params: ""
  ms_r: 
  ms_l: 1000000
  
  # AliSim
  iqtree2dir: "~/Documents/iqtree-2.2.2.2-MacOSX/bin/iqtree2"
  alisim_model: "JC"
  alisim_scale: 0.001
  outgroup: ""
  
  # non-overlapping window analysis
  window_size: !r c()
---

```{r, include=FALSE}
# install.packages("ape")
# install.packages("forcats")
# install.packages("ggplot2")
# install.packages("log4r")
# install.packages("seqinr")

# store initial system time
sys_tic <- Sys.time()

# load libraries
library(data.table)
library(dplyr)
library(doSNOW)
library(hash)

# create outdir
currentdir <- paste0(params$outdir, "/", params$prefix)
if (!dir.exists(currentdir)) {
  dir.create(currentdir, recursive = T)
}

# create log file
fn_log <- paste0(params$outdir, "/", params$prefix, "/", params$prefix, ".log")
log_appender <- log4r::file_appender(fn_log, append = TRUE, layout = log4r::default_log_layout())
fn_logger <- log4r::logger(threshold = "INFO", appenders = log_appender)
if (params$redo) {
  unlink(fn_log)
}

if (!file.exists(fn_log)) {
  write.table("SimNOW", file=fn_log, quote=F, row.names=F, col.names=F)
}

knitr::opts_knit$set(root.dir = currentdir)
```

```{r child = paste(params$rmddir,"/nw_simulation.Rmd",sep=""), include=FALSE}
```

```{r child = paste(params$rmddir,"/nw_run.Rmd",sep=""), include=FALSE}
```

```{r child = paste(params$rmddir,"/nw_summary.Rmd",sep=""), include=FALSE}
```

```{r, include=FALSE}
# store final system time
sys_toc <- Sys.time()

# write the system time in log file
write.table(c("", paste0("Total elapsed time: ", round(as.numeric(sys_toc - sys_tic) / 60, 3), " mins")),
            file=fn_log, quote=F, row.names=F, col.names=F, append=T)
```