---
title: "Sequence Simulation"
params:
  # general
  prefix: "sim"
  outdir: "~/simulation"
  redo: TRUE
  
  # ms
  msdir: "~/msdir/ms"
  ms_params: ""
  ms_r: 0
  ms_l: 1000000
  
  # AliSim
  iqtree2dir: "~/iqtree-2.2.2.4-MacOSX/bin/iqtree2"
  alisim_model: "JC"
  alisim_scale: 0.001
---

```{r, include=FALSE}
# store initial system time
sys_tic <- Sys.time()

# load libraries
library(data.table)
library(dplyr)

# create outdir
currentdir <- paste0(params$outdir, "/", params$prefix)
if (!dir.exists(currentdir)) {
  dir.create(currentdir, recursive = T)
}

# create log file
fn_log <- paste0(params$outdir, "/", params$prefix, "/", params$prefix, ".log")
log_appender <- log4r::file_appender(fn_log, append = TRUE, layout = log4r::default_log_layout())
fn_logger <- log4r::logger(threshold = "INFO", appenders = log_appender)
if (params$redo) {
  unlink(fn_log)
  write.table("SimNOW", file=fn_log, quote=F, row.names=F, col.names=F)
}

knitr::opts_knit$set(root.dir = currentdir)
```

```{r simsetup, include=FALSE}
write.table(c("",
              "####################################",
              "####     Sequence Simulation    ####",
              "####################################"),
            file=fn_log, quote=F, row.names=F, col.names=F, append=T)

# create simulation dir
simulation_outdir <- paste0(getwd(), "/simulation")
if (!dir.exists(simulation_outdir)) {
  dir.create(simulation_outdir, recursive = T)
}

# input/output files
fn_msfile <- paste0(simulation_outdir, "/", params$prefix, ".ms")
fn_mstrees <- paste0(simulation_outdir, "/", params$prefix, ".mstrees")
fn_mttrees <- paste0(simulation_outdir, "/", params$prefix, ".multitree")
fn_mstops <- paste0(simulation_outdir, "/", params$prefix, ".mstops")
fn_uqtops <- paste0(simulation_outdir, "/", params$prefix, ".uqtops")

fn_nexus <- paste0(simulation_outdir, "/", params$prefix, ".nex")
fn_alisim <- paste0(simulation_outdir, "/", params$prefix)
fn_alisim_fa <- paste0(simulation_outdir, "/", params$prefix, ".fa")
```

```{r ms, include=FALSE}
write.table(c("",
              "---------------- ms ----------------"),
              file=fn_log, quote=F, row.names=F, col.names=F, append=T)

options(scipen=999)
randseed <- paste(sample(10000:99999,3), collapse=" ")
ms_command <- paste(params$ms_params, "-r", params$ms_r, params$ms_l, "-seeds", randseed)

# generate msfile
if (file.exists(fn_msfile) && !params$redo) {
  log4r::info(fn_logger, paste0("File found: ", params$prefix, "ms."))
} else {
  system(paste(params$msdir,ms_command,">",fn_msfile))
  log4r::info(fn_logger, paste0("File created: ", params$prefix, ".ms."))
}
```

```{r postms, include=FALSE}
options(scipen=999)

if (all(file.exists(fn_mstrees, fn_mttrees, fn_mstops, fn_uqtops)) && !params$redo) {
  log4r::info(fn_logger, "File found: ms summary files.")
  
} else {
  ms <- data.table::fread(fn_msfile, col.names="cmd", sep="")
  
  # extract ms trees
  mstrees <- ms[grepl("^\\[", cmd)]
  if (nrow(mstrees) == 0) {
    mstrees <- ms[grepl("^\\(.+\\);$", cmd)]
    mstrees[1, cmd := paste0("[", params$ms_l, "]", mstrees[1, cmd])]
  }
  
  # convert ms trees into data.table
  mstrees[, c("empty","length","tree") := data.table::tstrsplit(cmd, '\\[|\\]', fixed = FALSE)]
  mstrees[, c("cmd", "empty") := NULL]
  mstrees$length <- as.numeric(mstrees$length)
  
  # combine contiguous trees together  
  summary <- mstrees %>%
    group_by(tree, group_run = data.table::rleid(tree)) %>%
    summarise_all(sum) %>%
    arrange(group_run)
  summary$group_run <- NULL
  summary <- data.table::as.data.table(summary)
    
  # store first tree without branch lengths  
  n <- nrow(summary)
  start <- 1
  stop <- summary$length[1]
  
  first_tree <- ape::read.tree(text=summary$tree[1])
  first_tree$edge.length <- NULL
  topology <- ape::write.tree(first_tree)
    
  # store subsequent trees without branch lengths
  if (n > 1) {
    for (i in 2:n){
      start <- c(start,stop[length(stop)]+1)
      stop <- c(stop,stop[length(stop)]+summary$length[i])

      temp_tree <- ape::read.tree(text=summary$tree[i])
      temp_tree$edge.length <- NULL
      topology <- c(topology, ape::write.tree(temp_tree))
    }
  }
  summary[, c("start", "stop", "topology") := list(start, stop, topology)]
  
  # output files
  data.table::fwrite(summary, file=fn_mstrees, sep="\t", quote=F)
  write.table(summary$tree, file=fn_mttrees, sep="\t", quote=F, row.names=F, col.names=F)
  log4r::info(fn_logger, paste0(n, " tree partition(s) found. File created: ",
                               params$prefix, ".mstrees and ", params$prefix, ".multitree"))
    
  # match the naming convention of topologies
  uq_tops <- unique(summary$topology)
  ls_unroot <- NULL
  ls_uqtops <- NULL
  
  for (i in uq_tops) {
    is_equal <- FALSE
    
    for (j in ls_unroot) {
      if (ape::all.equal.phylo(ape::unroot(ape::read.tree(text = i)), ape::unroot(ape::read.tree(text = j)))) {
        is_equal <- TRUE
        ls_uqtops[[i]] <- j
        break
      }
    }
    
    if (!is_equal) {
      ls_unroot <- c(ls_unroot, i)
      ls_uqtops[[i]] <- i
    }
  }
  
  lookup <- match(summary$topology, names(ls_uqtops))
  summary[, "utopology" := as.character(ls_uqtops[lookup])]
  
  # combine contiguous topologies together 
  t_summary <- summary %>%
    group_by(utopology, group_run = data.table::rleid(utopology)) %>%
    summarise(length=sum(length)) %>%
    arrange(group_run)
  t_summary$group_run <- NULL
  t_summary <- as.data.table(t_summary)
  data.table::setnames(t_summary, c("topology", "length"))
   
  # store the boundary of each topology 
  nt <- nrow(t_summary)
  start <- 1
  stop <- t_summary$length[1]

  if (nt > 1) {
    for (i in 2:nt){
      start <- c(start,stop[length(stop)]+1)
      stop <- c(stop,stop[length(stop)]+t_summary$length[i])
    }
  }    
  t_summary[, c("start", "stop") := list(start, stop)]
  
  # output files
  data.table::fwrite(t_summary, file=fn_mstops, sep="\t", quote=F)
  write.table(unique(t_summary$topology), file=fn_uqtops, sep="\t", quote=F, row.names=F, col.names=F)
  log4r::info(fn_logger, paste0(nt, " topology partition(s) found. File created: ", 
                               params$prefix, ".mstops and ", params$prefix, ".uqtops"))
  
  rm(ms, mstrees, summary, t_summary, start, stop, topology)
}
```

```{r prealisim, include=FALSE}
write.table(c("",
              "-------------- AliSim --------------"),
              file=fn_log, quote=F, row.names=F, col.names=F, append=T)

if (file.exists(fn_nexus) && !params$redo) {
  log4r::info(fn_logger, paste0("File found: ", params$prefix, ".nex."))
  
} else {
  mstrees <- data.table::fread(fn_mstrees)
  
  # generate nexus file
  res <- lapply(1:nrow(mstrees), function(i) {
    paste0("    charset gene_",i," = DNA, ",mstrees$start[i],"-",mstrees$stop[i],";")
  })
  
  nexus_lines <- c("#nexus", "begin sets;", unlist(res), "end;")
  
  fileConn <- file(fn_nexus)
  writeLines(nexus_lines, fileConn)
  close(fileConn)
  
  log4r::info(fn_logger, paste0("File created: ", params$prefix, ".nex."))
  rm(mstrees, res)
}
```

```{r alisim, include=FALSE}
if (file.exists(paste0(fn_alisim, ".fa")) && !params$redo) {
  log4r::info(fn_logger, paste0("File found: ", params$prefix, ".fa."))
  
} else {
  iqtree_cmd <- paste(params$iqtree2dir,
                      "--alisim", fn_alisim,
                      "-Q", fn_nexus,
                      "-t", fn_mttrees,
                      "-m", params$alisim_model,
                      "--length", params$ms_l,
                      "-T 1 -af fasta -cptime 1000000 -redo --no-log")
  
  if (params$alisim_scale <= 0 || is.null(params$alisim_scale)) {
    system(iqtree_cmd)
  } else {
    system(paste(iqtree_cmd, "--branch-scale", params$alisim_scale))
  }
  
  log4r::info(fn_logger, paste0("File created: ", params$prefix, ".fa."))
}
```

```{r, include=FALSE}
# store final system time
sys_toc <- Sys.time()

# write the system time in log file
write.table(c("", paste0("Total elapsed time: ", round(as.numeric(difftime(sys_toc, sys_tic, units = "mins")), 3), " mins")),
            file=fn_log, quote=F, row.names=F, col.names=F, append=T)
```