---
title: "Summary of Non-overlapping Windows vs Truth"
---

```{r sumsetup, include=FALSE}
write.table(c("",
              "####################################",
              "####         NOW vs Truth       ####",
              "####################################"),
            file=fn_log, quote=F, row.names=F, col.names=F, append=T)

window_outdir <- paste0(getwd(), "/windows/")
window_sizes <- list.dirs(window_outdir, full.names = F, recursive = F)

# input/output files
fn_mstops <- paste0(getwd(), "/simulation/", params$prefix, ".mstops")
fn_summary <- paste0(window_outdir, params$prefix, ".sum")
```

```{r sumwindow, include=FALSE}
msfile <- data.table::fread(fn_mstops)

# iterate through window sizes
for (i in window_sizes) {
  temp_outdir <- paste0(window_outdir,i,"/summary/")
  
  fn_cmp <- paste0(temp_outdir, params$prefix, ".cmp")
  # fn_figure <- paste0(temp_outdir, params$prefix, ".cmp.tiff")
  if (file.exists(fn_cmp) && !params$redo) {
    log4r::info(fn_logger, paste0("File found: ", i, "bp window comparison file."))
    next
  }
  
  # read annotation summary file
  smfile <- data.table::fread(paste0(temp_outdir, params$prefix, ".atsum"))
  smfile$start <- as.numeric(smfile$start)
  smfile$stop <- as.numeric(smfile$stop)
  
  mstree_uq <- unique(msfile$topology)
  smtree_uq <- unique(smfile$newick)
  
  # match window topology with ms topology
  for (j in mstree_uq) {
    for (k in smtree_uq) {
      if (ape::all.equal.phylo(ape::unroot(ape::read.tree(text = j)), ape::read.tree(text = k))) {
        msfile[, topology := gsub(j, k, topology, fixed = TRUE)]
        break
      }
    }
  }
  
  # update mstrees
  mstree_uq <- unique(msfile$topology)
  mstree_uq_ln <- length(mstree_uq)
  
  # create empty dataframe
  output <- data.table::data.table(c(mstree_uq,"NT"), matrix(0, nrow=mstree_uq_ln+1, ncol=mstree_uq_ln))
  data.table::setnames(output, c("topology", mstree_uq))
  
  # iterate through ms topology file
  for (k in 1:nrow(msfile)){
    # extract the hmm topology based on ms topology switching
    start_idx <- tail(which(smfile$start <= msfile$start[k]), 1)
    stop_idx <- head(which(smfile$stop >= msfile$stop[k]), 1)
    
    # update lengths
    sites <- smfile[start_idx:stop_idx,]
    sites$start[1] <- msfile$start[k]
    sites$length[1] <- sites$stop[1] - sites$start[1] + 1
    
    last_idx <- nrow(sites)
    sites$stop[last_idx] <- msfile$stop[k]
    sites$length[last_idx] <- sites$stop[last_idx] - sites$start[last_idx] + 1
    
    topology_idx <- match(msfile$topology[k], colnames(output))
    
    # add number of window sites for the respective ms topology
    for (j in 1:nrow(sites)) {
      window_idx <- match(sites$newick[j], output$topology)
      
      if (is.na(window_idx)) {
        tempval <- as.numeric(output[mstree_uq_ln+1, ..topology_idx] + sites$length[j])
        output[mstree_uq_ln+1, eval(msfile$topology[k]) := tempval]
      } else {
        tempval <- as.numeric(output[window_idx, ..topology_idx] + sites$length[j])
        output[window_idx, eval(msfile$topology[k]) := tempval]
      }
    }
    
    rm(sites)
  }
  
  # visualization
  # sub_output <- data.frame(stringsAsFactors = FALSE)
  # 
  # for (j in 1:nrow(output)) {
  #   for (k in 2:ncol(output)) {
  #     sub_output <- rbind(sub_output, c(output$topology[j],colnames(output[k]),output[j,k]))
  #   }
  # }
  # colnames(sub_output) <- c("topology","sites","frequency")
  # sub_output$sites <- factor(sub_output$sites,levels = unique(sub_output$sites),ordered = T)
  # 
  # tiff(filename=fn_figure, units="px", width=2880, height=1800)
  # print(ggplot(sub_output, aes(fill=sites, y=as.numeric(frequency), x=topology)) + 
  #         geom_bar(position="dodge", stat="identity") +
  #         aes(x = fct_inorder(topology)) +
  #         ggtitle("Distribution of Sites from Non-Overlapping Window Analysis in Simulated Dataset") + 
  #         xlab("True topology from simulated data") +
  #         ylab("Number of sites from non-overlapping window analysis") +
  #         theme(
  #           plot.title = element_text(hjust = 0.5, size = 50),
  #           axis.title.x=element_text(size = 40, margin = margin(t=20, r=0, b=0, l=0)),
  #           axis.title.y=element_text(size = 40, margin = margin(t=0, r=20, b=0, l=0)),
  #           axis.text.y=element_text(size=30),
  #           axis.text.x=element_text(size=30),
  #           legend.title=element_blank(),
  #           legend.text=element_text(size=30),
  #           legend.key.size=unit(2,"cm")
  #         ))
  # dev.off()
  
  data.table::fwrite(output, file=fn_cmp, sep = "\t", quote = F)
  log4r::info(fn_logger, paste0("File created: ", i, "bp window comparison files (", params$prefix, ".cmp)."))
  
  rm(smfile, output)
}

rm(msfile)
```

```{r sumtable, include=FALSE}
t_accuracy <- c()

# iterate through window sizes
for (i in window_sizes) {
  fn_cmp <- paste0(window_outdir,i,"/summary/",params$prefix,".cmp")
  fn_iqtree <- paste0(window_outdir,i,"/trees/",params$prefix,".iqtree")
  fn_contiguous <- paste0(window_outdir,i,"/contiguous/trees/",params$prefix,".iqtree")
  
  # read and extract accuracy of each window
  cmp <- data.table::fread(fn_cmp)
  cmp <- as.matrix(cmp[,-1])
  
  acc <- sum(as.numeric(diag(cmp))) / sum(as.numeric(cmp)) * 100
  acc <- round(acc, 3)
  
  # extract information of interest
  aic <- gsub("^.* ", "", system(paste("grep '^Akaike information criterion'",fn_iqtree), intern = T))
  aicc <- gsub("^.* ", "", system(paste("grep '^Corrected Akaike information criterion'",fn_iqtree), intern = T))
  bic <- gsub("^.* ", "", system(paste("grep '^Bayesian information criterion'",fn_iqtree), intern = T))
  
  # change empty character to NA
  caic <- NA; caicc <- NA; cbic <- NA
  if (file.exists(fn_contiguous)) {
    caic <- gsub("^.* ", "", system(paste("grep '^Akaike information criterion'", fn_contiguous), intern = T))
    caicc <- gsub("^.* ", "", system(paste("grep '^Corrected Akaike information criterion'",fn_contiguous), intern = T))
    cbic <- gsub("^.* ", "", system(paste("grep '^Bayesian information criterion'",fn_contiguous), intern = T))
  }
  
  t_accuracy <- rbind(t_accuracy, c(i,acc,aic,aicc,bic,caic,caicc,cbic))
  rm(cmp, acc)
}

t_accuracy <- data.table::as.data.table(t_accuracy)
data.table::setnames(t_accuracy, c("window_size","accuracy","aic","aicc","bic","aic_ct","aicc_ct","bic_ct"))

data.table::fwrite(t_accuracy, file=fn_summary, quote=F, sep="\t")
log4r::info(fn_logger, paste0("File created/modified: summary table of NOW and ms (", params$prefix, ".sum)."))

# correlation plot
t_accuracy <- as.data.frame(t_accuracy)
t_accuracy <- t_accuracy[, colSums(is.na(t_accuracy))==0]

library(ggplot2)
pcolors <- RColorBrewer::brewer.pal(8, "Dark2")
iterator <- 0

for (c in 3:ncol(t_accuracy)) {
  fn_sumfig <- paste0(window_outdir, params$prefix, ".", colnames(t_accuracy)[c],".tiff")
  iterator <- iterator + 1
  
  tiff(filename=fn_sumfig, units="px", width=2880, height=1800)
  print(ggplot(t_accuracy, aes(y=as.numeric(accuracy), x=as.numeric(t_accuracy[,c]), ymin=0, ymax=100)) + 
          geom_jitter(shape=16, width = 0.2, height = 0.2, size=5) +
          scale_colour_manual(values = pcolors[iterator]) +
          ggtitle("Correlation of NOW Information Criterion and NOW Accuracy") + 
          xlab("Information criterion score") +
          ylab("Accuracy (%)") +
          theme(
            plot.title = element_text(hjust = 0.5, size = 50),
            axis.title.x=element_text(size = 40, margin = margin(t=20, r=0, b=0, l=0)),
            axis.title.y=element_text(size = 40, margin = margin(t=0, r=20, b=0, l=0)),
            axis.text.y=element_text(size=30),
            axis.text.x=element_text(size=30),
            legend.title=element_blank(),
            legend.text=element_text(size=30),
            legend.key.size=unit(2,"cm")
          ))
  dev.off()
}

log4r::info(fn_logger, paste0("File created/modified: NOW accuracy vs NOW IC correlation plots."))
rm(t_accuracy)
```