---
title: "Non-overlapping Windows Report"
params:
  prefix: "helibut"
  outdir: "~/Documents/simulation/rmd_test"
  redo: TRUE
---

```{r setup, include=FALSE}
library(dplyr)
library(data.table)
library(ggplot2)
library(RColorBrewer)

knitr::opts_knit$set(include = FALSE)
```

```{r sim_summary}
fn_simsum <- paste(params$outdir, "/", params$prefix, ".simsum", sep="")
fn_simfig <- paste(params$outdir, "/", params$prefix, ".simsum.tiff", sep="")
if (file.exists(fn_simsum) && params$redo == FALSE) {
  print("Summary between simulations already exists. Quitting...")
  knitr::knit_exit()
}

allsims <- list.dirs(params$outdir, full.names = F, recursive = F)
simulation <- allsims[grep(paste("^",params$prefix,"_",sep=""), allsims)]

window_sizes <- list.dirs(paste(params$outdir,"/",simulation[1],"/windows/",sep=""), full.names = F, recursive = F)
window_sizes <- subset(window_sizes, window_sizes != paste(simulation[1],".summary",sep=""))

empty_matrix <- as.data.frame(matrix(rep(0, length(window_sizes)+1), nrow=length(simulation), ncol=length(window_sizes)+1))
names(empty_matrix) <- c(window_sizes, "r")
  
output <- data.frame(simulation = simulation)
output <- cbind(output, empty_matrix)

for (i in simulation) {
  row_idx <- which(output$simulation == i)
  
  fn_sum <- paste(params$outdir,"/",i,"/windows/",i,".sum",sep="")
  sumfile <- read.table(fn_sum)
  colnames(sumfile) <- sumfile[1,]
  sumfile <- sumfile[-1,]
  
  for (j in 1:nrow(sumfile)) {
    col_idx <- sumfile$window_size[j]
    output[row_idx,col_idx] <- sumfile$accuracy[j]
  }
  
  fn_ms <- paste(params$outdir,"/",i,"/simulation/",i,".ms",sep="")
  command <- strsplit(system(paste("grep 'ms'",fn_ms), intern=T), " ")
  
  output[row_idx,ncol(output)] = command[[1]][length(command[[1]])-1]
}

write.table(output, fn_simsum, quote = F, row.names = T, col.names = T)

print("Visualizing...")
sub_output <- data.frame()
pcolors <- RColorBrewer::brewer.pal(8, "Dark2")
  
for (i in 1:nrow(output)) {
  for (j in 3:ncol(output)-1) {
    sub_output <- rbind(sub_output, c(output$simulation[i],colnames(output[j]),output[i,j],output[i,ncol(output)]))
  }
}
colnames(sub_output) <- c("simulation","wsize","accuracy","r")
sub_output$wsize <- factor(as.numeric(sub_output$wsize))

tiff(filename=fn_simfig, units="px", width=2880, height=1800)
print(ggplot(sub_output, aes(y=as.numeric(accuracy), x=wsize, ymin=0, ymax=100)) + 
        geom_boxplot() +
        geom_jitter(shape=16, position=position_jitter(0.2), aes(colour=r), size=5) +
        scale_colour_manual(values = pcolors) +
        ggtitle("Accuracy of Non-Overlapping Windows in Simulated Dataset") + 
        xlab("Window size (bp)") +
        ylab("Accuracy (%)") +
        theme(
          plot.title = element_text(hjust = 0.5, size = 50),
          axis.title.x=element_text(size = 40, margin = margin(t=20, r=0, b=0, l=0)),
          axis.title.y=element_text(size = 40, margin = margin(t=0, r=20, b=0, l=0)),
          axis.text.y=element_text(size=20),
          axis.text.x=element_text(size=20),
          legend.title=element_text(size=30),
          legend.text=element_text(size=30),
          legend.key.size=unit(2,"cm")
        ))
dev.off()

iterator <- 0
for (i in unique(sub_output$r)) {
  fn_simfig <- paste(params$outdir, "/", params$prefix, ".simsum.r",i,".tiff", sep="")
  iterator <- iterator + 1
  outperr <- subset(sub_output, sub_output$r == i)
  
  tiff(filename=fn_simfig, units="px", width=2880, height=1800)
  print(ggplot(outperr, aes(y=as.numeric(accuracy), x=wsize, ymin=0, ymax=100)) + 
          geom_boxplot() +
          geom_jitter(shape=16, position=position_jitter(0.2), aes(colour=r), size=5) +
          scale_colour_manual(values = pcolors[iterator]) +
          ggtitle("Accuracy of Non-Overlapping Windows in Simulated Dataset") + 
          xlab("Window size (bp)") +
          ylab("Accuracy (%)") +
          theme(
            plot.title = element_text(hjust = 0.5, size = 50),
            axis.title.x=element_text(size = 40, margin = margin(t=20, r=0, b=0, l=0)),
            axis.title.y=element_text(size = 40, margin = margin(t=0, r=20, b=0, l=0)),
            axis.text.y=element_text(size=20),
            axis.text.x=element_text(size=20),
            legend.title=element_text(size=30),
            legend.text=element_text(size=30),
            legend.key.size=unit(2,"cm")
          ))
  dev.off()
}
```