---
title: "Summary of Multiple Non-overlapping Windows Analyses"
params:
  prefix: "sim"
  outdir: "~/simulation"
---

```{r setup, include=FALSE}
library(data.table)
library(dplyr)
library(ggplot2)

simsumdir <- paste0(params$outdir, "/summary/")
if (!dir.exists(simsumdir)) {
  dir.create(simsumdir, recursive = T)
}
```

```{r simsum, include=FALSE}
fn_simsum <- paste0(simsumdir, params$prefix, ".simsum")
fn_acc_ws <- paste0(simsumdir, params$prefix, ".acc_ws.tiff")

# extract row and column names
allsims <- list.dirs(params$outdir, full.names = F, recursive = F)
simulation <- allsims[grep(paste0("^",params$prefix), allsims)]
simulation <- simulation[simulation != "summary"]

window_sizes <- list.dirs(paste0(params$outdir,"/",simulation[1],"/windows/"), full.names = F, recursive = F)
window_sizes <- window_sizes[window_sizes != paste0(simulation[1],".summary")]

# extract summary for each simulation
cnnames <- NULL
simsum <- data.table::data.table()

for (i in simulation) {
  # read simulation summary file
  sumfile <- data.table::fread(paste0(params$outdir,"/",i,"/windows/",i,".sum"))
  if (is.null(cnnames)){
    cnnames <- colnames(sumfile)[3:ncol(sumfile)]
  }
  
  # read ms file
  fn_ms <- paste0(params$outdir,"/",i,"/simulation/",i,".ms")
  command <- strsplit(system(paste("grep 'ms'",fn_ms), intern=T), " ")
  rrate <- as.numeric(command[[1]][match("-r", command[[1]]) + 1])
  
  sumfile <- data.table::data.table("simulation" = rep(i,nrow(sumfile)), sumfile, "r" = rep(rrate,nrow(sumfile)))
  simsum <- rbind(simsum, sumfile)
}

simsum$accuracy <- as.numeric(simsum$accuracy)
simsum$window_size <- factor(simsum$window_size/1000)
simsum$r <- factor(simsum$r)
data.table::fwrite(simsum, file=fn_simsum, quote = F, sep = "\t")

# visualization for all simulations
tiff(filename=fn_acc_ws, units="px")
print(ggplot(simsum, aes(y=accuracy, x=window_size, ymin=0, ymax=100)) + 
        geom_boxplot(outlier.shape = NA) +
        geom_point(shape=16, aes(colour=r, size=20)) +
        facet_wrap(.~r, scales = "free", ncol = 1) +
        ggtitle("Accuracy of Non-Overlapping Windows in Simulated Dataset") + xlab("Window size (kb)") + ylab("Accuracy (%)") +
        guides(size="none", colour=guide_legend(override.aes=list(size=8))) +
        theme(
          plot.title = element_text(hjust = 0.5, size = 50),
          plot.margin = margin(1.25, 1.25, 1.25, 1.25, "cm"),
          axis.title.x=element_text(size = 40, margin = margin(t=20, r=0, b=0, l=0)),
          axis.title.y=element_text(size = 40, margin = margin(t=0, r=20, b=0, l=0)),
          axis.text.y=element_text(size=30),
          axis.text.x=element_text(size=30),
          legend.title=element_text(size=30),
          legend.text=element_text(size=30),
          legend.key.size=unit(2,"cm")
        ))
dev.off()

for (i in 5:ncol(simsum)-1) {
  ifc <- colnames(simsum)[i]
  ifc_outdir <- paste0(simsumdir, ifc, "/")
  if (!dir.exists(ifc_outdir)) {
    dir.create(ifc_outdir)
  }
  
  # information criteria vs accuracy
  fn_simfig <- paste0(ifc_outdir, params$prefix, ".acc_ws.",ifc,".tiff")
  
  tiff(filename=fn_simfig, units="px", width=2880, height=1800)
  print(ggplot(simsum, aes(y=accuracy, x=unlist(simsum[,..i]), ymin=0, ymax=100, group=simulation)) +
          geom_line(aes(size=1, alpha=0.2)) +
          geom_point(aes(colour=window_size, size=20)) +
          facet_wrap(.~r, scales = "free") +
          viridis::scale_color_viridis(discrete = TRUE) +
          ggtitle(paste("Correlation between", toupper(ifc), "and Accuracy")) + xlab(toupper(ifc)) + ylab("Accuracy (%)") +
          labs(color="w_size (kb)") +
          guides(alpha="none", size="none", colour=guide_legend(override.aes=list(size=8))) +
          theme(
            plot.title = element_text(hjust = 0.5, size = 50),
            plot.margin = margin(1.25, 1.25, 1.25, 1.25, "cm"),
            axis.title.x=element_text(size = 40, margin = margin(t=20, r=0, b=0, l=0)),
            axis.title.y=element_text(size = 40, margin = margin(t=0, r=20, b=0, l=0)),
            axis.text.y=element_text(size=30),
            axis.text.x=element_text(size=30),
            strip.text = element_text(size = 30),
            legend.title=element_text(size=30),
            legend.text=element_text(size=30),
            legend.key.size=unit(2,"cm")
          ))
  dev.off()
  
  # accuracy loss
  acc_loss <- simsum %>% 
    group_by(simulation, r) %>% 
    mutate(max_acc = max(accuracy)) %>%
    slice(which.min(!!as.name(ifc))) %>% 
    summarise(acc_loss = max_acc - accuracy)

  fn_simfig <- paste0(ifc_outdir, params$prefix, ".acc_df.",ifc,".tiff")
  
  tiff(filename=fn_simfig, units="px", width=2880, height=1800)
  print(ggplot(acc_loss, aes(y=acc_loss, x=factor(r), ymin=0)) + 
          geom_boxplot(outlier.shape = NA) +
          geom_point(shape=16, aes(colour=r, size=20)) +
          ggtitle(paste("Loss of Accuracy for Lowest", toupper(ifc))) + xlab(toupper(ifc)) + ylab("Loss of Accuracy (%)") +
          guides(size="none", colour=guide_legend(override.aes=list(size=8))) +
          theme(
            plot.title = element_text(hjust = 0.5, size = 50),
            plot.margin = margin(1.25, 1.25, 1.25, 1.25, "cm"),
            axis.title.x=element_text(size = 40, margin = margin(t=20, r=0, b=0, l=0)),
            axis.title.y=element_text(size = 40, margin = margin(t=0, r=20, b=0, l=0)),
            axis.text.y=element_text(size=30),
            axis.text.x=element_text(size=30),
            legend.title=element_text(size=30),
            legend.text=element_text(size=30),
            legend.key.size=unit(2,"cm")
          ))
  dev.off()
  
  # information criterion vs window size
  fn_simfig <- paste0(ifc_outdir, params$prefix, ".ifc_ws.",ifc,".tiff")
  
  tiff(filename=fn_simfig, units="px", width=2880, height=1800)
  print(ggplot(simsum, aes(x=window_size, y=unlist(simsum[,..i]), group=simulation)) +
          geom_line(aes(size=1, alpha=0.2)) +
          geom_point(aes(colour=window_size, size=20)) +
          facet_wrap(.~r, scales = "free", ncol = 1) +
          viridis::scale_color_viridis(discrete = TRUE) +
          ggtitle(paste("Correlation between", toupper(ifc), "and Window Size")) + ylab(toupper(ifc)) + xlab("Window Size (kb)") +
          guides(color="none", alpha="none", size="none") +
          theme(
            plot.title = element_text(hjust = 0.5, size = 50),
            plot.margin = margin(1.25, 1.25, 1.25, 1.25, "cm"),
            axis.title.x=element_text(size = 40, margin = margin(t=20, r=0, b=0, l=0)),
            axis.title.y=element_text(size = 40, margin = margin(t=0, r=20, b=0, l=0)),
            axis.text.y=element_text(size=30),
            axis.text.x=element_text(size=30),
            legend.title=element_text(size=30),
            legend.text=element_text(size=30),
            legend.key.size=unit(2,"cm")
          ))
  dev.off()
}

# ranked IC vs ranked accuracy
simsum$accuracy <- -1 * simsum$accuracy
rank_simsum <- simsum %>%
  group_by(simulation, r) %>%
  mutate(
    across(
      where(is.numeric), min_rank))
simsum$accuracy <- -1 * simsum$accuracy

for (i in 5:ncol(rank_simsum)-1) {
  ifc <- colnames(rank_simsum)[i]
  ifc_outdir <- paste0(simsumdir, ifc, "/")
  if (!dir.exists(ifc_outdir)) {
    dir.create(ifc_outdir)
  }
  
  fn_simfig <- paste0(ifc_outdir, params$prefix, ".rank.acc_ws.",ifc,".tiff")
  
  tiff(filename=fn_simfig, units="px", width=2880, height=1800)
  print(ggplot(rank_simsum, aes(y=accuracy, x=unlist(rank_simsum[,i]), ymin=0, group=simulation)) +
          geom_line(aes(size=1, alpha=0.2)) +
          geom_point(aes(colour=window_size, size=20)) +
          facet_wrap(.~r, scales = "free") +
          viridis::scale_color_viridis(discrete = TRUE) +
          ggtitle(paste("Correlation between Ranked", toupper(ifc), "and Ranked Accuracy")) + xlab(paste("Ranked",toupper(ifc))) + ylab("Ranked Accuracy") +
          labs(color="w_size (kb)") +
          guides(alpha="none", size="none", colour=guide_legend(override.aes=list(size=8))) +
          theme(
            plot.title = element_text(hjust = 0.5, size = 50),
            plot.margin = margin(1.25, 0, 1.25, 0, "cm"),
            axis.title.x=element_text(size = 40, margin = margin(t=20, r=0, b=0, l=0)),
            axis.title.y=element_text(size = 40, margin = margin(t=0, r=20, b=0, l=0)),
            axis.text.y=element_text(size=30),
            axis.text.x=element_text(size=30),
            legend.title=element_text(size=30),
            legend.text=element_text(size=30),
            legend.key.size=unit(2,"cm")
          ))
  dev.off()
}
```
