---
title: "Summary of MAST Analyses"
params:
  prefix: ""
  outdir: ""
  redo: TRUE
  
  ic_type: "AIC"
  
  mast_analysis: "HiMAST"
---

```{r setup, include=FALSE}
library(dplyr)
library(data.table)
library(ggplot2)

# select analysis type
mast_analysis <- tolower(params$mast_analysis)
ic_type <- tolower(params$ic_type)

MAST <- "mast"
HiMAST <- "himast"
if (!mast_analysis %in% c(MAST, HiMAST)) {
  print("Error: invalid type of analysis. Exited.")
  knitr::knit_exit()
}

# set up working directory
hmmsumdir <- paste0(params$outdir, "/summary/", mast_analysis, "/")
if (!dir.exists(hmmsumdir)) {
  dir.create(hmmsumdir, recursive = T)
}

# output files
fn_hmmacc <- paste0(hmmsumdir, params$prefix, ".hmmacc")
```

```{r hmmtruthwindow, include=FALSE}
# retrieve all simulations
allsims <- list.dirs(params$outdir, full.names = F, recursive = F)
simulation <- allsims[grep(paste("^",params$prefix,"_",sep=""), allsims)]
simulation <- simulation[simulation != "summary"]

# retrieve all MAST models 
hmmdir <- paste0(params$outdir, "/", simulation[1], "/", mast_analysis, "/")
model_list <- list.dirs(hmmdir, full.names = F, recursive = F)
model_list <- subset(model_list, model_list != paste0(simulation[1], ".mast.tops"))

if (mast_analysis == HiMAST) {
  # MAST summary
  dfsets <- c()
  
  # retrieve topology set and recombination rate for each simulation
  for (s in simulation) {
    for (m in model_list) {
      fn_dftmp <- paste0(params$outdir, "/", s, "/", mast_analysis, "/", m, "/summary/", s, ".mh.sum")
      fn_nowsum <- paste0(params$outdir, "/", s, "/windows/", s, ".sum")
      fn_hmmsum_nw <- paste0(params$outdir, "/", s, "/", mast_analysis, "/", m, "/summary/", s, ".hmmnow")
      
      if (!all(file.exists(fn_dftmp, fn_nowsum, fn_hmmsum_nw))) {
        next
      }
      
      dftmp <- data.table::fread(fn_dftmp)
      nowsum <- data.table::fread(fn_nowsum)
      if (!ic_type %in% colnames(nowsum)) {
        print("Error: invalid information criterion type. Exited.")
        knitr::knit_exit()
      }
    
      nowrow <- nowsum %>%
        slice_min(!!as.name(ic_type)) %>%
        select(window_size, accuracy)
      
      # window-based HMM
      hmmsum_nw <- data.table::fread(fn_hmmsum_nw)
      hmmsum <- as.matrix(hmmsum_nw[,-1])
    
      # calculate the accuracy 
      acc <- sum(as.numeric(diag(hmmsum))) / sum(as.numeric(hmmsum)) * 100
      acc <- round(acc, 3)
      
      dfsets <- rbind(dfsets, c(s, m, nowrow$window_size[1], nowrow$accuracy[1], dftmp$accuracy[1], acc))
    }
  }
  
  dfsets <- data.table::as.data.table(dfsets)
  data.table::setnames(dfsets, c("simulation", "mast_model", "window_size", "now", "hmm", "hmm_now"))
  data.table::fwrite(dfsets, fn_hmmacc, quote = F, sep = "\t")
}
```
