---
title: "Treelikeness Analysis"
---

```{r tlsetup, include=FALSE}
write.table(c("",
              "####################################",
              "####        Treelikeness        ####",
              "####################################"),
            file=fn_log, quote=F, row.names=F, col.names=F, append=T)

window_outdir <- paste(getwd(), "/windows/", sep="")
window_sizes <- list.dirs(window_outdir, full.names = F, recursive = F)
```

```{r tl, include=FALSE}
all_ts <- data.frame(stringsAsFactors = FALSE)
fn_tiff <- paste(window_outdir, params$prefix, ".ts.tiff", sep="")

for (w in window_sizes) {
  tl_outdir <- paste(getwd(), "/windows/", w, "/treelikeness/", sep="")
  if (!dir.exists(tl_outdir)) {
    dir.create(tl_outdir, recursive = T)
  }
  
  fn_ts <- paste(tl_outdir, params$prefix, ".ts", sep="")
  if (file.exists(fn_ts) && !params$redo) {
    log4r::info(fn_logger, paste0("File exists: ts files (", w, " bp). Skipped.", sep=""))
    next
  }
  
  tl_treedir <- paste(tl_outdir, "trees/", sep="")
  if (!dir.exists(tl_treedir)) {
    dir.create(tl_treedir, recursive = T)
  }
  
  if (length(list.files(tl_treedir, pattern = "*.nwk")) != 0 && !params$redo) {
    log4r::info(fn_logger, paste0("File exists: Newick treefile (", w, " bp). Skipped.", sep=""))
    next
  }
  
  # list window alignments
  alpath <- paste(getwd(), "/windows/", w, "/alignment/", sep="")
  alfile <- list.files(alpath, pattern = "*.fa", full.names=T)

  # list window trees
  fn_treefile <- paste(getwd(), "/windows/", w, "/trees/", params$prefix, ".treefile", sep="")
  df_ts <- data.frame(stringsAsFactors = FALSE)
  ln <- 1
  
  con <- file(fn_treefile, open="r", blocking = TRUE)
  while (length(linetr <- readLines(con, n = 1, warn = FALSE))) {
    tmp_fnal <- strsplit(alfile[ln], "(/|\\.)")[[1]]
    tmp_fnal <- tmp_fnal[length(tmp_fnal)-1]
    
    tmp_fntr <- paste(tl_treedir, tmp_fnal, ".nwk", sep="")
    write.table(linetr, tmp_fntr, quote = F, row.names = F, col.names = F)
    
    ts <- tree.proportion(params$iqtree2dir, params$splittreedir, alfile[ln], network_algorithm = "neighbournet", trimmed = TRUE,
                          tree_path = tmp_fntr, run_IQTREE = FALSE, "dna")
    
    df_ts <- rbind(df_ts, c(tm_fnal, ts))
    ln <- ln + 1
  }
  close(con)
  
  colnames(df_ts) <- c("alignment","ts")
  write.table(df_ts, fn_ts, quote = F, row.names = F)
  log4r::info(fn_logger, paste0("File created: Treelikeness file (", w, " bp).", sep=""))
  
  # collective dataframe 
  df_ts$ts <- suppressWarnings(as.numeric(df_ts$ts))
  subts <- subset(df_ts[!is.na(df_ts$ts),])
  subts$wsize <- rep(as.numeric(w)/1000, nrow(subts))
    
  all_ts <- rbind(all_ts, subts)
}

tiff(file=fn_tiff, units="px", width=2880, height=1800)
print(ggplot(data=all_ts, aes(fill=wsize, y=ts, x=wsize, ymin=0, ymax=1)) +
  geom_point() +
  ggtitle("Treelikeness of Fixed Non-Overlapping Windows") + 
  xlab("Window Size (kb)") +
  ylab("Treelikeness") +
  theme(
    plot.title = element_text(hjust = 0.5, size = 50),
    axis.title.x=element_text(size = 40, margin = margin(t=20, r=0, b=0, l=0)),
    axis.title.y=element_text(size = 40, margin = margin(t=0, r=20, b=0, l=0)),
    axis.text.y=element_text(size=30),
    axis.text.x=element_text(size=30),
    legend.title=element_blank(),
    legend.text=element_text(size=30),
    legend.key.size=unit(2,"cm")
  ))
dev.off()

log4r::info(fn_logger, paste0("File created: Treelikeness plot file", sep=""))
```