---
title: "Non-overlapping Windows Analysis"
output:
  html_document:
    code_folding: show

params:
  # general
  codedir: "~/SimNOW/codes"
  prefix: "sim"
  outdir: "~/simulation"
  thread: 5
  redo: TRUE
  
  # ms
  ms_l: 1000000
  
  # IQ-TREE 2
  iqtree2dir: "~/iqtree-2.2.2.4-MacOSX/bin/iqtree2"
  set_model: TRUE
  set_blmin: TRUE
  
  dna_model: "JC"
  outgroup: ""
  
  # non-overlapping window analysis
  window_size: !r c(50000,100000,500000,1000000)
---

## Load required libraries and functions
```{r}
source(paste0(params$codedir, "/2_non_overlapping_window/functions.R"))

library(data.table)
library(dplyr)
library(doSNOW)
```

```{r, include=FALSE}
# install.packages("ape")
# install.packages("forcats")
# install.packages("ggplot2")
# install.packages("log4r")
# install.packages("seqinr")
# install.packages("stringr")

# store initial system time
sys_tic <- Sys.time()

# create outdir
currentdir <- paste0(params$outdir, "/", params$prefix)
if (!dir.exists(currentdir)) {
  dir.create(currentdir, recursive = T)
}

# create log file
fn_log <- paste0(params$outdir, "/", params$prefix, "/", params$prefix, ".log")
log_appender <- log4r::file_appender(fn_log, append = TRUE, layout = log4r::default_log_layout())
fn_logger <- log4r::logger(threshold = "INFO", appenders = log_appender)

knitr::opts_knit$set(root.dir = currentdir)
```

```{r child = paste0(params$codedir,"/2_non_overlapping_window/2_run.Rmd")}
```

```{r child = paste0(params$codedir,"/2_non_overlapping_window/3_summary.Rmd")}
```

```{r, include=FALSE}
# store final system time
sys_toc <- Sys.time()

# write the system time in log file
write.table(c("", paste0("Total elapsed time: ", round(as.numeric(difftime(sys_toc, sys_tic, units = "mins")), 3), " mins")),
            file=fn_log, quote=F, row.names=F, col.names=F, append=T)
```