---
title: "Non-overlapping Windows Analysis"
---

## Run non-overlapping windows on simulated alignment
```{r nowsetup, include=FALSE}
write.table(c("",
              "####################################",
              "####         NOW Analysis       ####",
              "####################################"),
            file=fn_log, quote=F, row.names=F, col.names=F, append=T)

if (length(params$window_size) == 0) {
  log4r::error(fn_logger, "Error: window size is not specified. Exited.")
  knitr::knit_exit()
}

# create windows dir
window_outdir <- paste0(getwd(), "/windows/")
if (!dir.exists(window_outdir)) {
  dir.create(window_outdir, recursive = T)
}

# input files
fn_alisim <- paste0(getwd(), "/simulation/", params$prefix, ".fa")
fn_uqtops <- paste0(getwd(), "/simulation/", params$prefix, ".uqtops")
```

### Generating window alignments
```{r nowalignment}
write.table(c("",
              "---------- Window Alignment --------"),
              file=fn_log, quote=F, row.names=F, col.names=F, append=T)

# read fasta file
s <- seqinr::read.fasta(fn_alisim, whole.header = T)

# create doSNOW cluster
nwcl <- makeCluster(params$thread)
doSNOW::registerDoSNOW(nwcl)

# iterate through window sizes
foreach (w = sort(params$window_size)) %dopar% {
  # load required function
  source(paste0(params$codedir, "/2_non_overlapping_window/functions.R"))

  # prevent the use of scientific notation for big numbers
  options(scipen=999)

  # total alignment length should be divisible by the window size
  numw <- params$ms_l/w
  if (w == 0 || !numw%%1 == 0) {
    log4r::warn(fn_logger, paste0("Warning: invalid window size (", w, "bp). Skipped."))
    return(NULL)
  }
  
  # create outdir
  temp_outdir <- paste0(window_outdir, w, "/alignment/")
  if (!dir.exists(temp_outdir)) {
    dir.create(temp_outdir, recursive = T)
  }
  
  # skip if window alignments exist
  if (length(list.files(temp_outdir, pattern='fa')) == numw && !params$redo) {
    log4r::info(fn_logger, paste0("File found: ", w, "bp window alignment."))
    return(NULL)
  } 
  
  # remove all alignments in the folder
  unlink(paste0(temp_outdir,"*.fa"))
  
  # generate window alignments
  f_window_alignment(s, w, numw, temp_outdir)

  log4r::info(fn_logger, paste0("File created: ", w, "bp window alignment."))
}

rm(s)
stopCluster(nwcl)
```

### Generating window trees
```{r nowtree}
write.table(c("",
              "------------ Window Tree -----------"),
              file=fn_log, quote=F, row.names=F, col.names=F, append=T)

# prevent the use of scientific notation for big numbers
options(scipen=999)

# extract the updated list of window size
window_sizes <- list.dirs(window_outdir, full.names = F, recursive = F)
window_sizes <- sort(as.numeric(window_sizes))

# iterate through window sizes
for (i in window_sizes) {
  # check input alignments
  fastadir <- paste0(window_outdir,i,"/alignment/")
  numf <- length(list.files(fastadir, pattern='fa'))
  numw <- params$ms_l/i
  if (numw != numf) {
    log4r::warn(fn_logger, paste0("Warning: ", w, "bp window has ", numf, "/", numw, " alignments. Skipped."))
    next
  }

  # create outdir
  temp_outdir <- paste0(window_outdir,i,"/trees/")
  if (!dir.exists(temp_outdir)) {
    dir.create(temp_outdir, recursive = T)
  }
  
  # set prefix for iqtree2
  prefix <- paste0(temp_outdir,params$prefix)
  if (file.exists(paste0(prefix, ".treefile")) && !params$redo) {
    log4r::info(fn_logger, paste0("File found: ", i, "bp window treefile."))
    next
  }
  
  # set the number of threads according to the number of windows
  tthread <- params$thread
  if (numw < tthread) {
    tthread <- numw
  }
  
  # generate window trees
  f_window_tree(fastadir, prefix, tthread,
                params$outgroup, params$set_model, params$set_blmin, params$dna_model, i,
                params$iqtree2dir)

  log4r::info(fn_logger, paste0("File created: ", i, "bp window treefile."))
}
```

### Annotating window trees
```{r nowsummary}
# create doSNOW cluster
nwcl <- makeCluster(params$thread)
doSNOW::registerDoSNOW(nwcl)

# iterate through window sizes
foreach (i = window_sizes) %dopar% {
  # load required libraries and function
  source(paste0(params$codedir, "/2_non_overlapping_window/functions.R"))

  library(data.table)
  library(dplyr)
  
  # prevent the use of scientific notation for big numbers
  options(scipen=999)
  
  # create outdir
  temp_outdir <- paste0(window_outdir, i ,"/summary/")
  if (!dir.exists(temp_outdir)) {
    dir.create(temp_outdir, recursive = T)
  }
  
  # retrieve each fasta file and its respective topology
  fn_treefile <- paste0(window_outdir, i, "/trees/", params$prefix, ".treefile")
  if (!file.exists(fn_treefile)) {
    log4r::warn(fn_logger, paste0("Warning: ", i, "bp window treefile is not found. Skipped."))
    return(NULL)
  }
  
  # extract list of window alignment
  seq_list <- stringr::str_sort(list.files(paste0(window_outdir, i, "/alignment/")), numeric=TRUE)

  # annotate window trees
  f_annotate_window_tree(fn_treefile, seq_list, i, params$prefix, temp_outdir)

  log4r::info(fn_logger, paste0("File created: ", i, "bp summary files"))
}

stopCluster(nwcl)
```