---
title: "Summary of Non-overlapping Windows vs Truth"
---

## Summarize accuracy of non-overlapping windows on simulated alignment
```{r sumsetup, include=FALSE}
write.table(c("",
              "####################################",
              "####         NOW vs Truth       ####",
              "####################################"),
            file=fn_log, quote=F, row.names=F, col.names=F, append=T)

window_outdir <- paste0(getwd(), "/windows/")
window_sizes <- stringr::str_sort(list.dirs(window_outdir, full.names = F, recursive = F), numeric=T)

# input/output files
fn_mstops <- paste0(getwd(), "/simulation/", params$prefix, ".mstops")
fn_summary <- paste0(window_outdir, params$prefix, ".sum")
```

### Comparing topology weight and site assignment between NOW and ms
```{r sumwindow}
# read ms topology file
msfile <- data.table::fread(fn_mstops)

# iterate through window sizes
for (i in window_sizes) {
  temp_outdir <- paste0(window_outdir,i,"/summary/")
  
  # output files
  fn_cmp <- paste0(temp_outdir, params$prefix, ".cmp")
  fn_cmptw <- paste0(temp_outdir, params$prefix, ".cmptw")
  if (all(file.exists(fn_cmp, fn_cmptw)) && !params$redo) {
    log4r::info(fn_logger, paste0("File found: ", i, "bp window comparison file."))
    next
  }
  
  # read annotation summary file
  fn_smfile <- paste0(temp_outdir, params$prefix, ".atsum")
  if (!file.exists(fn_smfile)) {
    log4r::warn(fn_logger, paste0("Warn: ", i, "bp window annotation file not found. Skipped."))
    next
  }
  
  smfile <- data.table::fread(fn_smfile)
  smfile$start <- as.numeric(smfile$start)
  smfile$stop <- as.numeric(smfile$stop)
  
  # extract unique ms and NOW topologies
  mstree_uq <- unique(msfile$topology)
  smtree_uq <- unique(smfile$topology)
  
  # match window topology with ms topology
  for (j in mstree_uq) {
    for (k in smtree_uq) {
      if (ape::all.equal.phylo(ape::unroot(ape::read.tree(text = j)), ape::read.tree(text = k))) {
        smfile[, topology := gsub(k, j, topology, fixed = TRUE)]
        break
      }
    }
  }
  
  # create matrix for site accuracy
  f_create_site_acc_matrix(msfile, smfile, mstree_uq, fn_cmp)

  # compare weights between ms and NOW topologies
  f_compare_topology_weight(msfile, smfile, mstree_uq, params$ms_l, fn_cmptw)

  log4r::info(fn_logger, paste0("File created: ", i, "bp window comparison files (", params$prefix, ".cmp)."))
}

rm(msfile)
```

### Extracting accuracy and information criterion of NOW
```{r sumtable}
t_accuracy <- c()

# iterate through window sizes
for (i in window_sizes) {
  fn_cmp <- paste0(window_outdir,i,"/summary/",params$prefix,".cmp")
  fn_cmptw <- paste0(window_outdir,i,"/summary/",params$prefix,".cmptw")
  fn_iqtree <- paste0(window_outdir,i,"/trees/",params$prefix,".iqtree")
  
  # skip the analysis if input files do not exist
  if (!all(file.exists(fn_cmp,fn_cmptw,fn_iqtree))) {
    log4r::warn(fn_logger, paste0("Warn: ", i, "bp window comparison file not found. Skipped."))
    next
  }
  
  # extract the accuracy and IC score
  output <- f_extract_acc_and_ic(fn_cmp, fn_cmptw, fn_iqtree)
  
  # add the entry to the table
  t_accuracy <- rbind(t_accuracy, c(i,output))
}

# convert vector to data.table
t_accuracy <- data.table::as.data.table(t_accuracy)
data.table::setnames(t_accuracy, c("window_size","accuracy","aic","aicc","bic","rmse"))

# save the data.table
data.table::fwrite(t_accuracy, file=fn_summary, quote=F, sep="\t")
log4r::info(fn_logger, paste0("File created/modified: summary table of NOW and ms (", params$prefix, ".sum)."))

# print the subset of the output
head(t_accuracy)
```