---
title: "Summary of SimNOW Runs"
author: "Jeremias Ivan"
date: "`r format(Sys.time(), '%d %B %Y, %H:%M%p')`"

output:
  html_document:
    code_folding: show
    toc: true
    toc_float: true

params:
  codedir: "~/SimNOW/codes"
  prefix: "sim"
  outdir: "~/simulation"
---

## Load required libraries and functions
```{r}
source(paste0(params$codedir, "/4_all_runs_summary/functions.R"))
source(paste0(params$codedir, "/4_all_runs_summary/functions_html.R"))

library(data.table)
library(kableExtra)
library(tidyverse)
```

```{r setup, include=FALSE}
# install.packages("viridis")

# output directories
simsumdir <- paste0(params$outdir, "/summary/")
sitedir <- paste0(simsumdir, "site/")
rmsedir <- paste0(simsumdir, "rmse/")

# create directory if not exist
lapply(list(simsumdir,sitedir,rmsedir), function(x){if(!dir.exists(x)) dir.create(x, recursive=T)})

# output files
fn_simsum <- paste0(simsumdir, params$prefix, ".simsum")
fn_site_rmse <- paste0(simsumdir, params$prefix, ".site_rmse.tiff")
fn_site_ws <- paste0(sitedir, params$prefix, ".site_ws.tiff")
fn_rmse_ws <- paste0(rmsedir, params$prefix, ".rmse_ws.tiff")
```

```{r simsum, include=FALSE}
# extract list of simulation
allsims <- list.dirs(params$outdir, full.names = F, recursive = F)
simulation <- str_sort(allsims[grep(paste0("^",params$prefix), allsims)], numeric=T)
simulation <- simulation[simulation != "summary"]

# extract list of window size
window_sizes <- list.dirs(paste0(params$outdir,"/",simulation[1],"/windows/"), full.names = F, recursive = F)
window_sizes <- window_sizes[window_sizes != paste0(simulation[1],".sum")]

# initiate variables
cnnames <- NULL
simsum <- data.table::data.table()

# iterate over simulation
for (i in simulation) {
  # read simulation summary file
  sumfile <- data.table::fread(paste0(params$outdir,"/",i,"/windows/",i,".sum"))
  if (is.null(cnnames)){
    cnnames <- colnames(sumfile)[3:ncol(sumfile)]
  }
  
  # read ms file
  fn_ms <- paste0(params$outdir,"/",i,"/simulation/",i,".ms")

  # extract recombination rate
  command <- strsplit(system(paste("grep 'ms'",fn_ms), intern=T), " ")
  rrate <- as.numeric(command[[1]][match("-r", command[[1]]) + 1])
  
  # add the simulation details onto the big table
  sumfile <- data.table::data.table("simulation" = rep(i, nrow(sumfile)), sumfile, "r" = rep(rrate,nrow(sumfile)))
  simsum <- rbind(simsum, sumfile)
}

# convert the columns into their respective data types
simsum$accuracy <- as.numeric(simsum$accuracy)
simsum$rmse <- as.numeric(simsum$rmse)
simsum$window_size <- factor(simsum$window_size/1000)
simsum$r <- factor(simsum$r)

# add ranked data.frame
simsum$accuracy <- -1 * simsum$accuracy
rank_simsum <- simsum %>%
  group_by(simulation, r) %>%
  mutate(
    across(
      where(is.numeric), min_rank))
simsum$accuracy <- -1 * simsum$accuracy

# select the best window size
best_simsum <- simsum %>%
  group_by(simulation, r) %>%
  mutate(measure=case_when(
    accuracy==max(accuracy) & rmse==min(rmse) ~ "site+rmse",
    accuracy==max(accuracy) ~ "site",
    rmse==min(rmse) ~ "rmse",
    TRUE ~ "other"
  )) %>%
  filter(measure != "other")

# extract column indices
idx_site <- which(colnames(best_simsum) == "accuracy")
idx_rmse <- which(colnames(best_simsum) == "rmse")

# save the summary file
data.table::fwrite(simsum, file=fn_simsum, quote = F, sep = "\t")
```

## Summary table of accuracy and information criteria between simulations {.tabset}
### Summary
```{r}
kable(simsum) %>%
  kable_styling("striped", full_width = T) %>%
  scroll_box(width = "100%", height = ifelse(nrow(simsum) > 7, "300px", ""))
```

### Ranked summary
```{r}
kable(rank_simsum) %>%
  kable_styling("striped", full_width = T) %>%
  scroll_box(width = "100%", height = ifelse(nrow(rank_simsum) > 7, "300px", ""))
```

### Best window size
```{r}
kable(best_simsum) %>%
  kable_styling("striped", full_width = T) %>%
  column_spec(idx_site, bold = grepl("site", best_simsum$measure)) %>%
  column_spec(idx_rmse, bold = grepl("rmse", best_simsum$measure)) %>%
  scroll_box(width = "100%", height = ifelse(nrow(best_simsum) > 7, "300px", ""))
```

```{r allplots, include=FALSE}
# visualization for all simulations (window size vs accuracy)
tiff(filename=fn_site_ws, units="px", width=1600, height=2800)
print(f_acc_wsize(simsum, "site"))
dev.off()

# visualization for all simulations (window size vs RMSE)
tiff(filename=fn_rmse_ws, units="px", width=1600, height=2800)
print(f_acc_wsize(simsum, "rmse"))
dev.off()

# visualization for all simulations (site accuracy vs RMSE)
tiff(filename=fn_site_rmse, units="px", width=2880, height=1800)
print(f_acc_rmse(simsum))
dev.off()

# iterate over information criteria
for (i in 6:ncol(simsum)-2) {
  # initiate variables
  ifc <- colnames(simsum)[i]
  ifc_sitedir <- paste0(sitedir, ifc, "/")
  ifc_rmsedir <- paste0(rmsedir, ifc, "/")
  
  # create directories if not exist
  lapply(list(ifc_sitedir,ifc_rmsedir), function(x){if(!dir.exists(x)) dir.create(x, recursive=T)})
  
  # information criteria vs accuracy / rmse
  fn_sitefig <- paste0(ifc_sitedir, params$prefix, ".", ifc, "_site.tiff")
  fn_rmsefig <- paste0(ifc_rmsedir, params$prefix, ".", ifc, "_rmse.tiff")

  tiff(filename=fn_sitefig, units="px", width=2880, height=1800)
  print(f_ic_acc(simsum, i, ifc, "site"))
  dev.off()
  
  tiff(filename=fn_rmsefig, units="px", width=2880, height=1800)
  print(f_ic_acc(simsum, i, ifc, "rmse"))
  dev.off()

  # delta information criteria vs delta accuracy / rmse
  fn_sitefig <- paste0(ifc_sitedir, params$prefix, ".", ifc, "_site_delta.tiff")
  fn_rmsefig <- paste0(ifc_rmsedir, params$prefix, ".", ifc, "_rmse_delta.tiff")
  
  tiff(filename=fn_sitefig, units="px", width=2880, height=1800)
  print(f_delta_ic_acc(simsum, i, ifc, "site"))
  dev.off()

  tiff(filename=fn_rmsefig, units="px", width=2880, height=1800)
  print(f_delta_ic_acc(simsum, i, ifc, "rmse"))
  dev.off()
  
  # accuracy loss
  acc_loss <- simsum %>% 
    group_by(simulation, r) %>% 
    mutate(max_acc = max(accuracy), min_rmse = min(rmse)) %>%
    slice(which.min(!!as.name(ifc))) %>% 
    summarise(site_loss = max_acc - accuracy, rmse_gain = rmse - min_rmse)

  fn_sitefig <- paste0(ifc_sitedir, params$prefix, ".", ifc, "_site_loss.tiff")
  fn_rmsefig <- paste0(ifc_rmsedir, params$prefix, ".", ifc, "_rmse_loss.tiff")
  
  tiff(filename=fn_sitefig, units="px", width=2880, height=1800)
  print(f_acc_loss(acc_loss, ifc, "site"))
  dev.off()
  
  tiff(filename=fn_rmsefig, units="px", width=2880, height=1800)
  print(f_acc_loss(acc_loss, ifc, "rmse"))
  dev.off()
  
  # information criterion vs window size
  fn_simfig <- paste0(simsumdir, params$prefix, ".", ifc, "_ws.tiff")
  
  tiff(filename=fn_simfig, units="px", width=1600, height=2800)
  print(f_ic_wsize(simsum, i, ifc))
  dev.off()

  # ranked IC vs ranked accuracy
  fn_sitefig <- paste0(ifc_sitedir, params$prefix, ".", ifc, "_site_rank.tiff")
  fn_rmsefig <- paste0(ifc_rmsedir, params$prefix, ".", ifc, "_rmse_rank.tiff")
  
  tiff(filename=fn_sitefig, units="px", width=2880, height=1800)
  print(f_rank_ic_acc(rank_simsum, i, ifc, "site"))
  dev.off()
  
  tiff(filename=fn_rmsefig, units="px", width=2880, height=1800)
  print(f_rank_ic_acc(rank_simsum, i, ifc, "rmse"))
  dev.off()
}
```

## Summary plots between simulations {.tabset}
### Window size vs. site accuracy
```{r, out.width="100%", echo=FALSE}
print(f_acc_wsize_2(simsum, "site"))
```

### Window size vs. RMSE
```{r, out.width="100%", echo=FALSE}
print(f_acc_wsize_2(simsum, "rmse"))
```

### Site accuracy vs. RMSE
```{r, out.width="100%", echo=FALSE}
print(f_acc_rmse_2(simsum))
```

## Summary plots of information criteria
### AIC {.tabset}
```{r plot-aic, include=FALSE}
ifc <- "aic"

# calculate accuracy loss
acc_loss <- simsum %>% 
  group_by(simulation, r) %>% 
  mutate(max_acc = max(accuracy), min_rmse = min(rmse)) %>%
  slice(which.min(!!as.name(ifc))) %>% 
  summarise(site_loss = max_acc - accuracy, rmse_gain = rmse - min_rmse)
```

```{r, results='asis', out.width="100%", echo=FALSE}
f_plot_all(simsum, acc_loss, rank_simsum, 4, ifc)
```

### AICc {.tabset}
```{r plot-aicc, include=FALSE}
ifc <- "aicc"

# calculate accuracy loss
acc_loss <- simsum %>% 
  group_by(simulation, r) %>% 
  mutate(max_acc = max(accuracy), min_rmse = min(rmse)) %>%
  slice(which.min(!!as.name(ifc))) %>% 
  summarise(site_loss = max_acc - accuracy, rmse_gain = rmse - min_rmse)
```

```{r, results='asis', out.width="100%", echo=FALSE}
f_plot_all(simsum, acc_loss, rank_simsum, 5, ifc)
```

### BIC {.tabset}
```{r plot-bic, include=FALSE}
ifc <- "bic"

# calculate accuracy loss
acc_loss <- simsum %>% 
  group_by(simulation, r) %>% 
  mutate(max_acc = max(accuracy), min_rmse = min(rmse)) %>%
  slice(which.min(!!as.name(ifc))) %>% 
  summarise(site_loss = max_acc - accuracy, rmse_gain = rmse - min_rmse)
```

```{r, results='asis', out.width="100%", echo=FALSE}
f_plot_all(simsum, acc_loss, rank_simsum, 6, ifc)
```