---
title: "Summary of Multiple Non-overlapping Windows Analyses"
params:
  prefix: "sim"
  outdir: "~/simulation"
---

```{r setup, include=FALSE}
# install.packages("viridis")

library(data.table)
library(dplyr)
library(ggplot2)

simsumdir <- paste0(params$outdir, "/summary/")
sitedir <- paste0(simsumdir, "site/")
rmsedir <- paste0(simsumdir, "rmse/")

# create directory if not exist
lapply(list(simsumdir,sitedir,rmsedir), function(x){if(!dir.exists(x)) dir.create(x, recursive=T)})
```

```{r function, include=FALSE}
f_acc_wsize <- function(df, type) {
  plot <- NULL
  if (type == "site") {
    plot <- ggplot(df, aes(y=accuracy, x=window_size, ymin=0, ymax=100)) +
      ggtitle("Site Classification Accuracy of Non-Overlapping Windows in Simulated Datasets") +
      xlab("Window size (kb)") + ylab("Accuracy (%)")
  } else if (type == "rmse") {
    plot <- ggplot(df, aes(y=rmse, x=window_size, ymin=0)) +
      ggtitle("RMSE of Non-Overlapping Windows in Simulated Datasets") +
      xlab("Window size (kb)") + ylab("RMSE (%)")
  }

  plot <- plot +
    geom_boxplot(outlier.shape = NA) +
    geom_point(shape=16, aes(colour=r, size=20)) +
    facet_wrap(.~r, scales = "free", ncol = 1) +
    guides(size="none", colour="none") +
    theme(
      plot.title = element_text(hjust = 0.5, size = 50),
      plot.margin = margin(1.25, 1.25, 1.25, 1.25, "cm"),
      axis.title.x=element_text(size = 40, margin = margin(t=20, r=0, b=0, l=0)),
      axis.title.y=element_text(size = 40, margin = margin(t=0, r=20, b=0, l=0)),
      axis.text.y=element_text(size=30),
      axis.text.x=element_text(size=30),
      strip.text = element_text(size = 30)
    )

  return(plot)
}

f_acc_rmse <- function(df) {
  plot <- ggplot(df, aes(y=accuracy, x=rmse, ymin=0, xmin=0, group=simulation)) +
    ggtitle("Correlation between Site Classification Accuracy and RMSE") +
    xlab("RMSE (%)") + ylab("Accuracy (%)") +
    geom_point(aes(colour=window_size, size=20)) +
    geom_smooth(method = lm) +
    facet_wrap(.~r, scales = "free") +
    viridis::scale_color_viridis(discrete = TRUE) +
    labs(color="w_size (kb)") +
    guides(size="none", colour=guide_legend(override.aes=list(size=8))) +
    theme(
      plot.title = element_text(hjust = 0.5, size = 50),
      plot.margin = margin(1.25, 0, 1.25, 0, "cm"),
      axis.title.x=element_text(size = 40, margin = margin(t=20, r=0, b=0, l=0)),
      axis.title.y=element_text(size = 40, margin = margin(t=0, r=20, b=0, l=0)),
      axis.text.y=element_text(size=30),
      axis.text.x=element_text(size=30),
      strip.text = element_text(size = 30),
      legend.title=element_text(size=30),
      legend.text=element_text(size=30),
      legend.key.size=unit(2,"cm")
    )

  return(plot)
}

f_ic_acc <- function(df, i, ifc, type) {
  plot <- NULL
  if (type == "site") {
    plot <- ggplot(df, aes(y=accuracy, x=as.numeric(unlist(df[,..i])), ymin=0, ymax=100, group=simulation)) +
      ggtitle(paste("Correlation between", toupper(ifc), "and Site Classification Accuracy")) +
      xlab(toupper(ifc)) + ylab("Accuracy (%)")
  } else if (type == "rmse") {
    plot <- ggplot(df, aes(y=rmse, x=as.numeric(unlist(df[,..i])), ymin=0, group=simulation)) +
      ggtitle(paste("Correlation between", toupper(ifc), "and RMSE")) +
      xlab(toupper(ifc)) + ylab("RMSE (%)")
  }
  
  plot <- plot +
    geom_line(aes(size=1, alpha=0.2)) +
    geom_point(aes(colour=window_size, size=20)) +
    facet_wrap(.~r, scales = "free") +
    viridis::scale_color_viridis(discrete = TRUE) + 
    labs(color="w_size (kb)") +
    guides(alpha="none", size="none", colour=guide_legend(override.aes=list(size=8))) +
    theme(
      plot.title = element_text(hjust = 0.5, size = 50),
      plot.margin = margin(1.25, 1.25, 1.25, 1.25, "cm"),
      axis.title.x=element_text(size = 40, margin = margin(t=20, r=0, b=0, l=0)),
      axis.title.y=element_text(size = 40, margin = margin(t=0, r=20, b=0, l=0)),
      axis.text.y=element_text(size=30),
      axis.text.x=element_text(size=30),
      strip.text = element_text(size = 30),
      legend.title=element_text(size=30),
      legend.text=element_text(size=30),
      legend.key.size=unit(2,"cm")
    )
  
  return(plot)
}

f_acc_loss <- function(df, ifc, type) {
  plot <- NULL
  if (type == "site") {
    plot <- ggplot(df, aes(y=site_loss, x=factor(r), ymin=0)) +
      ggtitle(paste("Loss of Site Classification Accuracy for Lowest", toupper(ifc))) +
      xlab("Recombination rate (rho)") + ylab("Loss of Site Classification Accuracy (%)")
  } else if (type == "rmse") {
    plot <- ggplot(df, aes(y=rmse_gain, x=factor(r), ymin=0)) +
      ggtitle(paste("Increase in RMSE for Lowest", toupper(ifc))) +
      xlab("Recombination rate (rho)") + ylab("Increase in RMSE (%)")
  }
  
  plot <- plot +
    geom_boxplot(outlier.shape = NA) +
    geom_point(shape=16, aes(colour=r, size=20)) +
    guides(size="none", colour="none") +
    theme(
      plot.title = element_text(hjust = 0.5, size = 50),
      plot.margin = margin(1.25, 1.25, 1.25, 1.25, "cm"),
      axis.title.x=element_text(size = 40, margin = margin(t=20, r=0, b=0, l=0)),
      axis.title.y=element_text(size = 40, margin = margin(t=0, r=20, b=0, l=0)),
      axis.text.y=element_text(size=30),
      axis.text.x=element_text(size=30)
    )
  
  return(plot)
}

f_ic_wsize <- function(df, i, ifc) {
  plot <- ggplot(df, aes(x=window_size, y=as.numeric(unlist(df[,..i])), group=simulation)) +
    geom_line(aes(size=1, alpha=0.2)) +
    geom_point(aes(colour=window_size, size=20)) +
    facet_wrap(.~r, scales = "free", ncol = 1) +
    viridis::scale_color_viridis(discrete = TRUE) +
    ggtitle(paste("Correlation between", toupper(ifc), "and Window Size")) + ylab(toupper(ifc)) + xlab("Window Size (kb)") +
    guides(color="none", alpha="none", size="none") +
    theme(
      plot.title = element_text(hjust = 0.5, size = 50),
      plot.margin = margin(1.25, 1.25, 1.25, 1.25, "cm"),
      axis.title.x=element_text(size = 40, margin = margin(t=20, r=0, b=0, l=0)),
      axis.title.y=element_text(size = 40, margin = margin(t=0, r=20, b=0, l=0)),
      axis.text.y=element_text(size=30),
      axis.text.x=element_text(size=30),
      strip.text = element_text(size = 30),
      legend.title=element_text(size=30),
      legend.text=element_text(size=30),
      legend.key.size=unit(2,"cm")
    )
  
  return(plot)
}

f_rank_ic_acc <- function(df, i, ifc, type) {
  plot <- NULL
  if (type == "site") {
    plot <- ggplot(df, aes(y=accuracy, x=unlist(df[,i]), ymin=0, group=simulation)) +
      ggtitle(paste("Correlation between Ranked", toupper(ifc), "and Ranked Site Classification Accuracy")) +
      xlab(paste("Ranked",toupper(ifc))) + ylab("Ranked Accuracy")
  } else if (type == "rmse") {
    plot <- ggplot(df, aes(y=rmse, x=unlist(df[,i]), ymin=0, group=simulation)) +
      ggtitle(paste("Correlation between Ranked", toupper(ifc), "and Ranked RMSE")) +
      xlab(paste("Ranked",toupper(ifc))) + ylab("Ranked RMSE")
  }
  
  plot <- plot +
    geom_line(aes(size=1, alpha=0.2)) +
    geom_point(aes(colour=window_size, size=20)) +
    facet_wrap(.~r, scales = "free") +
    viridis::scale_color_viridis(discrete = TRUE) +
    labs(color="w_size (kb)") +
    guides(alpha="none", size="none", colour=guide_legend(override.aes=list(size=8))) +
    theme(
      plot.title = element_text(hjust = 0.5, size = 50),
      plot.margin = margin(1.25, 0, 1.25, 0, "cm"),
      axis.title.x=element_text(size = 40, margin = margin(t=20, r=0, b=0, l=0)),
      axis.title.y=element_text(size = 40, margin = margin(t=0, r=20, b=0, l=0)),
      axis.text.y=element_text(size=30),
      axis.text.x=element_text(size=30),
      strip.text = element_text(size = 30),
      legend.title=element_text(size=30),
      legend.text=element_text(size=30),
      legend.key.size=unit(2,"cm")
    )
  
  return(plot)
}
```

```{r simsum, include=FALSE}
fn_simsum <- paste0(simsumdir, params$prefix, ".simsum")
fn_site_rmse <- paste0(simsumdir, params$prefix, ".site_rmse.tiff")
fn_site_ws <- paste0(sitedir, params$prefix, ".site_ws.tiff")
fn_rmse_ws <- paste0(rmsedir, params$prefix, ".rmse_ws.tiff")

# extract row and column names
allsims <- list.dirs(params$outdir, full.names = F, recursive = F)
simulation <- allsims[grep(paste0("^",params$prefix), allsims)]
simulation <- simulation[simulation != "summary"]

window_sizes <- list.dirs(paste0(params$outdir,"/",simulation[1],"/windows/"), full.names = F, recursive = F)
window_sizes <- window_sizes[window_sizes != paste0(simulation[1],".sum")]

# extract summary for each simulation
cnnames <- NULL
simsum <- data.table::data.table()

for (i in simulation) {
  # read simulation summary file
  sumfile <- data.table::fread(paste0(params$outdir,"/",i,"/windows/",i,".sum"))
  if (is.null(cnnames)){
    cnnames <- colnames(sumfile)[3:ncol(sumfile)]
  }
  
  # read ms file
  fn_ms <- paste0(params$outdir,"/",i,"/simulation/",i,".ms")
  command <- strsplit(system(paste("grep 'ms'",fn_ms), intern=T), " ")
  rrate <- as.numeric(command[[1]][match("-r", command[[1]]) + 1])
  
  sumfile <- data.table::data.table("simulation" = rep(i, nrow(sumfile)), sumfile, "r" = rep(rrate,nrow(sumfile)))
  simsum <- rbind(simsum, sumfile)
}

simsum$accuracy <- as.numeric(simsum$accuracy)
simsum$rmse <- as.numeric(simsum$rmse)
simsum$window_size <- factor(simsum$window_size/1000)
simsum$r <- factor(simsum$r)
data.table::fwrite(simsum, file=fn_simsum, quote = F, sep = "\t")

# visualization for all simulations (window size vs accuracy)
tiff(filename=fn_site_ws, units="px", width=1600, height=2800)
print(f_acc_wsize(simsum, "site"))
dev.off()

# visualization for all simulations (window size vs RMSE)
tiff(filename=fn_rmse_ws, units="px", width=1600, height=2800)
print(f_acc_wsize(simsum, "rmse"))
dev.off()

# visualization for all simulations (site accuracy vs RMSE)
tiff(filename=fn_site_rmse, units="px", width=2880, height=1800)
print(f_acc_rmse(simsum))
dev.off()

for (i in 6:ncol(simsum)-2) {
  ifc <- colnames(simsum)[i]
  ifc_sitedir <- paste0(sitedir, ifc, "/")
  ifc_rmsedir <- paste0(rmsedir, ifc, "/")
  
  # create directories if not exist
  lapply(list(ifc_sitedir,ifc_rmsedir), function(x){if(!dir.exists(x)) dir.create(x, recursive=T)})
  
  # information criteria vs accuracy / rmse
  fn_sitefig <- paste0(ifc_sitedir, params$prefix, ".", ifc, "_site.tiff")
  fn_rmsefig <- paste0(ifc_rmsedir, params$prefix, ".", ifc, "_rmse.tiff")
  
  tiff(filename=fn_sitefig, units="px", width=2880, height=1800)
  print(f_ic_acc(simsum, i, ifc, "site"))
  dev.off()
  
  tiff(filename=fn_rmsefig, units="px", width=2880, height=1800)
  print(f_ic_acc(simsum, i, ifc, "rmse"))
  dev.off()
  
  # accuracy loss
  acc_loss <- simsum %>% 
    group_by(simulation, r) %>% 
    mutate(max_acc = max(accuracy), min_rmse = min(rmse)) %>%
    slice(which.min(!!as.name(ifc))) %>% 
    summarise(site_loss = max_acc - accuracy, rmse_gain = rmse - min_rmse)

  fn_sitefig <- paste0(ifc_sitedir, params$prefix, ".", ifc, "_site_loss.tiff")
  fn_rmsefig <- paste0(ifc_rmsedir, params$prefix, ".", ifc, "_rmse_loss.tiff")
  
  tiff(filename=fn_sitefig, units="px", width=2880, height=1800)
  print(f_acc_loss(acc_loss, ifc, "site"))
  dev.off()
  
  tiff(filename=fn_rmsefig, units="px", width=2880, height=1800)
  print(f_acc_loss(acc_loss, ifc, "rmse"))
  dev.off()
  
  # information criterion vs window size
  fn_simfig <- paste0(simsumdir, params$prefix, ".", ifc, "_ws.tiff")
  
  tiff(filename=fn_simfig, units="px", width=1600, height=2800)
  print(f_ic_wsize(simsum, i, ifc))
  dev.off()
}

# ranked IC vs ranked accuracy
simsum$accuracy <- -1 * simsum$accuracy
rank_simsum <- simsum %>%
  group_by(simulation, r) %>%
  mutate(
    across(
      where(is.numeric), min_rank))
simsum$accuracy <- -1 * simsum$accuracy

for (i in 6:ncol(rank_simsum)-2) {
  ifc <- colnames(rank_simsum)[i]
  ifc_sitedir <- paste0(sitedir, ifc, "/")
  ifc_rmsedir <- paste0(rmsedir, ifc, "/")

  fn_sitefig <- paste0(ifc_sitedir, params$prefix, ".", ifc, "_site_rank.tiff")
  fn_rmsefig <- paste0(ifc_rmsedir, params$prefix, ".", ifc, "_rmse_rank.tiff")
  
  tiff(filename=fn_sitefig, units="px", width=2880, height=1800)
  print(f_rank_ic_acc(rank_simsum, i, ifc, "site"))
  dev.off()
  
  tiff(filename=fn_rmsefig, units="px", width=2880, height=1800)
  print(f_rank_ic_acc(rank_simsum, i, ifc, "rmse"))
  dev.off()
}
```
