---
title: "Summary of Multiple Non-overlapping Windows Analyses"
params:
  codedir: "~/SimNOW/empirical_analysis"
  prefix: "sim"
  outdir: "~/simulation"

  ic_type: "aic"
  colour_scheme: ""
---
```{r heliconius-setup, include=FALSE}
# install.packages("viridis")
# install.packages("ape")

# load libraries
library(data.table)
library(dplyr)
library(ggplot2)

source(paste0(params$codedir,"/datasets/heliconius_erato/codes/functions.R"), local=TRUE)

# output directory
simsumdir <- paste0(params$outdir, "/", params$prefix, "/summary/")
if (!dir.exists(simsumdir)) {
  dir.create(simsumdir, recursive=T)
}

fn_topsimsum <- paste0(simsumdir, params$prefix, ".topsimsum")
fn_topsimsum_fig <- paste0(simsumdir, params$prefix, ".topsimsum.tiff")
fn_topsimsum_eight_fig <- paste0(simsumdir, params$prefix, ".topsimsum_eight.tiff")
fn_cnsimsum <- paste0(simsumdir, params$prefix, ".cnsimsum")
fn_cnsimsum_fig <- paste0(simsumdir, params$prefix, ".cnsimsum.tiff")
fn_cnsimsum_eight_fig <- paste0(simsumdir, params$prefix, ".cnsimsum_eight.tiff")

fn_topsimsum_all <- paste0(simsumdir, params$prefix, ".all.topsimsum")
```

```{r heliconius-summary, include=FALSE}
allsims <- list.dirs(paste0(params$outdir,"/",params$prefix), full.names = F, recursive = F)
chrs <- allsims[grep("^chr", allsims)]

# iterate through chromosomes
df_topsimsum <- data.table::data.table(chr=character(), topology=character(), count=numeric(), cum.percentage=numeric(), colour=character())
df_topsimsum_all <- data.table::data.table(chr=character(), topology=character(), count=numeric(), count_percentage=numeric())
df_cnsimsum <- data.table::data.table(chr=character(), topology=character(), count=numeric(), colour=character(), tree=character())

for (c in chrs) {
  window_outdir <- paste0(params$outdir,"/",params$prefix,"/",c,"/windows/")

  fn_summary <- paste0(window_outdir, c, ".sum")
  if (!file.exists(fn_summary)){
    next
  }

  # extract the best window size
  sumfile <- data.table::fread(fn_summary)
  min_ic <- sumfile %>%
    slice_min(!!sym(tolower(params$ic_type)))
  best_wsize <- as.numeric(min_ic$window_size)*1000

  fn_atsum <- paste0(window_outdir, best_wsize, "/full/summary/", c, ".atsum")
  fn_topsum <- paste0(window_outdir, best_wsize, "/full/summary/", c, ".topsum")
  fn_cnsum <- paste0(window_outdir, best_wsize, "/full/summary/", c, ".cnsum")
  if (!all(file.exists(fn_atsum, fn_topsum, fn_cnsum))) {
    next
  }

  df_atsum <- data.table::fread(fn_atsum)
  df_atsum <- df_atsum %>%
    group_by(topology) %>%
    summarise(count=n()) %>%
    mutate(chr=c, count_percentage=count/sum(count))
  df_topsimsum_all <- rbind(df_topsimsum_all, df_atsum)

  df_topsum <- data.table::fread(fn_topsum)
  df_topsum$chr <- rep(c, nrow(df_topsum))
  df_topsimsum <- rbind(df_topsimsum, df_topsum, fill=TRUE)

  df_cnsum <- data.table::fread(fn_cnsum)
  df_cnsum$chr <- rep(c, nrow(df_cnsum))
  df_cnsimsum <- rbind(df_cnsimsum, df_cnsum, fill=TRUE)
}

if (params$colour_scheme != "") {
  df_colour <- data.table::fread(params$colour_scheme)

  top_topsum <- unique(df_topsimsum$topology)
  top_colour <- unique(df_colour$topology)

  # set colour
  for (j in top_topsum) {
    for (k in top_colour) {
      if (ape::all.equal.phylo(ape::unroot(ape::read.tree(text = j)), ape::unroot(ape::read.tree(text = k)))) {
        topology_idx <- match(k, df_colour$topology)

        df_topsimsum[topology == j, colour := df_colour$code[topology_idx]]
        df_cnsimsum[topology == j, colour := df_colour$code[topology_idx]]
        df_cnsimsum[topology == j, tree := df_colour$tree[topology_idx]]
        break
      }
    }
  }

  df_topsimsum[is.na(colour), colour := "#000000"]
  df_cnsimsum[is.na(colour), colour := "#000000"]
  df_cnsimsum[is.na(tree), tree := "NT"]
}

data.table::fwrite(df_topsimsum, file=fn_topsimsum, quote=F, sep="\t")
data.table::fwrite(df_topsimsum_all, file=fn_topsimsum_all, quote=F, sep="\t")
data.table::fwrite(df_cnsimsum, file=fn_cnsimsum, quote=F, sep="\t")
```

```{r heliconius-visualization, include=FALSE}
# topsimsum
plots <- f_topsimsum(df_topsimsum)
tiff(filename=fn_topsimsum_fig, units="px", width=3200, height=1800)
print(plots$plot1)
dev.off()

tiff(filename=fn_topsimsum_eight_fig, units="px", width=2880, height=1800)
print(plots$plot2)
dev.off()

# cnsimsum
plots <- f_cnsimsum(df_cnsimsum, plots$df)
tiff(filename=fn_cnsimsum_fig, units="px", width=2880, height=1800)
print(plots$plot1)
dev.off()

tiff(filename=fn_cnsimsum_eight_fig, units="px", width=2880, height=1800)
print(plots$plot2)
dev.off()
```

```{r heliconius-setup_nogaps, include=FALSE}
simsumdir <- paste0(params$outdir, "/", params$prefix, "/summary/nogaps/")
if (!dir.exists(simsumdir)) {
  dir.create(simsumdir, recursive=T)
}

fn_topsimsum <- paste0(simsumdir, params$prefix, ".topsimsum")
fn_topsimsum_fig <- paste0(simsumdir, params$prefix, ".topsimsum.tiff")
fn_topsimsum_eight_fig <- paste0(simsumdir, params$prefix, ".topsimsum_eight.tiff")
fn_cnsimsum <- paste0(simsumdir, params$prefix, ".cnsimsum")
fn_cnsimsum_fig <- paste0(simsumdir, params$prefix, ".cnsimsum.tiff")
fn_cnsimsum_eight_fig <- paste0(simsumdir, params$prefix, ".cnsimsum_eight.tiff")

fn_topsimsum_all <- paste0(simsumdir, params$prefix, ".all.topsimsum")
```

```{r heliconius-summary_nogaps, include=FALSE}
allsims <- list.dirs(paste0(params$outdir,"/",params$prefix), full.names = F, recursive = F)
chrs <- allsims[grep("^nogaps_chr", allsims)]

# iterate through chromosomes
df_topsimsum <- data.table::data.table(chr=character(), topology=character(), count=numeric(), cum.percentage=numeric(), colour=character())
df_topsimsum_all <- data.table::data.table(chr=character(), topology=character(), count=numeric(), count_percentage=numeric())
df_cnsimsum <- data.table::data.table(chr=character(), topology=character(), count=numeric(), colour=character(), tree=character())

for (c in chrs) {
  window_outdir <- paste0(params$outdir,"/",params$prefix,"/",c,"/windows/")

  fn_summary <- paste0(window_outdir, c, ".sum")
  if (!file.exists(fn_summary)){
    next
  }

  # extract the best window size
  sumfile <- data.table::fread(fn_summary)
  min_ic <- sumfile %>%
    slice_min(!!sym(tolower(params$ic_type)))
  best_wsize <- as.numeric(min_ic$window_size)*1000

  fn_atsum <- paste0(window_outdir, best_wsize, "/full/summary/", c, ".atsum")
  fn_topsum <- paste0(window_outdir, best_wsize, "/full/summary/", c, ".topsum")
  fn_cnsum <- paste0(window_outdir, best_wsize, "/full/summary/", c, ".cnsum")
  if (!all(file.exists(fn_atsum, fn_topsum, fn_cnsum))) {
    next
  }

  df_atsum <- data.table::fread(fn_atsum)
  df_atsum <- df_atsum %>%
    group_by(topology) %>%
    summarise(count=n()) %>%
    mutate(chr=c, count_percentage=count/sum(count))
  df_topsimsum_all <- rbind(df_topsimsum_all, df_atsum)

  df_topsum <- data.table::fread(fn_topsum)
  df_topsum$chr <- rep(c, nrow(df_topsum))
  df_topsimsum <- rbind(df_topsimsum, df_topsum, fill=TRUE)

  df_cnsum <- data.table::fread(fn_cnsum)
  df_cnsum$chr <- rep(c, nrow(df_cnsum))
  df_cnsimsum <- rbind(df_cnsimsum, df_cnsum, fill=TRUE)
}

if (params$colour_scheme != "") {
  df_colour <- data.table::fread(params$colour_scheme)

  top_topsum <- unique(df_topsimsum$topology)
  top_colour <- unique(df_colour$topology)

  # set colour
  for (j in top_topsum) {
    for (k in top_colour) {
      if (ape::all.equal.phylo(ape::unroot(ape::read.tree(text = j)), ape::unroot(ape::read.tree(text = k)))) {
        topology_idx <- match(k, df_colour$topology)

        df_topsimsum[topology == j, colour := df_colour$code[topology_idx]]
        df_cnsimsum[topology == j, colour := df_colour$code[topology_idx]]
        df_cnsimsum[topology == j, tree := df_colour$tree[topology_idx]]
        break
      }
    }
  }

  df_topsimsum[is.na(colour), colour := "#000000"]
  df_cnsimsum[is.na(colour), colour := "#000000"]
  df_cnsimsum[is.na(tree), tree := "NT"]
}

data.table::fwrite(df_topsimsum, file=fn_topsimsum, quote=F, sep="\t")
data.table::fwrite(df_topsimsum_all, file=fn_topsimsum_all, quote=F, sep="\t")
data.table::fwrite(df_cnsimsum, file=fn_cnsimsum, quote=F, sep="\t")
```

```{r heliconius-visualization_nogaps, include=FALSE}
# topsimsum
plots <- f_topsimsum(df_topsimsum)
tiff(filename=fn_topsimsum_fig, units="px", width=3200, height=1800)
print(plots$plot1)
dev.off()

tiff(filename=fn_topsimsum_eight_fig, units="px", width=2880, height=1800)
print(plots$plot2)
dev.off()

# cnsimsum
plots <- f_cnsimsum(df_cnsimsum, plots$df)
tiff(filename=fn_cnsimsum_fig, units="px", width=2880, height=1800)
print(plots$plot1)
dev.off()

tiff(filename=fn_cnsimsum_eight_fig, units="px", width=2880, height=1800)
print(plots$plot2)
dev.off()
```