---
title: "Summary of Non-overlapping Windows vs Truth"
---

## Summarize accuracy of non-overlapping windows on simulated alignment
```{r sumsetup, include=FALSE}
write.table(c("",
              "####################################",
              "####         DAC vs Truth       ####",
              "####################################"),
            file=fn_log, quote=F, row.names=F, col.names=F, append=T)

# input file
fn_mstrees <- paste0(getwd(), "/simulation/", params$prefix, ".mstrees")
fn_mstops <- paste0(getwd(), "/simulation/", params$prefix, ".mstops")

# create an output directory
outdir_summary <- paste0(dac_outdir, "summary/")
if (!dir.exists(outdir_summary)) {
  dir.create(outdir_summary, recursive=T)
}

# output files
fn_cmp <- paste0(outdir_summary, params$prefix, ".cmp")
fn_cmptw <- paste0(outdir_summary, params$prefix, ".cmptw")
fn_acc <- paste0(outdir_summary, params$prefix, ".acc")
fn_corlm <- paste0(outdir_summary, params$prefix, ".corlm")

fn_windowdist_tiff <- paste0(outdir_summary, params$prefix, ".wdist.tiff")
fn_windowdist_binned_tiff <- paste0(outdir_summary, params$prefix, ".wdist_binned.tiff")
```

### Comparing topology weight and site assignment between NOW and ms
```{r sumwindow}
# read ms topology file
mtfile <- data.table::fread(fn_mstrees)
mtfile <- mtfile %>%
  group_by(tree, group_run = data.table::rleid(tree)) %>%
  summarise(length=sum(length), start=start, stop=stop) %>%
  arrange(group_run)
mtfile$group_run <- NULL
mtfile <- data.table::as.data.table(mtfile)

msfile <- data.table::fread(fn_mstops)

# read now topology file
smfile <- data.table::fread(fn_dactops)

# output files
if (!all(file.exists(fn_cmp, fn_cmptw)) || params$redo) {
  # extract unique ms and NOW topologies
  mstree_uq <- unique(msfile$topology)
  smtree_uq <- unique(smfile$topology)

  # match window topology with ms topology
  for (j in mstree_uq) {
    for (k in smtree_uq) {
      if (ape::all.equal.phylo(ape::unroot(ape::read.tree(text = j)), ape::read.tree(text = k))) {
        smfile[, topology := gsub(k, j, topology, fixed = TRUE)]
        break
      }
    }
  }

  # create matrix for site accuracy
  f_create_site_acc_matrix(msfile, smfile, mstree_uq, fn_cmp)

  # compare weights between ms and NOW topologies
  f_compare_topology_weight(msfile, smfile, mstree_uq, sum(smfile$length), fn_cmptw)

  rm(msfile)
}

# extract accuracy
acc <- f_extract_acc(fn_cmp, fn_cmptw)

df_now <- data.table::data.table(method="now", min_wsize=as.numeric(best_wsize_aic), max_wsize=as.numeric(best_wsize_aic),
                                 acc=df_sum_now$accuracy[df_sum_now$window_size==best_wsize_aic],
                                 rmse=df_sum_now$rmse[df_sum_now$window_size==best_wsize_aic],
                                 aic=df_sum_now$aic[df_sum_now$window_size==best_wsize_aic])
df_dac <- data.table::data.table(method="dac", min_wsize=min(df_topology$length), max_wsize=max(df_topology$length),
                                 acc=acc$acc, rmse=acc$rmse, aic=sum(df_current$aic))

df_output <- rbind(df_now, df_dac)
data.table::fwrite(df_output, file=fn_acc, quote=FALSE, sep="\t")
```

```{r sumvisualisation}
if (nrow(smfile) > 1) {
  # convert the lengths into genomic positions
  mtfile_dist <- data.table::data.table(pos = seq(1, sum(mtfile$length)),
                                        len = rep(mtfile$length, times=mtfile$length),
                                        type = "mstrees")

  msfile_dist <- data.table::data.table(pos = seq(1, sum(msfile$length)),
                                        len = rep(msfile$length, times=msfile$length),
                                        type = "mstops")

  smfile_dist <- data.table::data.table(pos = seq(1, sum(smfile$length)),
                                        len = rep(smfile$length, times=smfile$length)
                                        type = "aic")

  # run linear model
  lm <- lm(smfile_dist$len ~ mtfile_dist$len+msfile_dist$len)
  lm_sum <- summary(lm)$coefficients

  # extract important values
  mt_est <- round(lm_sum["mtfile_dist$len", "Estimate"], 3)
  ms_est <- round(lm_sum["msfile_dist$len", "Estimate"], 3)

  mt_ste <- lm_sum["mtfile_dist$len", "Std. Error"]
  ms_ste <- lm_sum["msfile_dist$len", "Std. Error"]

  mt_p <- round(lm_sum["mtfile_dist$len", "Pr(>|t|)"], 3)
  ms_p <- round(lm_sum["msfile_dist$len", "Pr(>|t|)"], 3)

  r2 <- round(summary(lm)$r.squared, 3)

  # save the correlation result
  df_cor <- data.table::data.table(mstrees_est = mt_est, mstrees_ste = mt_ste, mstrees_p = mt_p,
                                  mstops_est = ms_est, mstops_ste = ms_ste, mstops_p = ms_p,
                                  R2 = r2)
  data.table::fwrite(df_cor, file=fn_corlm, quote=F, sep="\t")

  # combine all data.table
  df_dist <- data.table::as.data.table(rbind(mtfile_dist, msfile_dist, smfile_dist))
  df_dist$type <- factor(df_dist$type, levels=c("mstrees","mstops","aic"))

  # visualisation
  plot <- ggplot(df_dist, aes(x=pos, y=len, colour=type, xmin=0, xmax=max(df_dist$pos))) +
    geom_line(linewidth=2, alpha=0.8) +
    geom_hline(yintercept=as.numeric(best_wsize_aic), linewidth=2, linetype=5) +
    scale_y_log10(labels=scales::label_number(trim = TRUE, accuracy = NULL)) +
    scale_colour_manual(values=c("#619CFF","#00BA38", "#F8766D")) +
    xlab("Genome Position (bp)") + ylab("Block Length (bp)") +
    theme(
        axis.title.x=element_text(size=40),
        axis.title.y=element_text(size=40),
        axis.text.y=element_text(size=30),
        axis.text.x=element_text(size=30),
        strip.text=element_text(size=30),
        legend.title=element_text(size=30),
        legend.text=element_text(size=30),
        legend.key.size=unit(2,"cm")
      )

  tiff(filename=fn_windowdist_tiff, units="px", width=3840, height=1080)
  print(plot)
  dev.off()

  rm(mtfile_dist, msfile_dist, smfile_dist, df_dist)
}
```

```{r sumvisualisation-binned}
# transform data.frames into 1000 bins
n_bins <- 1000

# extract alignment length
total_length <- sum(msfile$length)
bin_edges <- round(seq(1, total_length+1, length.out=n_bins+1))

# divide the length distribution based on the bins
mtfile_dist <- lapply(1:n_bins, function(i) {
  bin_start <- bin_edges[i]
  bin_end <- bin_edges[i+1]-1

  f_bin_length_dist(mtfile, bin_start, bin_end, i)
})

msfile_dist <- lapply(1:n_bins, function(i) {
  bin_start <- bin_edges[i]
  bin_end <- bin_edges[i+1]-1
  
  f_bin_length_dist(msfile, bin_start, bin_end, i)
})

smfile_dist <- lapply(1:n_bins, function(i) {
  bin_start <- bin_edges[i]
  bin_end <- bin_edges[i+1]-1

  f_bin_length_dist(smfile, bin_start, bin_end, i)
})

# convert list to data.frame
mtfile_dist <- mtfile_dist %>% bind_rows() %>% mutate(bin_mid = (bin_start + bin_end) / 2, type="mstrees")
msfile_dist <- msfile_dist %>% bind_rows() %>% mutate(bin_mid = (bin_start + bin_end) / 2, type="mstops")
smfile_dist <- smfile_dist %>% bind_rows() %>% mutate(bin_mid = (bin_start + bin_end) / 2, type="aic")
df_dist <- rbind(mtfile_dist, msfile_dist, smfile_dist)
df_dist$type <- factor(df_dist$type, levels=c("mstrees","mstops","aic"))

# visualisation
plot <- ggplot(df_dist, aes(x=bin_mid, y=avg_length, colour=type, xmin=0, xmax=total_length)) +
  geom_line(linewidth=3, alpha=0.8) +
  geom_hline(yintercept=as.numeric(best_wsize_aic), linewidth=3, linetype=5) +
  scale_y_log10(labels=scales::label_number(trim = TRUE, accuracy = NULL)) +
  scale_colour_manual(values=c("#619CFF","#00BA38", "#F8766D")) +
  xlab("Genome Position (bp)") + ylab("Average Block Length (bp)") +
  theme(
      axis.title.x=element_text(size=40),
      axis.title.y=element_text(size=40),
      axis.text.y=element_text(size=30),
      axis.text.x=element_text(size=30),
      strip.text=element_text(size=30),
      legend.title=element_text(size=30),
      legend.text=element_text(size=30),
      legend.key.size=unit(2,"cm")
    )

tiff(filename=fn_windowdist_binned_tiff, units="px", width=1920, height=1080)
print(plot)
dev.off()
```