---
title: "Check Topology Distribution from ms"
params:
  # general
  prefix: "hl"
  outdir: "~/Documents/simulation/hl"
  nreps: 10
  thread: 5
  
  top_threshold: 0.985
  
  # ms
  msdir: "~/Documents/msdir/ms"
  ms_params: ""
  ms_r: 0
  ms_l: 10000000
---

```{r setup, include=FALSE}
library(doSNOW)

# create doSNOW cluster
nwcl <- makeCluster(params$thread)
doSNOW::registerDoSNOW(nwcl)
```

```{r ms, include=FALSE}
ms_command <- paste(params$ms_params, "-r", params$ms_r, params$ms_l)

lenout <- foreach (i = 1:params$nreps, .combine=c) %dopar% {
  library(data.table)
  library(dplyr)
  
  options(scipen=999)
  
  # analysis run
  prefix <- paste0(params$prefix, "_", i)
  
  # create directory
  currentdir <- paste0(params$outdir, "/", prefix, "/")
  if (!dir.exists(currentdir)) {
    dir.create(currentdir, recursive = T)
  }
  
  # output files
  fn_seedms <- paste0(currentdir, "seedms")
  fn_msfile <- paste0(currentdir, prefix, ".ms")
  fn_mstops <- paste0(currentdir, prefix, ".mstops")
  
  # generate seedms
  randseed <- paste(sample(10000:99999,3), collapse=" ")
  write.table(randseed, file=fn_seedms, quote=F, row.names=F, col.names=F)
  
  # generate msfile
  system(paste(params$msdir,ms_command,">",fn_msfile))
  
  # read msfile
  ms <- data.table::fread(fn_msfile, col.names="cmd", sep="")
  
  # extract ms trees
  mstrees <- ms[grepl("^\\[", cmd)]
  if (nrow(mstrees) == 0) {
    mstrees <- ms[grepl("^\\(.+\\);$", cmd)]
    mstrees[1, cmd := paste0("[", params$ms_l, "]", mstrees[1, cmd])]
  }
  
  # convert ms trees into data.table
  mstrees[, c("empty","length","tree") := data.table::tstrsplit(cmd, '\\[|\\]', fixed = FALSE)]
  mstrees[, c("cmd", "empty") := NULL]
  mstrees$length <- as.numeric(mstrees$length)
  
  # group by tree
  summary <- mstrees %>%
    group_by(tree) %>%
    summarise(n=n())
  summary <- data.table::as.data.table(summary)
  
  # store trees without branch lengths
  n <- nrow(summary)
  topology <- c()

  for (i in 1:n){
    temp_tree <- ape::read.tree(text=summary$tree[i])
    temp_tree$edge.length <- NULL
    topology <- c(topology, ape::write.tree(temp_tree))
  }
  summary[, "topology" := topology]
  summary$tree <- NULL
  
  # group by topology
  tsummary <- summary %>%
    group_by(topology) %>%
    summarise_all(sum)
  
  # extract unique topologies
  ls_unroot <- c()
  ls_uqtops <- c()
  uq_tops <- unique(tsummary$topology)
  
  for (i in uq_tops) {
    is_equal <- 0
    
    if (is.null(ls_unroot)) {
      ls_unroot <- c(ls_unroot, i)
      ls_uqtops <- c(ls_uqtops, i)
      next
    }
    
    for (j in ls_unroot) {
      if (ape::all.equal.phylo(ape::unroot(ape::read.tree(text = i)), ape::unroot(ape::read.tree(text = j)))) {
        is_equal <- 1
        ls_uqtops <- c(ls_uqtops, j)
        break
      }
    }
    
    if (is_equal == 0) {
      ls_unroot <- c(ls_unroot, i)
      ls_uqtops <- c(ls_uqtops, i)
    }
  }

  # group by topology
  tsummary <- data.table::as.data.table(tsummary)
  tsummary[, "utopology" := ls_uqtops]
  
  usummary <- tsummary %>%
    group_by(utopology) %>%
    summarise(n = sum(n), percentage = round(n/sum(tsummary$n) * 100, 5)) %>%
    arrange(-n) %>%
    mutate(cum.percentage = round(cumsum(n) / sum(tsummary$n), 5))
  
  sub_sum <- head(subset(usummary$cum.percentage, usummary$cum.percentage >= params$top_threshold), 1)
  sum_idx <- match(sub_sum, usummary$cum.percentage)
  
  data.table::fwrite(usummary, file=fn_mstops, quote=FALSE, sep="\t")
  
  list(list(nrow(mstrees),sum_idx))
}

stopCluster(nwcl)

# output
lenloci <- sapply(lenout, function(x){x[[1]]})
lentree <- sapply(lenout, function(x){x[[2]]})

write.table(c(paste("Average number of loci:", mean(lenloci)),
              paste0("Average number of topologies: ", mean(lentree), " (", round(sd(lentree),5), ")")),
            file = paste0(params$outdir, "/", params$prefix, ".mssum"),
            quote = FALSE, row.names = FALSE, col.names = FALSE)
```
