---
title: "Comparison of Topology Weights between Empirical and Simulated Datasets"
params:
  prefix: "hl"
  outdir: "~/Documents/simulation/debug/hl"
  
  wsize: 50000
  reftopdir: "~/Documents/simulation/sim_edelman/reftops.txt"
---

```{r setup, include=FALSE}
library(data.table)
library(dplyr)
library(ggplot2)

topdistdir <- paste0(params$outdir, "/topdist/")
if (!dir.exists(topdistdir)) {
  dir.create(topdistdir, recursive = T)
}
```

```{r distref, include=FALSE}
fn_mstopdist <- paste0(topdistdir, params$prefix, ".mstopdist")
fn_nwtopdist <- paste0(topdistdir, params$prefix, ".nwtopdist")

# extract simulations
allsims <- list.dirs(params$outdir, full.names = F, recursive = F)
simulation <- allsims[grep(paste0("^",params$prefix), allsims)]

# read reference topology
msreftop <- data.table::fread(params$reftopdir)
nwreftop <- copy(msreftop)
allreftop <- copy(msreftop)

rrate <- c("ref")
lnreftop <- nrow(msreftop)

for (i in simulation) {
  fn_cmptw <- paste0(params$outdir, "/", i, "/windows/", params$wsize, "/summary/", i, ".cmptw")
  if (!file.exists(fn_cmptw)) {
    print(paste0(params$prefix, " has no .cmptw file for ", params$wsize, "bp window"))
  }
  
  # read topology weights
  cmptw <- data.table::fread(fn_cmptw)
  mstempvalue <- c()
  nwtempvalue <- c()
  
  # retrieve weight for each topology
  for (j in 1:nrow(msreftop)) {
    for (k in 1:nrow(cmptw)) {
      is_comparable <- ape::all.equal.phylo(ape::unroot(ape::read.tree(text = msreftop$newick[j])),
                                            ape::unroot(ape::read.tree(text = cmptw$topology[k])))
      
      if (is_comparable) {
        cmptw$topology[k] <- msreftop$newick[j]
        
        ifelse(is.na(cmptw$ms[k]), mstempvalue <- c(mstempvalue, "NA"), mstempvalue <- c(mstempvalue, cmptw$ms[k]))
        ifelse(is.na(cmptw$now[k]), nwtempvalue <- c(nwtempvalue, "NA"), nwtempvalue <- c(nwtempvalue, cmptw$now[k]))
        break
      }
    }
    
    if (!is_comparable) {
      mstempvalue <- c(mstempvalue, "NA")
      nwtempvalue <- c(nwtempvalue, "NA")
    }
  }
  
  msreftop[, (i) := mstempvalue]
  nwreftop[, (i) := nwtempvalue]
  
  # rank based on cumulative percentage
  cmptw <- cmptw %>%
    arrange(-now)
  
  tempdt <- data.table::data.table(cmptw[1:lnreftop, topology], cmptw[1:lnreftop, now])
  data.table::setnames(tempdt, c("topology",i))
  
  allreftop <- data.table::merge.data.table(allreftop, tempdt,
                                            by.x = "newick", by.y = "topology",
                                            all.x = TRUE, all.y = TRUE)
  
  # extract recombination rate
  fn_ms <- paste0(params$outdir,"/",i,"/simulation/",i,".ms")
  command <- strsplit(system(paste("grep 'ms'",fn_ms), intern=T), " ")
  rrate <- c(rrate, as.numeric(command[[1]][length(command[[1]])-1]))
}

data.table::fwrite(msreftop, file=fn_mstopdist, quote=F, sep="\t")
data.table::fwrite(nwreftop, file=fn_nwtopdist, quote=F, sep="\t")

# comparison with ref topology
sub_output <- data.frame()
  
for (i in 1:nrow(nwreftop)) {
  for (j in 2:ncol(nwreftop)) {
    sub_output <- rbind(sub_output, c(nwreftop$newick[i],
                                      colnames(nwreftop)[j],
                                      as.character(nwreftop[i, ..j]),
                                      rrate[j-1]))
  }
}
colnames(sub_output) <- c("newick","simulation","weight","r")
sub_output$simulation <- forcats::fct_inorder(factor(sub_output$simulation))

uq_r <- subset(unique(sub_output$r), unique(sub_output$r) != "ref")

for (i in uq_r) {
  fn_topdist_fig <- paste0(topdistdir, params$prefix, ".topdist.r",i,".tiff")
  outperr <- subset(sub_output, sub_output$r == i | sub_output$r == "ref")
  
  tiff(filename=fn_topdist_fig, units="px", width=2880, height=1800)
  print(ggplot(outperr, aes(y=as.numeric(weight), x=simulation, ymin=0, ymax=100, fill=newick)) + 
          geom_bar(position="stack", stat="identity") +
          ggtitle("Comparison of NOW Topology Weights between Empirical and Simulated Datasets") +
          xlab("Simulation") +
          ylab("Topology weights") +
          theme(
            plot.title = element_text(hjust = 0.5, size = 50),
            plot.margin = margin(1.25, 0, 1.25, 0, "cm"),
            axis.title.x=element_text(size = 40, margin = margin(t=20, r=0, b=0, l=0)),
            axis.title.y=element_text(size = 40, margin = margin(t=0, r=20, b=0, l=0)),
            axis.text.y=element_text(size=30),
            axis.text.x=element_text(size=30),
            legend.title=element_text(size=30),
            legend.text=element_text(size=30),
            legend.key.size=unit(2,"cm")
          ))
  dev.off()
}

# top topologies for each recombination rate
sub_output <- data.frame()
  
for (i in 1:nrow(allreftop)) {
  for (j in 2:ncol(allreftop)) {
    sub_output <- rbind(sub_output, c(allreftop$newick[i],
                                      colnames(allreftop)[j],
                                      as.character(allreftop[i, ..j]),
                                      rrate[j-1]))
  }
}
colnames(sub_output) <- c("newick","simulation","weight","r")
sub_output$simulation <- forcats::fct_inorder(factor(sub_output$simulation))

for (i in uq_r) {
  fn_toptops_fig <- paste0(topdistdir, params$prefix, ".toptops.r",i,".tiff")
  outperr <- subset(sub_output, sub_output$r == i | sub_output$r == "ref")
  
  tiff(filename=fn_toptops_fig, units="px", width=2880, height=1800)
  print(ggplot(outperr, aes(y=as.numeric(weight), x=simulation, ymin=0, ymax=100, fill=newick)) + 
          geom_bar(position="stack", stat="identity") +
          ggtitle(paste("Top", lnreftop, "Topologies in Empirical and Simulated Datasets")) +
          xlab("Simulation") +
          ylab("Topology weights") +
          theme(
            plot.title = element_text(hjust = 0.5, size = 50),
            plot.margin = margin(1.25, 0, 1.25, 0, "cm"),
            axis.title.x=element_text(size = 40, margin = margin(t=20, r=0, b=0, l=0)),
            axis.title.y=element_text(size = 40, margin = margin(t=0, r=20, b=0, l=0)),
            axis.text.y=element_text(size=30),
            axis.text.x=element_text(size=30),
            legend.title=element_text(size=30),
            legend.text=element_text(size=30),
            legend.key.size=unit(2,"cm")
          ))
  dev.off()
}
```