---
title: "Check Locus Length Distribution from ms"
params:
  prefix: "hl"
  outdir: "~/Documents/simulation/hl"
---

```{r setup, include=FALSE}
library(data.table)
library(ggplot2)
```

```{r ms, include=FALSE}
options(scipen = 999)

# extract simulations
allsims <- list.dirs(params$outdir, full.names = F, recursive = F)
simulation <- allsims[grep(paste0("^",params$prefix), allsims)]

locuslen <- c()

for (s in simulation) {
  fn_msfile <- paste0(params$outdir, "/", s, "/simulation/", s, ".ms")
  command <- strsplit(system(paste("grep 'ms'",fn_msfile), intern=T), " ")
  
  # extract ms params
  rho <- as.numeric(command[[1]][length(command[[1]])-1])
  ms_l <- as.numeric(command[[1]][length(command[[1]])])
  
  # read msfile
  ms <- data.table::fread(fn_msfile, col.names="cmd", sep="")
  
  # extract ms trees
  mstrees <- ms[grepl("^\\[", cmd)]
  if (nrow(mstrees) == 0) {
    mstrees <- ms[grepl("^\\(.+\\);$", cmd)]
    mstrees[1, cmd := paste0("[", ms_l, "]", mstrees[1, cmd])]
  }
  
  # convert ms trees into data.table
  mstrees[, c("empty","length","tree") := data.table::tstrsplit(cmd, '\\[|\\]', fixed = FALSE)]
  
  for (l in mstrees$length) {
    locuslen <- rbind(locuslen, c(s, as.numeric(l)/1000, rho))
  }
}

locuslen <- as.data.frame(locuslen)
colnames(locuslen) <- c("simulation","length","rho")
locuslen$length <- as.numeric(locuslen$length)

# write output file
fn_file <- paste0(params$outdir, "/", params$prefix, ".loclen")
write.csv(c("r","mean","sd"), file=fn_file, quote=F, row.names=F, col.names=F, append=T, sep="\t")

#visualization
for (r in unique(locuslen$rho)) {
  fn_fig <- paste0(params$outdir, "/", params$prefix, ".r", r, "loclen.tiff")
  
  outperr <- subset(locuslen, locuslen$rho == r)
  write.csv(c(r, round(mean(outperr$length),5), round(sd(outperr$length),5)),
            file=fn_file, quote=F, row.names=F, col.names=F, append=T, sep="\t")
  
  lenbin <- ceiling(sqrt(nrow(outperr)))
  widthbin <- (max(outperr$length) - min(outperr$length)) / lenbin
  
  tiff(filename=fn_fig, units="px", width=2880, height=1800)
  print(ggplot(outperr, aes(x=length, fill=simulation)) +
    geom_histogram(binwidth=widthbin, alpha=.5, position="identity") +
    ggtitle(paste0("Distribution of locus length (bin width = ", round(widthbin, 5), ")")) +
    xlab("Length (kb)") +
    ylab("Count") +
    theme(
        plot.title = element_text(hjust = 0.5, size = 50),
        plot.margin = margin(1.25, 1.25, 1.25, 0.25, "cm"),
        axis.title.x=element_text(size = 40, margin = margin(t=20, r=0, b=0, l=0)),
        axis.title.y=element_text(size = 40, margin = margin(t=0, r=20, b=0, l=0)),
        axis.text.y=element_text(size=30),
        axis.text.x=element_text(size=30),
        legend.position = "none"
      ))
  dev.off()
}
```