---
title: "Sequence Simulation using ms and AliSim"
output:
  html_document:
    code_folding: show

params:
  # general
  codedir: "~/SimNOW/codes"
  prefix: "sim"
  outdir: "~/simulation"
  redo: TRUE
  
  # ms
  msdir: "~/msdir/ms"
  ms_params: ""
  ms_r: 0
  ms_l: 1000000
  
  # AliSim
  iqtree2dir: "~/iqtree-2.2.2.4-MacOSX/bin/iqtree2"
  alisim_model: "JC"
  alisim_scale: 0.001
  
  copy_gaps: TRUE
  src_aln: "~/empirical_aln.fa"
---

## Load required libraries and functions
```{r}
source(paste0(params$codedir, "/", "1_sequence_simulation/functions.R"))

library(data.table)
library(dplyr)
```

```{r, include=FALSE}
# store initial system time
sys_tic <- Sys.time()

# create outdir
currentdir <- paste0(params$outdir, "/", params$prefix)
if (!dir.exists(currentdir)) {
  dir.create(currentdir, recursive = T)
}

# create log file
fn_log <- paste0(params$outdir, "/", params$prefix, "/", params$prefix, ".log")
log_appender <- log4r::file_appender(fn_log, append = TRUE, layout = log4r::default_log_layout())
fn_logger <- log4r::logger(threshold = "INFO", appenders = log_appender)
if (params$redo) {
  unlink(fn_log)
  write.table("SimNOW", file=fn_log, quote=F, row.names=F, col.names=F)
}

knitr::opts_knit$set(root.dir = currentdir)
```

```{r simulation-setup, include=FALSE}
write.table(c("",
              "####################################",
              "####     Sequence Simulation    ####",
              "####################################"),
            file=fn_log, quote=F, row.names=F, col.names=F, append=T)

# create simulation dir
simulation_outdir <- paste0(getwd(), "/simulation")
if (!dir.exists(simulation_outdir)) {
  dir.create(simulation_outdir, recursive = T)
}

# input/output files
fn_msfile <- paste0(simulation_outdir, "/", params$prefix, ".ms")
fn_mstrees <- paste0(simulation_outdir, "/", params$prefix, ".mstrees")
fn_mttrees <- paste0(simulation_outdir, "/", params$prefix, ".multitree")
fn_mstops <- paste0(simulation_outdir, "/", params$prefix, ".mstops")
fn_uqtops <- paste0(simulation_outdir, "/", params$prefix, ".uqtops")

fn_nexus <- paste0(simulation_outdir, "/", params$prefix, ".nex")
fn_alisim <- paste0(simulation_outdir, "/", params$prefix)
fn_alisim_fa <- paste0(simulation_outdir, "/", params$prefix, ".fa")

if (params$copy_gaps) {
  fn_alisim <- paste0(fn_alisim, "_nogaps")
}
```

## Simulation of locus trees using ms
### Running ms
```{r ms}
write.table(c("",
              "---------------- ms ----------------"),
              file=fn_log, quote=F, row.names=F, col.names=F, append=T)

# prevent the use of scientific notation for big numbers
options(scipen=999)

# generate random seeds for ms
randseed <- paste(sample(10000:99999,3), collapse=" ")

# combine all ms parameters into one variable
ms_command <- paste(params$ms_params, "-r", params$ms_r, params$ms_l, "-seeds", randseed)

# generate msfile
if (file.exists(fn_msfile) && !params$redo) {
  log4r::info(fn_logger, paste0("File found: ", params$prefix, "ms."))
} else {
  system(paste(params$msdir,ms_command,">",fn_msfile))
  log4r::info(fn_logger, paste0("File created: ", params$prefix, ".ms."))
}
```

### Extracting locus trees and topologies from ms file
```{r}
# mstrees
summary <- f_extract_locus_tree(fn_msfile, params$ms_l)
head(summary)

# mstops
t_summary <- f_extract_locus_topology(summary)
head(t_summary)
```

```{r postms, include=FALSE}
options(scipen=999)

if (all(file.exists(fn_mstrees, fn_mttrees, fn_mstops, fn_uqtops)) && !params$redo) {
  log4r::info(fn_logger, "File found: ms summary files.")
  
} else {
  # save the ms summary files
  data.table::fwrite(summary, file=fn_mstrees, sep="\t", quote=F)
  write.table(summary$tree, file=fn_mttrees, sep="\t", quote=F, row.names=F, col.names=F)
  log4r::info(fn_logger, paste0(nrow(summary), " tree partition(s) found. File created: ",
                               params$prefix, ".mstrees and ", params$prefix, ".multitree"))
  
  data.table::fwrite(t_summary, file=fn_mstops, sep="\t", quote=F)
  write.table(unique(t_summary$topology), file=fn_uqtops, sep="\t", quote=F, row.names=F, col.names=F)
  log4r::info(fn_logger, paste0(nrow(t_summary), " topology partition(s) found. File created: ", 
                               params$prefix, ".mstops and ", params$prefix, ".uqtops"))
}
```

## Simulation of FASTA alignment using AliSim
```{r prealisim, include=FALSE}
if (file.exists(fn_nexus) && !params$redo) {
  log4r::info(fn_logger, paste0("File found: ", params$prefix, ".nex."))
  
} else {
  # extract the boundary of each tree
  res <- lapply(1:nrow(summary), function(i) {
    paste0("    charset gene_",i," = DNA, ",summary$start[i],"-",summary$stop[i],";")
  })
  
  # store the header and footer of nexus file
  nexus_lines <- c("#nexus", "begin sets;", unlist(res), "end;")
  
  # write the nexus file
  fileConn <- file(fn_nexus)
  writeLines(nexus_lines, fileConn)
  close(fileConn)
  
  log4r::info(fn_logger, paste0("File created: ", params$prefix, ".nex."))
}
```

### Running AliSim
```{r alisim}
write.table(c("",
              "-------------- AliSim --------------"),
              file=fn_log, quote=F, row.names=F, col.names=F, append=T)
              
if (file.exists(fn_alisim_fa) && !params$redo) {
  log4r::info(fn_logger, paste0("File found: ", params$prefix, ".fa."))
  
} else {
  iqtree_cmd <- paste(params$iqtree2dir,
                      "--alisim", fn_alisim,
                      "-Q", fn_nexus,
                      "-t", fn_mttrees,
                      "-m", params$alisim_model,
                      "--length", params$ms_l,
                      "--branch-scale", params$alisim_scale,
                      "-T 1 -af fasta -cptime 1000000 -redo --no-log")
  system(iqtree_cmd)
  
  # add gaps
  if (params$copy_gaps) {
    output <- f_copy_gaps(paste0(fn_alisim, ".fa"), params$src_aln)

    if (!is.null(output$err)) {
      log4r::error(fn_logger, output$err)
      stop(output$err)
    }
    
    seqinr::write.fasta(sequences=output$seq, names=names(output$seq), file.out=fn_alisim_fa)
  }
  
  log4r::info(fn_logger, paste0("File created: ", params$prefix, ".fa."))
}
```

```{r, include=FALSE}
# store final system time
sys_toc <- Sys.time()

# write the system time in log file
write.table(c("", paste0("Total elapsed time: ", round(as.numeric(difftime(sys_toc, sys_tic, units = "mins")), 3), " mins")),
            file=fn_log, quote=F, row.names=F, col.names=F, append=T)
```