---
title: "Stepwise NOW for Empirical Dataset"
---

```{r nowsetup, include=FALSE}
write.table(c("",
              "####################################",
              "####         NOW Analysis       ####",
              "####################################"),
            file=fn_log, quote=F, row.names=F, col.names=F, append=T)

# output file
fn_summary <- paste0(getwd(), "/", params$prefix, ".sumtable")

# check input parameters
if (params$initial_wsize <= 0 || params$initial_wsize%%2 != 0) {
  log4r::error(fn_logger, "Error: invalid starting window size. Exited.")
}

if (!is.null(params$bootstrap_type) && params$bootstrap_type != "") {
  bs_type <- tolower(params$bootstrap_type)

  if (bs_type == "ufboot" && params$bootstrap < 1000) {
    log4r::error(fn_logger, "Error: invalid number of bootstrap for UFBoot. Exited.")
  } else if (bs_type == "nonparametric" && params$bootstrap < 100) {
    log4r::error(fn_logger, "Error: invalid number of bootstrap for non-parametric bootstrap. Exited.")
  }
}

min_branch_support <- 80
if (tolower(params$bootstrap_type) == "ufboot") {
  min_branch_support <- 95
}
```

```{r window-size, include=FALSE}
write.table(c("",
              "---------- Window Alignment --------"),
              file=fn_log, quote=F, row.names=F, col.names=F, append=T)

options(scipen=999)

# extract window sizes based on the initial size
max_wsize <- params$initial_wsize
wsizes <- max_wsize
while (max_wsize %% 2 == 0) {
  wsizes <- c(wsizes, max_wsize / 2)
  max_wsize <- max_wsize / 2
}
wsizes <- sort(wsizes, decreasing=T)

# set number of thread based on the number of window sizes
stepthread <- params$thread
if (stepthread > length(wsizes)-1) {
  stepthread <- length(wsizes)-1
}

# read fasta file
s <- seqinr::read.fasta(params$input_aln, whole.header = T)
len_taxa <- length(s)

# get length of the alignment
s_ln <- seqinr::getLength(s)[1]
write.table(paste0("Number of sites: ", s_ln, "bp"),
            file=fn_log, quote=F, row.names=F, col.names=F, append=T)

# update the alignment to be divisible by the initial window size
s_ln_new <- floor(s_ln/params$initial_wsize) * params$initial_wsize

s <- lapply(s, function(x) x[seq(from = 1, to = s_ln_new)])
s <- do.call(rbind, s)
s <- setNames(split(s, seq(nrow(s))), rownames(s))
write.table(paste0("Updated number of sites: ", s_ln_new, "bp"),
            file=fn_log, quote=F, row.names=F, col.names=F, append=T)
```

```{r window-aln, include=FALSE}
options(scipen=999)

########################################### LONG ############################################
# create outdir
dir_long <- paste0(getwd(), "/1/", wsizes[1], "/")
dir_perwindow <- paste0(dir_long, "perwindow/")
if (!dir.exists(dir_perwindow)) {
  dir.create(dir_perwindow, recursive = T)
}

# check if alignments already exist
numw <- s_ln_new/wsizes[1]
if (length(list.files(dir_perwindow, pattern='*.fa', recursive=FALSE)) == numw && !params$redo) {
  log4r::info(fn_logger, paste0("File found: ", wsizes[1], "bp window alignments for step 1."))
} else {
  fn_output <- paste0(dir_long, wsizes[1], ".perwindowsum")

  # generate window alignments
  df_output <- f_perwindow_run(dir_perwindow, wsizes[1], numw, s, len_taxa, params$min_informative_sites)
  data.table::fwrite(df_output, fn_output, quote=FALSE, sep="\t")

  log4r::info(fn_logger, paste0("File created: ", wsizes[1], "bp per-window alignments for step 1."))
}

########################################## SHORT ############################################
# create doSNOW cluster
nwcl <- makeCluster(stepthread)
doSNOW::registerDoSNOW(nwcl)

# window alignments for shorter window size
foreach (i = 1:(length(wsizes)-1)) %dopar% {
  options(scipen=999)

  # create outdir
  dir_short <- paste0(getwd(), "/", i, "/", wsizes[i+1], "/")
  dir_perwindow <- paste0(dir_short, "perwindow/")
  if (!dir.exists(dir_perwindow)) {
    dir.create(dir_perwindow, recursive = T)
  }

  # check if files already exist
  numw <- s_ln_new/wsizes[i+1]
  if (length(list.files(dir_perwindow, pattern='*.fa', recursive=FALSE)) == numw && !params$redo) {
    log4r::info(fn_logger, paste0("File found: ", wsizes[i+1], "bp window alignment for step ", i, "."))
  } else {
    fn_output <- paste0(dir_short, wsizes[i+1], ".perwindowsum")

    # generate window alingments
    df_output <- f_perwindow_run(dir_perwindow, wsizes[i+1], numw, s, len_taxa, params$min_informative_sites)
    data.table::fwrite(df_output, fn_output, quote=FALSE, sep="\t")

    log4r::info(fn_logger, paste0("File created: ", wsizes[i+1], "bp per-window alignments for step ", i, "."))
  }
}

stopCluster(nwcl)
rm(s)
```

```{r window-filter, include=FALSE}
# create doSNOW cluster
nwcl <- makeCluster(stepthread)
doSNOW::registerDoSNOW(nwcl)

foreach (i = 1:(length(wsizes)-1)) %dopar% {
  # input files
  fn_short <- paste0(getwd(), "/", i, "/", wsizes[i+1], "/", wsizes[i+1], ".perwindowsum")
  fn_long <- ""
  if (i == 1) {
    fn_long <- paste0(getwd(), "/", i, "/", wsizes[i], "/", wsizes[i], ".perwindowsum")
  } else {
    fn_long <- paste0(getwd(), "/", i-1, "/", wsizes[i], "/", wsizes[i], ".perwindowsum")
  }

  if (!all(file.exists(fn_long, fn_short))) {
    log4r::warn(fn_logger, paste0("File not found: .perwindowsum file(s) for step ", i, ". Skipped."))
    return(NULL)
  }
  
  # open input files
  df_long <- data.table::fread(fn_long)
  df_short <- data.table::fread(fn_short)

  ########################################### LONG ############################################
  # check which window is uninformative
  long_uninformative_idx <- c()
  for (j in 1:nrow(df_short)) {
    if (!df_short$is_informative[j]) {
      uninformative_idx <- which(df_long$start <= df_short$start[j] & df_long$end >= df_short$end[j])
      long_uninformative_idx <- c(long_uninformative_idx, uninformative_idx)
    }
  }
  long_uninformative_idx <- unique(long_uninformative_idx)

  # remove uninformative windows
  long_names <- df_long$name
  if (length(long_uninformative_idx) != 0){
    long_names <- df_long$name[-long_uninformative_idx]
  }
  
  # create outdir
  long_path <- paste0(getwd(), "/", i, "/", wsizes[i], "/filtered/")
  if (!dir.exists(long_path)) {
    dir.create(long_path, recursive=TRUE)
  }

  # check if files already exist
  if (length(list.files(long_path, pattern='*.fa$', recursive=TRUE)) == length(long_names) && !params$redo) {
    log4r::info(fn_logger, paste0("File found: ", wsizes[i], "bp filtered windows for Step", i, "."))

  } else {
    # iteration to copy the alignment
    for (j in long_names) {
      fn_path <- NULL 
      if (i == 1) {
        fn_path <- paste0(getwd(), "/", i, "/", wsizes[i], "/perwindow/", j, ".fa")
      } else {
        fn_path <- paste0(getwd(), "/", i-1, "/", wsizes[i], "/perwindow/", j, ".fa")
      }

      temp_path <- paste0(long_path, j, "/")
      if (!dir.exists(temp_path)) {
        dir.create(temp_path)
      }

      system(paste("cp", fn_path, temp_path))
    }
  }

  ########################################### SHORT ###########################################
  # check which window is uninformative
  short_uninformative_idx <- c()
  for (j in long_uninformative_idx) {
    uninformative_idx <- which(df_short$start >= df_long$start[j] & df_short$end <= df_long$end[j])
    short_uninformative_idx <- c(short_uninformative_idx, uninformative_idx)
  }
  short_uninformative_idx <- unique(short_uninformative_idx)

  # remove uninformative windows
  short_names <- df_short$name
  if (length(short_uninformative_idx) != 0){
    short_names <- df_short$name[-short_uninformative_idx]
  }

  # create outdir
  short_path <- paste0(getwd(), "/", i, "/", wsizes[i+1], "/filtered/")
  if (!dir.exists(short_path)) {
    dir.create(short_path, recursive=TRUE)
  }

  # check if files already exist
  if (length(list.files(short_path, pattern='*.fa$', recursive=TRUE)) == length(short_names) && !params$redo) {
    log4r::info(fn_logger, paste0("File found: ", wsizes[i+1], "bp filtered windows for Step", i, "."))
    return(NULL)
  }

  # iteration to copy the alignment
  for (j in short_names) {
    fn_path <- paste0(getwd(), "/", i, "/", wsizes[i+1], "/perwindow/", j, ".fa")

    temp_path <- paste0(short_path, j, "/")
    if (!dir.exists(temp_path)) {
      dir.create(temp_path)
    }

    system(paste("cp", fn_path, temp_path))
  }

  log4r::info(fn_logger, paste("File created: Step", i, "window filtering."))
}

stopCluster(nwcl)
```

```{r window-tree, include=FALSE}
write.table(c("",
              "------------ Window Tree -----------"),
              file=fn_log, quote=F, row.names=F, col.names=F, append=T)

options(scipen=999)

# iterate through window sizes
for (i in 1:(length(wsizes)-1)) {
  ########################################### LONG ############################################
  long_path <- paste0(getwd(), "/", i, "/", wsizes[i], "/filtered/")

  # check input alignments
  dirs <- list.dirs(long_path, full.names = F, recursive = F)
  dirs <- dirs[grepl("^window", dirs)]

  # create doSNOW cluster
  nwcl <- makeCluster(params$thread)
  doSNOW::registerDoSNOW(nwcl)
  
  foreach (j = dirs) %dopar% {
    windowdir <- paste0(long_path, j, "/")
    fastadir <- paste0(windowdir, j, ".fa")

    # check if files exist
    iqtreefile <- paste0(windowdir, j, ".fa.iqtree")
    treefile <- paste0(windowdir, j, ".fa.treefile")
    if (all(file.exists(iqtreefile, treefile)) && !params$redo) {
      return(NULL)
    }
    
    iqtreefile <- paste0(getwd(), "/", i-1, "/", wsizes[i], "/filtered/", j, "/", j, ".fa.iqtree")
    treefile <- paste0(getwd(), "/", i-1, "/", wsizes[i], "/filtered/", j, "/", j, ".fa.treefile")
    if (all(file.exists(iqtreefile, treefile))) {
      system(paste("cp", iqtreefile, windowdir))
      system(paste("cp", treefile, windowdir))
    } else {
      f_iqtree2_single(fastadir, params$outgroup, params$set_blmin, params$set_model, params$dna_model, params$bootstrap_type, params$bootstrap, params$iqtree2dir)

      # check if bootstrap is useless
      logfile <- paste0(windowdir, j, ".fa.log")
      err_msg <- suppressWarnings(system(paste("grep '.*It makes no sense to perform bootstrap with less than 4 sequences*'", logfile), intern=T))

      if (length(err_msg) != 0) {
        f_iqtree2_single(fastadir, params$outgroup, params$set_blmin, params$set_model, params$dna_model, "", 0, params$iqtree2dir)
      }
    }
  }

  stopCluster(nwcl)

  ########################################### SHORT ###########################################
  short_path <- paste0(getwd(), "/", i, "/", wsizes[i+1], "/filtered/")

  # check input alignments
  dirs <- list.dirs(short_path, full.names = F, recursive = F)
  dirs <- dirs[grepl("^window", dirs)]
  
  # create doSNOW cluster
  nwcl <- makeCluster(params$thread)
  doSNOW::registerDoSNOW(nwcl)

  foreach (j = dirs) %dopar% {
    fastadir <- paste0(short_path, j, "/", j, ".fa")

    iqtreefile <- paste0(short_path, j, "/", j, ".fa.iqtree")
    treefile <- paste0(short_path, j, "/", j, ".fa.treefile")
    if (all(file.exists(iqtreefile, treefile)) && !params$redo) {
      return(NULL)
    }

    f_iqtree2_single(fastadir, params$outgroup, params$set_blmin, params$set_model, params$dna_model, params$bootstrap_type, params$bootstrap, params$iqtree2dir)

    # check if bootstrap is useless
    logfile <- paste0(fastadir, ".log")
    err_msg <- suppressWarnings(system(paste("grep '.*It makes no sense to perform bootstrap with less than 4 sequences*'", logfile), intern=T))

    if (length(err_msg) != 0) {
      f_iqtree2_single(fastadir, params$outgroup, params$set_blmin, params$set_model, params$dna_model, "", 0, params$iqtree2dir)
    }
  }

  stopCluster(nwcl)
  log4r::info(fn_logger, paste("File created: Step", i, "window treefile."))
}
```

```{r nowsummary, include=FALSE}
options(scipen=999)

if (file.exists(fn_summary)) {
  log4r::info(fn_logger, "File found: summary of stepwise non-overlapping windows.")

} else {
  df_output <- data.table::data.table(step=numeric(),
                          l_wsize=numeric(), s_wsize=numeric(),
                          l_aic=numeric(), s_aic=numeric(), diff_aic=numeric(),
                          fasta_ln=numeric(), fasta_ln_percent=numeric(),
                          l_bs_tree=numeric(), l_bs_topology=numeric(), s_bs_tree=numeric(), s_bs_topology=numeric()
                          )

  # create doSNOW cluster
  nwcl <- makeCluster(params$thread)
  doSNOW::registerDoSNOW(nwcl)

  # iterate through window sizes
  for (i in 1:(length(wsizes)-1)) {
    ########################################### LONG ############################################
    long_path <- paste0(getwd(), "/", i, "/", wsizes[i], "/filtered/")
    dirs <- list.dirs(long_path, full.names = F, recursive = F)
    dirs <- dirs[grepl("^window", dirs)]

    # extract alignment length
    s_ln_step <- length(dirs) * wsizes[i]

    # extract statistics for each window
    long_windows <- foreach(j = dirs, .combine=c) %dopar% {
      iqtree_path <- paste0(long_path, j, "/", j, ".fa.iqtree")
      treefile_path <- paste0(long_path, j, "/", j, ".fa.treefile")

      if (!all(file.exists(iqtree_path, treefile_path))) {
        log4r::error(fn_logger, paste0("File not found: .treefile or .iqtree for ", j, " in Step ", i, ". Exited."))
        knitr::knit_exit()
      }

      out <- f_window_tree_statistics(iqtree_path, treefile_path, params$bootstrap_type, min_branch_support)
      return(list(list(out$logl, out$freeparams, out$tree)))
    }
    
    # extract the summary of all windows
    fn_uqtops <- paste0(getwd(), "/", i, "/", wsizes[i], "/", wsizes[i], ".uqtops")
    long_output <- f_window_trees_summary(long_windows, fn_uqtops)

    ########################################### SHORT ###########################################
    short_path <- paste0(getwd(), "/", i, "/", wsizes[i+1], "/filtered/")
    dirs <- list.dirs(short_path, full.names = F, recursive = F)
    dirs <- dirs[grepl("^window", dirs)]

    # double check the alignment length
    if (s_ln_step != length(dirs) * wsizes[i+1]) {
      log4r::error(fn_logger, paste0("Error: different alignment lengths on Step", i, "."))
    }

    # extract statistics for each window
    short_windows <- foreach(j = dirs, .combine=c) %dopar% {
      iqtree_path <- paste0(short_path, j, "/", j, ".fa.iqtree")
      treefile_path <- paste0(short_path, j, "/", j, ".fa.treefile")

      if (!all(file.exists(iqtree_path, treefile_path))) {
        log4r::error(fn_logger, paste0("File not found: .treefile or .iqtree for ", j, " in Step ", i, ". Exited."))
        knitr::knit_exit()
      }

      out <- f_window_tree_statistics(iqtree_path, treefile_path, params$bootstrap_type, min_branch_support)
      return(list(list(out$logl, out$freeparams, out$tree)))
    }

    # extract the summary of all windows
    fn_uqtops <- paste0(getwd(), "/", i, "/", wsizes[i+1], "/", wsizes[i+1], ".uqtops")
    short_output <- f_window_trees_summary(short_windows, fn_uqtops)

    ########################################## SUMMARY ##########################################
    df_output <- rbind(df_output,
                      list(step=i,l_wsize=wsizes[i],s_wsize=wsizes[i+1],
                          l_aic=long_output$aic, s_aic=short_output$aic, diff_aic=short_output$aic-long_output$aic,
                          fasta_ln=s_ln_step, fasta_ln_percent=round((s_ln_step/s_ln)*100,3),
                          l_bs_tree=length(long_output$tree), l_bs_topology=length(unique(long_output$tree)),
                          s_bs_tree=length(short_output$tree), s_bs_topology=length(unique(short_output$tree))),
                      fill=TRUE)
    log4r::info(fn_logger, paste0("Summary added: Step ", i, "."))
  }

  stopCluster(nwcl)

  data.table::fwrite(df_output, fn_summary, quote=FALSE, sep="\t")
  log4r::info(fn_logger, "File created: summary file.")
}

```

```{r child = paste0(params$codedir,"/stepwise_now/3_summary.Rmd")}
```