---
title: "Two-window MAST-HMM from NOW"
---

```{r setup, include=FALSE}
write.table(c("",
                "####################################",
                "####     Two-Window HiMAST      ####",
                "####################################"),
              file=fn_log, quote=F, row.names=F, col.names=F, append=T)

# output directory for HiMAST-based windows
dir_output_windows <- paste0(logdir, "windows/")
if (!dir.exists(dir_output_windows)) {
  dir.create(dir_output_windows, recursive=T)
}

# output directory for concatenated sequences
dir_output_runs <- paste0(logdir, "runs/")
if (!dir.exists(dir_output_runs)) {
  dir.create(dir_output_runs, recursive=T)
}

# temporary output directory
dir_output_tmp <- paste0(logdir, "tmp/")
if (!dir.exists(dir_output_tmp)) {
  dir.create(dir_output_tmp, recursive=T)
}

# tree output directory
dir_output_tree <- paste0(logdir, "tree/")
if (!dir.exists(dir_output_tree)) {
  dir.create(dir_output_tree, recursive=T)
}

# delete all files
if (params$redo) {
  unlink(paste0(dir_output_windows, "*.fa"))
  unlink(paste0(dir_output_runs, "*"), recursive = T)
  unlink(paste0(dir_output_tmp, "*.fa"))
}

# variables
mast_model <- paste0("'", params$mast_model, "'")
ic_type <- tolower(params$ic_type)

# input files
fn_mstops <- paste0(getwd(), "/simulation/", params$prefix, ".mstops")
fn_summary <- paste0(getwd(), "/windows/", params$prefix, ".sum")

# output files
fn_wh_atsum <- paste0(logdir, params$prefix, ".wh.atsum")
fn_wh_cmp <- paste0(logdir, params$prefix, ".wh.cmp")
```

```{r run, include=FALSE}
options(scipen=9999)

# read summary file
sum <- data.table::fread(fn_summary)
if (!ic_type %in% colnames(sum)) {
  errmsg <- "Error: invalid information criterion type. Exited."
  
  log4r::error(fn_logger, errmsg)
  stop(errmsg)
}

# select window size according to the lowest IC
wsize <- sum %>%
  slice_min(!!as.name(ic_type))

if (nrow(wsize) != 1) {
  log4r::warn(fn_logger, paste("Warn: identical", toupper(ic_type), "is found in >1 window size.", wsize$window_size[1], "is selected."))
}

# update variables
fn_atsum <- paste0(getwd(), "/windows/", wsize$window_size[1], "/summary/", params$prefix, ".atsum")
dir_fasta <- paste0(getwd(), "/windows/", wsize$window_size[1], "/alignment/")

# read atsum file
atsum <- data.table::fread(fn_atsum)
p <- nrow(atsum)

if (length(unique(atsum$topology)) == 1) {
  errmsg <- "Error: only one topology found. Exited."
  
  log4r::error(fn_logger, errmsg)
  stop(errmsg)
}

# output data.table
dt_output <- data.table::data.table(source = character(),
                                    start = numeric(),
                                    stop = numeric(),
                                    length = numeric(),
                                    topology = character())

# initialize variables
current_topology <- ""
current_length <- ""
current_start <- 0

# run
for (i in 1:p) {
  fn_current_fasta <- paste0(dir_output_tmp, atsum$source[i])
  
  # check the window from previous run 
  if (file.exists(fn_current_fasta)) {
    # save the last window and check if the windows have the same topology
    if (i == p || current_topology == atsum$topology[i+1]) {
      # copy the file to other folder
      system(paste0("mv ", fn_current_fasta, " ", dir_output_windows))
      
      # add entry to output data.table
      dt_output <- rbind(dt_output, list(atsum$source[i],
                                      current_start+1,
                                      current_start+current_length,
                                      current_length,
                                      current_topology))
      
      # update variables
      current_start <- current_start + current_length
      next
    
    } else {
      # create output directory for the run
      dir_run <- paste0(dir_output_runs, i, "/")
      if (!dir.exists(dir_run)) {
        dir.create(dir_run)
      }
      
      # run seqkit to concat the sequences
      seq1 <- paste0(dir_output_tmp, "/", atsum$source[i])
      seq2 <- paste0(dir_fasta, "/", atsum$source[i+1])
      fn_alignment <- paste0(dir_run, "concat_", i, ".fa")
      run_seqkit(seq1, seq2, params$seqkitdir, fn_alignment)
      
      # topology file
      fn_topology <- paste0(dir_run, paste0("topology_", i, ".txt"))
      ls_topology <- c(current_topology, atsum$topology[i+1])
      write.table(ls_topology, file = fn_topology, quote = F, row.names = F, col.names = F)
      
      # run HiMAST
      seqlength <- seqinr::getLength(seqinr::read.fasta(fn_alignment))[1]
      run_himast(fn_alignment, fn_topology, 1/seqlength, mast_model, params$masthmmdir)
      
      # check if HMM file exists
      fn_hmm <- paste0(fn_alignment, ".hmm")
      if (!file.exists(fn_hmm)) {
        errmsg <- paste("Error: HMM file for step", i, "is not found. Exited.")

        log4r::error(fn_logger, errmsg)
        stop(errmsg)
      }

      # extract HMM topologies
      output <- extract_hmmtrees(fn_hmm, fn_logger,
                                fn_alignment, atsum$source[i], atsum$source[i+1],
                                dt_output, ls_topology,
                                current_start,
                                dir_output_windows, dir_output_tmp)

      dt_output <- output$out
      current_length <- output$length
      current_topology <- output$topology
      current_start <- output$start
    }
    
  } else {
    # save the last window and check if the windows have the same topology
    if (i == p || atsum$topology[i] == atsum$topology[i+1]) {
      # copy the file to other folder
      system(paste0("cp ", dir_fasta, "/", atsum$source[i], " ", dir_output_windows))
      
      # add entry to output data.table
      dt_output <- rbind(dt_output, atsum[i,])
      
      # update variables
      current_start <- current_start + atsum$length[i]
      next
    
    } else {
      # create output directory for the run
      dir_run <- paste0(dir_output_runs, i, "/")
      if (!dir.exists(dir_run)) {
        dir.create(dir_run)
      }
      
      # run seqkit to concat the sequences
      seq1 <- paste0(dir_fasta, "/", atsum$source[i])
      seq2 <- paste0(dir_fasta, "/", atsum$source[i+1])
      fn_alignment <- paste0(dir_run, "concat_", i, ".fa")
      run_seqkit(seq1, seq2, params$seqkitdir, fn_alignment)
      
      # topology file
      fn_topology <- paste0(dir_run, paste0("topology_", i, ".txt"))
      ls_topology <- c(atsum$topology[i], atsum$topology[i+1])
      write.table(ls_topology, file = fn_topology, quote = F, row.names = F, col.names = F)
      
      # run HiMAST
      seqlength <- seqinr::getLength(seqinr::read.fasta(fn_alignment))[1]
      run_himast(fn_alignment, fn_topology, 1/seqlength, mast_model, params$masthmmdir)
      
      # check if HMM file exists
      fn_hmm <- paste0(fn_alignment, ".hmm")
      if (!file.exists(fn_hmm)) {
        errmsg <- paste("Error: HMM file for step", i, "is not found. Exited.")

        log4r::error(fn_logger, errmsg)
        stop(errmsg)
      }
      
      # extract HMM per-site topology
      output <- extract_hmmtrees(fn_hmm, fn_logger,
                                fn_alignment, atsum$source[i], atsum$source[i+1],
                                dt_output, ls_topology,
                                current_start,
                                dir_output_windows, dir_output_tmp)

      dt_output <- output$out
      current_length <- output$length
      current_topology <- output$topology
      current_start <- output$start
    }
  }
}

# write the output file
data.table::fwrite(dt_output, file=fn_wh_atsum, quote=F, sep="\t")
```

```{r summary, include=FALSE}
# summarize the accuracy
msfile <- data.table::fread(fn_mstops)

mstree_uq <- unique(msfile$topology)
mstree_uq_ln <- length(mstree_uq)
smtree_uq <- unique(dt_output$topology)

# match window topology with ms topology
for (j in mstree_uq) {
  for (k in smtree_uq) {
    if (ape::all.equal.phylo(ape::unroot(ape::read.tree(text = j)), ape::read.tree(text = k))) {
      dt_output[, topology := gsub(k, j, topology, fixed = TRUE)]
      break
    }
  }
}

# create empty dataframe
output <- data.table::data.table(c(mstree_uq,"NT"), matrix(0, nrow=mstree_uq_ln+1, ncol=mstree_uq_ln))
data.table::setnames(output, c("topology", mstree_uq))

# iterate through ms topology file
for (k in 1:nrow(msfile)){
  # extract the hmm topology based on ms topology switching
  start_idx <- tail(which(dt_output$start <= msfile$start[k]), 1)
  stop_idx <- head(which(dt_output$stop >= msfile$stop[k]), 1)
  
  # update lengths
  sites <- dt_output[start_idx:stop_idx,]
  sites$start[1] <- msfile$start[k]
  sites$length[1] <- sites$stop[1] - sites$start[1] + 1
  
  last_idx <- nrow(sites)
  sites$stop[last_idx] <- msfile$stop[k]
  sites$length[last_idx] <- sites$stop[last_idx] - sites$start[last_idx] + 1
  
  topology_idx <- match(msfile$topology[k], colnames(output))
  
  # add number of window sites for the respective ms topology
  for (j in 1:nrow(sites)) {
    window_idx <- match(sites$topology[j], output$topology)
    
    if (is.na(window_idx)) {
      tempval <- as.numeric(output[mstree_uq_ln+1, ..topology_idx] + sites$length[j])
      output[mstree_uq_ln+1, eval(msfile$topology[k]) := tempval]
    } else {
      tempval <- as.numeric(output[window_idx, ..topology_idx] + sites$length[j])
      output[window_idx, eval(msfile$topology[k]) := tempval]
    }
  }
  
  rm(sites)
}

data.table::fwrite(output, file=fn_wh_cmp, quote=F, sep="\t")

# calculate accuracy
output <- as.matrix(output[,-1])
acc <- sum(as.numeric(diag(output))) / sum(as.numeric(output)) * 100
acc <- round(acc, 3)

write.table(c("",
              paste("NOW Accuracy:", wsize$accuracy[1]),
              paste("HMM Accuracy:", acc),
              paste("Changes in accuracy:", round(acc - wsize$accuracy[1], 3))),
              file=fn_log, quote=F, row.names=F, col.names=F, append=T)
```

```{r windowtree, include=FALSE}
iqtree_model <- strsplit(params$mast_model, "\\+")[[1]][1]

# set the number of threads according to the number of windows
numw <- nrow(dt_output)
tthread <- params$thread
if (numw < tthread) {
  tthread <- numw
}

prefix <- paste0(dir_output_tree, params$prefix)
  
# generate window treefile
iqtree_cmd <- paste(params$iqtree2dir,
                    "-S", dir_output_windows,
                    "-m", iqtree_model,
                    "-pre", prefix,
                    "-T", tthread,
                    "-cptime 1000000 --quiet -redo")
system(iqtree_cmd)

# compare IC value
col_idx <- match(ic_type, colnames(wsize))
fn_iqtree <- paste0(prefix, ".iqtree")

now_ic <- wsize[1,..col_idx]
hmm_ic <- 0

if (ic_type == "aic") {
  hmm_ic <- gsub("^.* ", "", system(paste("grep '^Akaike information criterion'", fn_iqtree), intern = T))
} else if (ic_type == "bic") {
  hmm_ic <- gsub("^.* ", "", system(paste("grep '^Bayesian information criterion'", fn_iqtree), intern = T))
} else if (ic_type == "aicc") {
  hmm_ic <- gsub("^.* ", "", system(paste("grep '^Corrected Akaike information criterion'", fn_iqtree), intern = T))
}

write.table(c("",
              paste0("NOW ", toupper(ic_type), ": ", now_ic),
              paste0("HMM ", toupper(ic_type), ": ", hmm_ic),
              paste("Changes in IC:", as.numeric(hmm_ic) - as.numeric(now_ic))),
              file=fn_log, quote=F, row.names=F, col.names=F, append=T)
```