---
title: "Summary for Hominidae Dataset from UCSC"
params:
  # general
  prefix: "sim"
  outdir: ""
  thread: 1
  redo: FALSE

  # stepwise NOW
  initial_wsize: 128000
  min_wsize: 1000
---

```{r, include=FALSE}
# install.packages(ape)
# install.packages(data.table)
# install.packages(viridis)

# load libraries
library(doSNOW)
library(tidyverse)

# create outdir
dir_output_prefix <- paste0(params$outdir, "/", params$prefix, "/")
dir_output_summary <- paste0(dir_output_prefix, "summary/")
if (!dir.exists(dir_output_summary)) {
    dir.create(dir_output_summary, recursive=T)
}

# output files
fn_tops_wsize <- paste0(dir_output_summary, "all.tops_wsize.tsv")
fn_tops_best_chr <- paste0(dir_output_summary, "all.best.tops_chr.tsv")

fn_tops_best_chr_tiff <- paste0(dir_output_summary, ".best.tops_chr.tiff")
fn_tops_all_best_chr_tiff <- paste0(dir_output_summary, "all.best.tops_chr.tiff")

fn_uqtops_dist_tiff <- paste0(dir_output_summary, "all.best.tops_dist.tiff")
fn_conwindows_dist_tiff <- paste0(dir_output_summary, "all.best.conwins_dist.tiff")
fn_conwindows_dist_filtered_tiff <- paste0(dir_output_summary, "all.best.conwins_dist_filtered.tiff")

suffix_all_best_wintable <- ".all.best.wintable"
suffix_all_best_toptable <- ".all.best.toptable"
suffix_all_best_contable <- ".all.best.contable"

suffix_wsize_toptable <- ".wsize_toptable"
suffix_all_wsize_toptable <- ".all.wsize_toptable"
```

```{r greatapes-functions, include=FALSE}
f_extract_perwindow_topology <- function(fn_perwindowsum, dir_output_prefix, chr, step, window_size, thread) {
    # open file
    df_perwindowsum <- data.table::fread(fn_perwindowsum)

    # create doSNOW cluster
    nwcl <- makeCluster(thread)
    doSNOW::registerDoSNOW(nwcl)

    # iterate over windows
    df_output_chr <- foreach (window=df_perwindowsum$name, .combine='rbind') %dopar% {
        # check if treefile exists
        fn_tree <- paste0(dir_output_prefix, chr, "/", step, "/", window_size, "/filtered/", window, "/", window, ".fa.treefile")
        if (!file.exists(fn_tree)) {
            return(data.table::data.table(chr=chr, wsize=window_size, topology="-"))
        }

        # open treefile
        tre <- ape::read.tree(fn_tree)
        tre$edge.length <- NULL
        tre$node.label <- NULL
        
        return(data.table::data.table(chr=chr, wsize=window_size, topology=ape::write.tree(tre)))
    }

    stopCluster(nwcl)

    return(df_output_chr)
}

f_plot_perwindow_topology_dist <- function(df_topology_count, df_topology_count_avg, topology) {
    # create a plot of all window sizes
    df_topology_count_wsize <- df_topology_count[df_topology_count$wsize!="best"]
    df_topology_count_avg_wsize <- df_topology_count_avg[df_topology_count_avg$wsize!="best"]

    plot <- ggplot(df_topology_count_wsize, aes(x=wsize, y=count_percentage, group=chr)) +
        geom_line(aes(size=1, alpha=0.2)) +
        geom_point(aes(colour=chr, size=20)) +
        viridis::scale_color_viridis(discrete = TRUE) + 
        labs(colour="Chromosome")

    if (!is.null(df_topology_count_avg_wsize)) {
        plot <- plot + geom_point(data=df_topology_count_avg_wsize, aes(x=wsize, y=count_percentage), colour="red", size=12, shape=18) +
            geom_line(data=df_topology_count_avg_wsize, aes(x=wsize, y=count_percentage), colour="red", size=4)
    }
        
    plot <- plot + ggtitle(paste("Distribution of", topology, "across Window Sizes")) + ylab("Proportion") + xlab("Window Size") +
        guides(alpha="none", size="none", colour=guide_legend(override.aes=list(size=5))) +
        theme(
            plot.title = element_text(hjust = 0.5, size = 50),
            plot.margin = margin(1.25, 1.25, 1.25, 1.25, "cm"),
            axis.title.x=element_text(size = 40, margin = margin(t=20, r=0, b=0, l=0)),
            axis.title.y=element_text(size = 40, margin = margin(t=0, r=20, b=0, l=0)),
            axis.text.y=element_text(size=30),
            axis.text.x=element_text(size=30),
            strip.text = element_text(size=30),
            legend.title=element_text(size=30),
            legend.text=element_text(size=30),
            legend.key.size=unit(2,"cm")
        )
    
    return(plot)
}
```

```{r greatapes-alltrees}
# extract the list of chromosomes
ls_chr <- list.dirs(dir_output_prefix, full.names=F, recursive=F)
ls_chr <- ls_chr[grep("^chr", ls_chr)]
ls_chr <- str_sort(ls_chr, numeric=T)

# output files
df_topology_count <- data.table::data.table(topology=character())
df_topology_consecutive <- data.table::data.table(count=numeric())

# iterate over chromosomes
for (chr in ls_chr) {
    # output files
    fn_wintable_temp <- paste0(dir_output_prefix, chr, "/", chr, suffix_all_best_wintable)
    fn_toptable_temp <- paste0(dir_output_prefix, chr, "/", chr, suffix_all_best_toptable)
    fn_contable_temp <- paste0(dir_output_prefix, chr, "/", chr, suffix_all_best_contable)
    if (all(file.exists(fn_wintable_temp, fn_toptable_temp, fn_contable_temp)) && !params$redo) {
        # combine output files
        df_toptable_temp <- data.table::fread(fn_toptable_temp)
        df_topology_count <- data.table::merge.data.table(df_topology_count, df_toptable_temp, by="topology", all=T)

        df_contable_temp <- data.table::fread(fn_contable_temp)
        df_topology_consecutive <- data.table::merge.data.table(df_topology_consecutive, df_contable_temp, by="count", all=T)

        next
    }

    # open the summary table
    fn_summary <- paste0(dir_output_prefix, chr, "/", chr, ".sumtable")
    df_summary <- data.table::fread(fn_summary)

    # extract the best window size
    best_wsize_step <- df_summary$step[nrow(df_summary)]
    best_wsize <- df_summary$s_wsize[nrow(df_summary)]

    df_summary_subset <- df_summary[df_summary$diff_aic > 0,]
    if (nrow(df_summary_subset) > 0) {
        best_wsize_step <- df_summary_subset$step[1]-1
        best_wsize <- df_summary_subset$l_wsize[1]
    }

    # iterate over windows
    fn_perwindowsum <- paste0(dir_output_prefix, chr, "/", best_wsize_step, "/", best_wsize, "/", best_wsize, ".perwindowsum")
    df_output_chr <- f_extract_perwindow_topology(fn_perwindowsum, dir_output_prefix, chr, best_wsize_step, best_wsize, params$thread)

    # save the output file
    data.table::fwrite(df_output_chr, file=fn_wintable_temp, sep="\t", quote=F)

    # count number of unique topology
    df_topology_count_temp <- df_output_chr %>%
        group_by(topology) %>%
        filter(topology!="-") %>%
        summarise(!!chr:=n())

    # save the output file
    data.table::fwrite(df_topology_count_temp, file=fn_toptable_temp, sep="\t", quote=F)
    df_topology_count <- data.table::merge.data.table(df_topology_count, df_topology_count_temp, by="topology", all=T)

    # count number of consecutive topology
    df_topology_consecutive_temp <- df_output_chr %>%
        group_by(topology,
                 group_run=data.table::rleid(topology)) %>%
        summarise(count=n()) %>%
        group_by(count) %>%
        summarise(!!chr:=n())

    # save the output file
    data.table::fwrite(df_topology_consecutive_temp, file=fn_contable_temp, sep="\t", quote=F)
    df_topology_consecutive <- data.table::merge.data.table(df_topology_consecutive, df_topology_consecutive_temp, by="count", all=T)
}

# transform data.table
df_topology_count_long <- tidyr::pivot_longer(df_topology_count, cols = -topology, names_to = "chr", values_to = "count")
df_topology_count_long <- df_topology_count_long %>%
    filter(!is.na(count)) %>%
    mutate(count_percentage=count/sum(count))
df_topology_count_long$chr <- fct_inorder(df_topology_count_long$chr)
data.table::fwrite(df_topology_count_long, file=fn_tops_best_chr, sep="\t", quote=F)

df_topology_consecutive_long <- tidyr::pivot_longer(df_topology_consecutive, cols = -count, names_to = "chr", values_to = "n")
df_topology_consecutive_long$chr <- fct_inorder(df_topology_consecutive_long$chr)

# visualisation for unique topology count
plot <- ggplot(df_topology_count_long, aes(x=topology, y=count_percentage, fill=chr)) +
    geom_col() +
    ggtitle("Topology Distribution across Chromosome") +
    xlab("Topology") + ylab("Proportion") +
    theme(
      plot.title = element_text(hjust = 0.5, size = 50),
      plot.margin = margin(1.25, 1.25, 1.25, 1.25, "cm"),
      axis.title.x=element_text(size = 40, margin = margin(t=20, r=0, b=0, l=0)),
      axis.title.y=element_text(size = 40, margin = margin(t=0, r=20, b=0, l=0)),
      axis.text.y=element_text(size=30),
      axis.text.x=element_text(size=30),
      strip.text = element_text(size=30),
      legend.title=element_text(size=30),
      legend.text=element_text(size=30),
      legend.key.size=unit(2,"cm")
    )

tiff(filename=fn_uqtops_dist_tiff, units="px", width=2880, height=1800)
print(plot)
dev.off()

# visualisation for consecutive windows
plot <- ggplot(df_topology_consecutive_long, aes(x=count, y=n, fill=chr)) +
    geom_col() +
    ggtitle("Consecutive Topology Distribution across Chromosome") +
    xlab("Number of consecutive windows") + ylab("Count") +
    theme(
      plot.title = element_text(hjust = 0.5, size = 50),
      plot.margin = margin(1.25, 1.25, 1.25, 1.25, "cm"),
      axis.title.x=element_text(size = 40, margin = margin(t=20, r=0, b=0, l=0)),
      axis.title.y=element_text(size = 40, margin = margin(t=0, r=20, b=0, l=0)),
      axis.text.y=element_text(size=30),
      axis.text.x=element_text(size=30),
      strip.text = element_text(size=30),
      legend.title=element_text(size=30),
      legend.text=element_text(size=30),
      legend.key.size=unit(2,"cm")
    )

tiff(filename=fn_conwindows_dist_tiff, units="px", width=2880, height=1800)
print(plot)
dev.off()

# visualisation for consecutive windows with count>1
plot <- ggplot(df_topology_consecutive_long[df_topology_consecutive_long$n>1,], aes(x=count, y=n, fill=chr)) +
    geom_col() +
    ggtitle("Consecutive Topology Distribution across Chromosome with Count>1") +
    xlab("Number of consecutive windows") + ylab("Count") +
    theme(
      plot.title = element_text(hjust = 0.5, size = 50),
      plot.margin = margin(1.25, 1.25, 1.25, 1.25, "cm"),
      axis.title.x=element_text(size = 40, margin = margin(t=20, r=0, b=0, l=0)),
      axis.title.y=element_text(size = 40, margin = margin(t=0, r=20, b=0, l=0)),
      axis.text.y=element_text(size=30),
      axis.text.x=element_text(size=30),
      strip.text = element_text(size=30),
      legend.title=element_text(size=30),
      legend.text=element_text(size=30),
      legend.key.size=unit(2,"cm")
    )

tiff(filename=fn_conwindows_dist_filtered_tiff, units="px", width=2880, height=1800)
print(plot)
dev.off()
```

```{r greatapes-highbs-tree-wsize}
# output files
df_topology_count <- data.table::data.table(chr=factor(), wsize=factor(), topology=character(), count=numeric(), count_percentage=numeric())

# iterate over chromosomes
for (chr in ls_chr) {
    # output files
    fn_wsize_toptable_temp <- paste0(dir_output_prefix, chr, "/", chr, suffix_wsize_toptable)
    if (file.exists(fn_wsize_toptable_temp) && !params$redo) {
        # combine output files
        df_wsize_toptable_temp <- data.table::fread(fn_wsize_toptable_temp)
        df_topology_count <- rbind(df_topology_count, df_wsize_toptable_temp)

        next
    }

    # open the summary table
    fn_summary <- paste0(dir_output_prefix, chr, "/", chr, ".sumtable")
    df_summary <- data.table::fread(fn_summary)

    # extract steps with specified range of window sizes
    df_summary_subset <- df_summary[df_summary$l_wsize<=params$initial_wsize]
    df_summary_subset <- df_summary_subset[df_summary_subset$s_wsize>=params$min_wsize]

    # set up number of threads
    stepthread <- ifelse(nrow(df_summary_subset) < params$thread, nrow(df_summary_subset), params$thread)

    # create doSNOW cluster
    nwcl <- makeCluster(stepthread)
    doSNOW::registerDoSNOW(nwcl)

    # iterate over window sizes
    output <- foreach (step = 1:nrow(df_summary_subset), .combine='rbind') %dopar% {
        # set up variables
        long_wsize <- df_summary_subset$l_wsize[step]
        short_wsize <- df_summary_subset$s_wsize[step]

        df_topology_count_temp <- data.table::data.table(chr=factor(), wsize=factor(), topology=character(), count=numeric(), count_percentage=numeric())

        # check if it is the initial step
        if (step == 1) {
            # input files
            fn_uqtops <- paste0(dir_output_prefix, chr, "/", step, "/", long_wsize, "/", long_wsize, ".uqtops")
            if (file.exists(fn_uqtops)) {
                # open file
                df_uqtops_temp <- data.table::fread(fn_uqtops)

                # update data.table
                df_topology_count_temp <- rbind(df_topology_count_temp,
                                                data.table::data.table(chr=rep(chr, nrow(df_uqtops_temp)),
                                                                       wsize=rep(long_wsize, nrow(df_uqtops_temp)),
                                                                       topology=df_uqtops_temp$topology,
                                                                       count=df_uqtops_temp$n,
                                                                       count_percentage=df_uqtops_temp$n/sum(df_uqtops_temp$n)))
            }
        }

        # work on the short window size
        fn_uqtops <- paste0(dir_output_prefix, chr, "/", step, "/", short_wsize, "/", short_wsize, ".uqtops")
        if (file.exists(fn_uqtops)) {
            # open file
            df_uqtops_temp <- data.table::fread(fn_uqtops)

            # update data.table
            df_topology_count_temp <- rbind(df_topology_count_temp,
                                            data.table::data.table(chr=rep(chr, nrow(df_uqtops_temp)),
                                                                   wsize=rep(short_wsize, nrow(df_uqtops_temp)),
                                                                   topology=df_uqtops_temp$topology,
                                                                   count=df_uqtops_temp$n,
                                                                   count_percentage=df_uqtops_temp$n/sum(df_uqtops_temp$n)))
        }

        return(df_topology_count_temp)
    }

    stopCluster(nwcl)

    # save data.table
    data.table::fwrite(output, file=fn_wsize_toptable_temp, sep="\t", quote=F)

    # update data.table
    df_topology_count <- rbind(df_topology_count, output)
}

# open the topology distribution for the best window sizes for each chromosome
for (chr in ls_chr) {
    # open the summary table
    fn_summary <- paste0(dir_output_prefix, chr, "/", chr, ".sumtable")
    df_summary <- data.table::fread(fn_summary)

    # extract the best window size
    best_wsize_step <- df_summary$step[nrow(df_summary)]
    best_wsize <- df_summary$s_wsize[nrow(df_summary)]

    df_summary_subset <- df_summary[df_summary$diff_aic > 0,]
    if (nrow(df_summary_subset) > 0) {
        best_wsize_step <- df_summary_subset$step[1]-1
        best_wsize <- df_summary_subset$l_wsize[1]
    }

    # iterate over windows
    fn_uqtops <- paste0(dir_output_prefix, chr, "/", best_wsize_step, "/", best_wsize, "/", best_wsize, ".uqtops")
    df_uqtops <- data.table::fread(fn_uqtops)

    # transform data.table
    df_uqtops_transform <- df_uqtops %>%
        select(topology,n) %>%
        mutate(chr=chr, wsize="best", count_percentage=n/sum(n))

    # update data.table
    df_topology_count <- rbind(df_topology_count, df_uqtops_transform)
}

# check if the best window size has all topologies
ls_topologies <- unique(df_topology_count$topology)
for (chr in ls_chr) {
    # open the summary table
    fn_summary <- paste0(dir_output_prefix, chr, "/", chr, ".sumtable")
    df_summary <- data.table::fread(fn_summary)

    # extract steps with specified range of window sizes
    df_summary_subset <- df_summary[df_summary$l_wsize<=params$initial_wsize]
    df_summary_subset <- df_summary_subset[df_summary_subset$s_wsize>=params$min_wsize]

    # extract window sizes
    ls_wsize <- c("best", unique(c(df_summary_subset$l_wsize, df_summary_subset$s_wsize)))

    for (wsize in ls_wsize) {
        for (top in ls_topologies) {
            count_temp <- df_topology_count$count[df_topology_count$wsize==wsize & df_topology_count$chr==chr & df_topology_count$topology==top]

            if (length(count_temp) == 0) {
                df_topology_count <- rbind(df_topology_count,
                                           data.table::data.table(chr=chr, wsize=wsize, topology=top, count=0, count_percentage=0))
            }
        }
    }
}

# new data.frame to store average proportion
df_topology_count_avg <- df_topology_count %>%
    group_by(wsize, topology) %>%
    summarise(count=sum(count)) %>%
    group_by(wsize) %>%
    mutate(total_count=sum(count), count_percentage=count/total_count)

# visualisation for all window sizes
top_counter <- 1
for (top in sort(unique(df_topology_count$topology))) {
    # subset the data.table
    df_topology_count_subset <- df_topology_count[df_topology_count$topology==top,]
    df_topology_count_avg_subset <- df_topology_count_avg[df_topology_count_avg$topology==top,]

    # output file
    fn_topology_count <- paste0(dir_output_summary, "top", top_counter, "_wsize.tiff")

    tiff(filename=fn_topology_count, units="px", width=2880, height=1800)
    print(f_plot_perwindow_topology_dist(df_topology_count_subset, df_topology_count_avg_subset, top))
    dev.off()

    top_counter <- top_counter + 1
}

# visualisation for best window sizes
df_topology_count_subset <- df_topology_count[df_topology_count$wsize=="best",]

plot <- ggplot(df_topology_count_subset, aes(x=topology, y=count_percentage)) +
    geom_boxplot(outlier.shape = NA) +
    geom_point(shape=16, aes(colour=chr)) +
    ggtitle("Topology Distribution for Best Window Sizes across Chromosomes") +
    xlab("Topology") + ylab("Proportion") +
    theme(
      plot.title = element_text(hjust = 0.5, size = 50),
      plot.margin = margin(1.25, 1.25, 1.25, 1.25, "cm"),
      axis.title.x=element_text(size = 40, margin = margin(t=20, r=0, b=0, l=0)),
      axis.title.y=element_text(size = 40, margin = margin(t=0, r=20, b=0, l=0)),
      axis.text.y=element_text(size=30),
      axis.text.x=element_text(size=30),
      strip.text = element_text(size=30),
      legend.title=element_text(size=30),
      legend.text=element_text(size=30),
      legend.key.size=unit(2,"cm")
    )

tiff(filename=fn_tops_best_chr_tiff, units="px", width=2880, height=1800)
print(plot)
dev.off()
```

```{r greatapes-all-tree-wsize}
# output files
df_topology_count <- data.table::data.table(chr=factor(), wsize=factor(), topology=character(), count=numeric(), count_percentage=numeric())

# iterate over chromosomes
for (chr in ls_chr) {
    # output data.table
    df_topology_count_temp <- data.table::data.table(chr=factor(), wsize=factor(), topology=character(), count=numeric(), count_percentage=numeric())

    # output files
    fn_wsize_toptable_temp <- paste0(dir_output_prefix, chr, "/", chr, suffix_all_wsize_toptable)
    if (file.exists(fn_wsize_toptable_temp) && !params$redo) {
        # combine output files
        df_wsize_toptable_temp <- data.table::fread(fn_wsize_toptable_temp)
        df_topology_count <- rbind(df_topology_count, df_wsize_toptable_temp)

        next
    }

    # open the summary table
    fn_summary <- paste0(dir_output_prefix, chr, "/", chr, ".sumtable")
    df_summary <- data.table::fread(fn_summary)

    # extract steps with specified range of window sizes
    df_summary_subset <- df_summary[df_summary$l_wsize<=params$initial_wsize]
    df_summary_subset <- df_summary_subset[df_summary_subset$s_wsize>=params$min_wsize]

    # iterate over window sizes
    for (step in 1:nrow(df_summary_subset)) {
        # set up variables
        long_wsize <- df_summary_subset$l_wsize[step]
        short_wsize <- df_summary_subset$s_wsize[step]

        # check if it is the initial step
        if (step == 1) {
            fn_perwindowsum <- paste0(dir_output_prefix, chr, "/", step, "/", long_wsize, "/", long_wsize, ".perwindowsum")
            if (file.exists(fn_perwindowsum)) {
                df_output_wsize <- f_extract_perwindow_topology(fn_perwindowsum, dir_output_prefix, chr, step, long_wsize, params$thread)

                # transform data.table
                df_output_wsize <- df_output_wsize %>%
                    filter(topology!="-") %>%
                    group_by(chr,wsize,topology) %>%
                    summarise(count=n()) %>%
                    mutate(count_percentage=count/sum(count))

                # update data.table    
                df_topology_count_temp <- rbind(df_topology_count_temp, df_output_wsize)
            }
        }

        # work on the short window size
        fn_perwindowsum <- paste0(dir_output_prefix, chr, "/", step, "/", short_wsize, "/", short_wsize, ".perwindowsum")
        if (file.exists(fn_perwindowsum)) {
            df_output_wsize <- f_extract_perwindow_topology(fn_perwindowsum, dir_output_prefix, chr, step, short_wsize, params$thread)

            # transform data.table
            df_output_wsize <- df_output_wsize %>%
                filter(topology!="-") %>%
                group_by(chr,wsize,topology) %>%
                summarise(count=n()) %>%
                mutate(count_percentage=count/sum(count))

            # update data.table    
            df_topology_count_temp <- rbind(df_topology_count_temp, df_output_wsize)
        }
    }

    # save data.table
    data.table::fwrite(df_topology_count_temp, file=fn_wsize_toptable_temp, sep="\t", quote=F)

    # update data.table
    df_topology_count <- rbind(df_topology_count, df_topology_count_temp)
}

# open the topology distribution for the best window sizes for each chromosome
for (chr in ls_chr) {
    # input file
    fn_toptable_temp <- paste0(dir_output_prefix, chr, "/", chr, suffix_all_best_toptable)
    if (!file.exists(fn_toptable_temp)) {
        next
    }

    # open data.table
    df_toptable_temp <- data.table::fread(fn_toptable_temp)
    data.table::setnames(df_toptable_temp, c("topology", "count"))

    # convert data.table following the big data.table
    df_toptable_temp <- df_toptable_temp %>%
        mutate(chr=chr, wsize="best", count_percentage=count/sum(count))

    # update data.table
    df_topology_count <- rbind(df_topology_count, df_toptable_temp)
}

# check if the best window size has all topologies
ls_topologies <- unique(df_topology_count$topology)
for (chr in ls_chr) {
    # open the summary table
    fn_summary <- paste0(dir_output_prefix, chr, "/", chr, ".sumtable")
    df_summary <- data.table::fread(fn_summary)

    # extract steps with specified range of window sizes
    df_summary_subset <- df_summary[df_summary$l_wsize<=params$initial_wsize]
    df_summary_subset <- df_summary_subset[df_summary_subset$s_wsize>=params$min_wsize]

    # extract window sizes
    ls_wsize <- c("best", unique(c(df_summary_subset$l_wsize, df_summary_subset$s_wsize)))

    for (wsize in ls_wsize) {
        for (top in ls_topologies) {
            count_temp <- df_topology_count$count[df_topology_count$wsize==wsize & df_topology_count$chr==chr & df_topology_count$topology==top]

            if (length(count_temp) == 0) {
                df_topology_count <- rbind(df_topology_count,
                                           data.table::data.table(chr=chr, wsize=wsize, topology=top, count=0, count_percentage=0))
            }
        }
    }
}

# new data.frame to store average proportion
df_topology_count_avg <- df_topology_count %>%
    group_by(wsize, topology) %>%
    summarise(count=sum(count)) %>%
    group_by(wsize) %>%
    mutate(total_count=sum(count), count_percentage=count/total_count)

data.table::fwrite(df_topology_count_avg, file=fn_tops_wsize, sep="\t", quote=F)

# visualisation for all window sizes
top_counter <- 1
for (top in sort(unique(df_topology_count$topology))) {
    # subset the data.table
    df_topology_count_subset <- df_topology_count[df_topology_count$topology==top,]
    df_topology_count_avg_subset <- df_topology_count_avg[df_topology_count_avg$topology==top,]

    # output file
    fn_topology_count <- paste0(dir_output_summary, "all.top", top_counter, "_wsize.tiff")

    tiff(filename=fn_topology_count, units="px", width=2880, height=1800)
    print(f_plot_perwindow_topology_dist(df_topology_count_subset, df_topology_count_avg_subset, top))
    dev.off()

    top_counter <- top_counter + 1
}

# visualisation for best window sizes
df_topology_count_subset <- df_topology_count[df_topology_count$wsize=="best",]

plot <- ggplot(df_topology_count_subset, aes(x=topology, y=count_percentage)) +
    geom_boxplot(outlier.shape = NA) +
    geom_point(shape=16, aes(colour=chr)) +
    ggtitle("Topology Distribution for Best Window Sizes across Chromosomes") +
    xlab("Topology") + ylab("Proportion") +
    theme(
      plot.title = element_text(hjust = 0.5, size = 50),
      plot.margin = margin(1.25, 1.25, 1.25, 1.25, "cm"),
      axis.title.x=element_text(size = 40, margin = margin(t=20, r=0, b=0, l=0)),
      axis.title.y=element_text(size = 40, margin = margin(t=0, r=20, b=0, l=0)),
      axis.text.y=element_text(size=30),
      axis.text.x=element_text(size=30),
      strip.text = element_text(size=30),
      legend.title=element_text(size=30),
      legend.text=element_text(size=30),
      legend.key.size=unit(2,"cm")
    )

tiff(filename=fn_tops_all_best_chr_tiff, units="px", width=2880, height=1800)
print(plot)
dev.off()
```