---
title: "Summary of Multiple Non-overlapping Windows Analyses"
params:
  # general
  codedir: "~/SimNOW/empirical_analysis"
  prefix: "sim"
  thread: 10
  outdir: "~/simulation"

  initial_wsize: 64000
  colour_scheme: ""
---
```{r heliconius-setup, include=FALSE}
# install.packages('ape')

# load libraries
library(data.table)
library(doSNOW)
library(tidyverse)

# load functions
source(paste0(params$codedir,"/datasets/heliconius_erato/codes/functions.R"), local=TRUE)
source(paste0(params$codedir,"/datasets/hominidae/codes/functions.R"), local=TRUE)

# output directory
dir_prefix <- paste0(params$outdir, "/", params$prefix, "/")
dir_summary <- paste0(dir_prefix, "summary/")
if (!dir.exists(dir_summary)) {
  dir.create(dir_summary, recursive=T)
}

# output files
fn_best_uqtops <- paste0(dir_summary, "best.uqtops")

fn_uqtops_dist_tiff <- paste0(dir_summary, "all.best.tops_dist.tiff")
fn_conwindows_tiff <- paste0(dir_summary, "all.best.conwins.tiff")
fn_conwindows_chr_tiff <- paste0(dir_summary, "all.best.conwins_chr.tiff")

suffix_all_best_wintable <- ".all.best.wintable"
suffix_all_best_toptable <- ".all.best.toptable"
suffix_all_best_contable <- ".all.best.contable"
```

```{r heliconius-summary, include=FALSE}
allsims <- list.dirs(paste0(params$outdir,"/",params$prefix), full.names = F, recursive = F)
chrs <- allsims[grep("^chr", allsims)]
chrs <- stringr::str_sort(chrs, numeric=TRUE)

# extract window sizes
max_wsize <- params$initial_wsize
wsizes <- max_wsize
while (max_wsize %% 2 == 0) {
  wsizes <- c(wsizes, max_wsize / 2)
  max_wsize <- max_wsize / 2
}
wsizes <- sort(wsizes, decreasing=T)

for (i in 1:length(wsizes)) {
  fn_output <- paste0(dir_summary, wsizes[i], ".uqtops")

  if (i == 1) {
      f_count_topology_freq(wsizes[i], chrs, i, paste0(params$outdir,"/",params$prefix), fn_output)
  } else {
      f_count_topology_freq(wsizes[i], chrs, i-1, paste0(params$outdir,"/",params$prefix), fn_output)
  }
}

# summary for best window size
df_best_wsize <- data.table::data.table()

# iterate over chromosomes
for (c in chrs) {
  # open summary table
  fn_summary <- paste0(params$outdir, "/", params$prefix, "/", c, "/", c, ".sumtable")
  if (!file.exists(fn_summary)) {
    cat(paste("Error:", fn_summary, "is not found. Exited"))
    knitr::knit_exit()
  }

  # read summary table
  df_summary <- data.table::fread(fn_summary)

  # choose the best window size
  i <- 1
  for (j in nrow(df_summary):1) {
    if (df_summary$diff_aic[j] < 0) {
      i <- j
      break
    }
  }

  # read unique topology file
  best_wsize <- df_summary$s_wsize[i]
  fn_uqtops <- paste0(params$outdir, "/", params$prefix, "/", c, "/", df_summary$step[i], "/", best_wsize, "/", best_wsize, ".uqtops")
  if (!file.exists(fn_uqtops)) {
    cat(paste("Error:", fn_uqtops, "is not found. Exited"))
    knitr::knit_exit()
  }

  # read summary table
  df_uqtops <- data.table::fread(fn_uqtops)

  df_best_wsize <- f_compare_topology_weight(df_best_wsize, df_uqtops, paste0(c, ".", best_wsize))
}

# add the total topology count
df_colnames <- colnames(df_best_wsize)[2:ncol(df_best_wsize)]

# convert columns in numeric
df_best_wsize[, (df_colnames) := lapply(.SD, as.numeric), .SDcols = df_colnames]

df_best_wsize <- df_best_wsize %>%
  mutate(n = rowSums(select(., all_of(df_colnames)))) %>%
  arrange(desc(n)) %>%
  mutate(cum.percentage=round(cumsum(n)/sum(n)*100,3))

# write the output data.table
data.table::fwrite(df_best_wsize, file=fn_best_uqtops, quote=FALSE, sep="\t")
```

```{r heliconius-alltrees}
# extract the list of chromosomes
ls_chr <- str_sort(chrs, numeric=T)

# output files
df_topology_count <- data.table::data.table(topology=character())
df_topology_consecutive <- data.table::data.table(topology=character(), count=numeric())

# iterate over chromosomes
for (chr in ls_chr) {
    # output files
    fn_wintable_temp <- paste0(dir_prefix, chr, "/", chr, suffix_all_best_wintable)
    fn_toptable_temp <- paste0(dir_prefix, chr, "/", chr, suffix_all_best_toptable)
    fn_contable_temp <- paste0(dir_prefix, chr, "/", chr, suffix_all_best_contable)
    if (all(file.exists(fn_wintable_temp, fn_toptable_temp, fn_contable_temp)) && !params$redo) {
        # combine output files
        df_toptable_temp <- data.table::fread(fn_toptable_temp)
        df_topology_count <- data.table::merge.data.table(df_topology_count, df_toptable_temp, by="topology", all=T)

        df_contable_temp <- data.table::fread(fn_contable_temp)
        df_topology_consecutive <- data.table::merge.data.table(df_topology_consecutive, df_contable_temp, by=c("topology","count"), all=T)

        next
    }

    # open the summary table
    fn_summary <- paste0(dir_prefix, chr, "/", chr, ".sumtable")
    df_summary <- data.table::fread(fn_summary)

    # extract the best window size
    best_wsize_step <- df_summary$step[nrow(df_summary)]
    best_wsize <- df_summary$s_wsize[nrow(df_summary)]

    df_summary_subset <- df_summary[df_summary$diff_aic > 0,]
    if (nrow(df_summary_subset) > 0) {
        best_wsize_step <- df_summary_subset$step[1]-1
        best_wsize <- df_summary_subset$l_wsize[1]
    }

    # iterate over windows
    fn_perwindowsum <- paste0(dir_prefix, chr, "/", best_wsize_step, "/", best_wsize, "/", best_wsize, ".perwindowsum")
    df_output_chr <- f_extract_perwindow_topology(fn_perwindowsum, dir_prefix, chr, best_wsize_step, best_wsize, params$thread)

    # save the output file
    data.table::fwrite(df_output_chr, file=fn_wintable_temp, sep="\t", quote=F)

    # count number of unique topology
    df_topology_count_temp <- df_output_chr %>%
        group_by(topology) %>%
        filter(topology!="-") %>%
        summarise(!!chr:=n())

    # save the output file
    data.table::fwrite(df_topology_count_temp, file=fn_toptable_temp, sep="\t", quote=F)
    df_topology_count <- data.table::merge.data.table(df_topology_count, df_topology_count_temp, by="topology", all=T)

    # count number of consecutive topology
    df_topology_consecutive_temp <- df_output_chr %>%
        group_by(topology,
                 group_run=data.table::rleid(topology)) %>%
        summarise(count=n()) %>%
        group_by(topology,count) %>%
        summarise(!!chr:=n())

    # save the output file
    data.table::fwrite(df_topology_consecutive_temp, file=fn_contable_temp, sep="\t", quote=F)
    df_topology_consecutive <- data.table::merge.data.table(df_topology_consecutive, df_topology_consecutive_temp, by=c("topology","count"), all=T)
}

# filter out topologies
ls_uq_tops <- unique(df_topology_count$topology)
df_topology <- data.table(topology=ls_uq_tops, colour=NA, tree=ls_uq_tops)

if (length(params$colour_scheme) != 0) {
  df_topology <- data.table(topology=character(), colour=character(), tree=character())
  df_colour_scheme <- fread(params$colour_scheme)

  # iterate over topologies
  for (j in 1:nrow(df_colour_scheme)) {
    for (top in ls_uq_tops) {
      # extract topologies
      top1 <- ape::read.tree(text=df_colour_scheme$topology[j])
      top2 <- ape::read.tree(text=top)

      if (ape::all.equal.phylo(top1, top2)) {
        df_topology <- rbind(df_topology, data.table(topology=top, colour=df_colour_scheme$code[j], tree=df_colour_scheme$tree[j]))
        break
      }
    }
  }
}

# transform data.table
df_topology_count_long <- tidyr::pivot_longer(df_topology_count, cols = starts_with("chr"), names_to = "chr", values_to = "count")
df_topology_count_long <- df_topology_count_long %>%
    filter(!is.na(count) & topology%in%df_topology$topology) %>%
    mutate(count_percentage=count/sum(count), chr=fct_inorder(chr)) %>%
    left_join(df_topology, by="topology") %>%
    arrange(readr::parse_number(tree)) %>%
    mutate(tree=fct_inorder(tree))

df_topology_consecutive_long <- tidyr::pivot_longer(df_topology_consecutive, cols = starts_with("chr"), names_to = "chr", values_to = "n")
df_topology_consecutive_long <- df_topology_consecutive_long %>%
    filter(topology%in%df_topology$topology) %>%
    mutate(chr=fct_inorder(chr)) %>%
    left_join(df_topology, by="topology") %>%
    arrange(readr::parse_number(tree)) %>%
    mutate(tree=fct_inorder(tree))

# visualisation for unique topology count
plot <- ggplot(df_topology_count_long, aes(x=tree, y=count_percentage))
if (all(is.na(df_topology_count_long$colour))) {
  plot <- plot + geom_col(aes(fill=chr)) + viridis::scale_fill_viridis(discrete = TRUE)
} else {
  plot <- plot + geom_col(aes(fill=colour)) + scale_fill_identity()
}

plot <- plot +
    ggtitle("Topology Distribution across Chromosome") +
    xlab("Topology") + ylab("Proportion") +
    theme(
      plot.title = element_text(hjust = 0.5, size = 50),
      plot.margin = margin(1.25, 1.25, 1.25, 1.25, "cm"),
      axis.title.x=element_text(size = 40, margin = margin(t=20, r=0, b=0, l=0)),
      axis.title.y=element_text(size = 40, margin = margin(t=0, r=20, b=0, l=0)),
      axis.text.y=element_text(size=30),
      axis.text.x=element_text(size=30),
      strip.text = element_text(size=30),
      legend.title=element_text(size=30),
      legend.text=element_text(size=30),
      legend.key.size=unit(2,"cm")
    )

tiff(filename=fn_uqtops_dist_tiff, units="px", width=2880, height=1800)
print(plot)
dev.off()

# visualisation for consecutive windows
plot <- ggplot(df_topology_consecutive_long, aes(x=count, y=n))
if (all(is.na(df_topology_consecutive_long$colour))) {
  plot <- plot + geom_col(aes(fill=chr)) + viridis::scale_fill_viridis(discrete = TRUE)
} else {
  plot <- plot + geom_col(aes(fill=colour)) + scale_fill_identity()
}

plot <- plot +
    ggtitle("Consecutive Topology Distribution across Chromosome") +
    facet_wrap(.~tree, scales="free", ncol=1) +
    xlab("Number of consecutive windows") + ylab("Count") +
    theme(
      plot.title=element_text(hjust=0.5, size=50),
      plot.margin=margin(1.25, 1.25, 1.25, 1.25, "cm"),
      axis.title.x=element_text(size=40, margin=margin(t=20, r=0, b=0, l=0)),
      axis.title.y=element_text(size=40, margin=margin(t=0, r=20, b=0, l=0)),
      axis.text.y=element_text(size=30),
      axis.text.x=element_text(size=30),
      strip.text=element_text(size=30),
      legend.title=element_text(size=30),
      legend.text=element_text(size=30),
      legend.key.size=unit(2,"cm")
    )

tiff(filename=fn_conwindows_tiff, units="px", width=1600, height=2800)
print(plot)
dev.off()

# visualisation for consecutive windows per chromosome
plot <- plot +
    ggtitle("Consecutive Topology Distribution across Chromosome") +
    facet_grid(chr~tree, scales="free") +
    xlab("Number of consecutive windows") + ylab("Count") +
    theme(
      plot.title=element_text(hjust=0.5, size=50),
      plot.margin=margin(1.25, 1.25, 1.25, 1.25, "cm"),
      axis.title.x=element_text(size=40, margin=margin(t=20, r=0, b=0, l=0)),
      axis.title.y=element_text(size=40, margin=margin(t=0, r=20, b=0, l=0)),
      axis.text.y=element_text(size=30),
      axis.text.x=element_text(size=30),
      strip.text=element_text(size=30),
      legend.title=element_text(size=30),
      legend.text=element_text(size=30),
      legend.key.size=unit(2,"cm"),
      panel.spacing.y=unit(1.5,"lines")
    )

tiff(filename=fn_conwindows_chr_tiff, units="px", width=2100, height=8000)
print(plot)
dev.off()
```